
rem mainmenu
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\mainmenu_slim\IMAGE_MAINMENU_ICON_SELECT.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\mainmenu_slim\IMAGE_MAINMENU_ICON_ENV.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\mainmenu_slim\IMAGE_MAINMENU_ICON_STK.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\mainmenu_slim\IMAGE_MAINMENU_ICON_DYNAMIC_DEFAUL.png

echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\mainmenu_slim\IMAGE_MAINMENU_ICON_ITEM_TEXT_BG.png

echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Secondmenu_icon\IMAGE_SECMENU_ICON_TOOL_IKEYBACKUP.png


rem Bg
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Bg\IMAGE_COMMON_BG.png


rem Statusbar
echo y | xcopy 1.png ".\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon\signal_w\primo_status bar_VoLTE.png"
echo y | xcopy 1.png ".\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon\signal_w\primo_status bar_HD.png"
echo y | xcopy 1.png ".\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon\signal_w\primo_calling view_volte.png"
echo y | xcopy 1.png ".\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon\signal_w\primo_calling view_hd.png"


rem cc
echo y | xcopy 1.png .\mmi_res_240x240\cc\MMI_RES_DEFAULT\IMAG\cc\IAMGE_CALL_DEFAULT_PHOTO.png


rem tools
echo y | xcopy 1.png .\mmi_res_240x240\tools\MMI_RES_DEFAULT\IMAG\IMAGE_EXTRAS_FLASHLIGHT_BACK_RED.png
echo y | xcopy 1.png .\mmi_res_240x240\tools\MMI_RES_DEFAULT\IMAG\IMAGE_EXTRAS_FLASHLIGHT_LSK.png
echo y | xcopy 1.png .\mmi_res_240x240\tools\MMI_RES_DEFAULT\IMAG\IMAGE_EXTRAS_FLASHLIGHT_LSK_RED.png
echo y | xcopy 1.png .\mmi_res_240x240\tools\MMI_RES_DEFAULT\IMAG\IMAGE_EXTRAS_FLASHLIGHT_OFF.png
echo y | xcopy 1.png .\mmi_res_240x240\tools\MMI_RES_DEFAULT\IMAG\IMAGE_EXTRAS_FLASHLIGHT_ON_RED.png
echo y | xcopy 1.png .\mmi_res_240x240\tools\MMI_RES_DEFAULT\IMAG\IMAGE_EXTRAS_TIMER.png
echo y | xcopy 1.png .\mmi_res_240x240\tools\MMI_RES_DEFAULT\IMAG\IMAGE_EXTRAS_RESET.png
echo y | xcopy 1.png .\mmi_res_240x240\tools\MMI_RES_DEFAULT\IMAG\IMAGE_EXTRAS_STOPWATCH.png


rem wait
echo y | xcopy 2.gif .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Waiting_indicator\red_dark.gif
echo y | xcopy 2.gif .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Waiting_indicator\yellow.gif
echo y | xcopy 2.gif .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Waiting_indicator\yellow_dark.gif
echo y | xcopy 2.gif .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Waiting_indicator\red.gif


rem im
echo y | xcopy 1.png .\mmi_res_240x240\im\MMI_RES_DEFAULT\IMAG\SKIN_1\IMG_IMSP_ARROW_DOWN_DIS.png
echo y | xcopy 1.png .\mmi_res_240x240\im\MMI_RES_DEFAULT\IMAG\SKIN_1\IMG_IMSP_ARROW_DOWN_OFF.png




echo y | xcopy 1.bmp ".\mmi_res_240x240\camera\MMI_RES_DEFAULT\IMAG\DC OSD\IMG_DC_PHOTO_TIP.bmp"
echo y | xcopy 1.bmp ".\mmi_res_240x240\camera\MMI_RES_DEFAULT\IMAG\DC OSD\IMG_DC_VIDEO_TIP.bmp"
echo y | xcopy 1.bmp ".\mmi_res_240x240\camera\MMI_RES_DEFAULT\IMAG\DC OSD\IMG_DC_WAIT.bmp"
echo y | xcopy 1.bmp ".\mmi_res_240x240\camera\MMI_RES_DEFAULT\IMAG\DC OSD\IMG_DC_RECORD.bmp"
echo y | xcopy 1.bmp ".\mmi_res_240x240\camera\MMI_RES_DEFAULT\IMAG\DC OSD\IMG_DC_MENU_DOWN.bmp"
echo y | xcopy 1.bmp ".\mmi_res_240x240\camera\MMI_RES_DEFAULT\IMAG\DC OSD\IMG_DC_MENU_UP.bmp"
echo y | xcopy 1.bmp ".\mmi_res_240x240\camera\MMI_RES_DEFAULT\IMAG\DC OSD\IMG_DC_ADJUST_1.bmp"
echo y | xcopy 1.bmp ".\mmi_res_240x240\camera\MMI_RES_DEFAULT\IMAG\DC OSD\IMG_DC_ADJUST_2.bmp"
echo y | xcopy 1.bmp ".\mmi_res_240x240\camera\MMI_RES_DEFAULT\IMAG\DC OSD\IMG_DC_ADJUST_3.bmp"
echo y | xcopy 1.bmp ".\mmi_res_240x240\camera\MMI_RES_DEFAULT\IMAG\DC OSD\IMG_DC_ADJUST_4.bmp"
echo y | xcopy 1.bmp ".\mmi_res_240x240\camera\MMI_RES_DEFAULT\IMAG\DC OSD\IMG_DC_ADJUST_5.bmp"
echo y | xcopy 1.bmp ".\mmi_res_240x240\camera\MMI_RES_DEFAULT\IMAG\DC OSD\IMG_DC_ADJUST_6.bmp"
echo y | xcopy 1.bmp ".\mmi_res_240x240\camera\MMI_RES_DEFAULT\IMAG\DC OSD\IMG_DC_BIRGHTNESS_FOCUS.bmp"
echo y | xcopy 1.bmp ".\mmi_res_240x240\camera\MMI_RES_DEFAULT\IMAG\DC OSD\IMG_DC_BRIGHTNESS.bmp"
echo y | xcopy 1.bmp ".\mmi_res_240x240\camera\MMI_RES_DEFAULT\IMAG\DC OSD\IMG_DC_BRIGHTNESS_ADJUST.bmp"
echo y | xcopy 1.bmp ".\mmi_res_240x240\camera\MMI_RES_DEFAULT\IMAG\DC OSD\IMG_DC_CONTRAST.bmp"
echo y | xcopy 1.bmp ".\mmi_res_240x240\camera\MMI_RES_DEFAULT\IMAG\DC OSD\IMG_DC_CONTRAST_ADJUST.bmp"
echo y | xcopy 1.bmp ".\mmi_res_240x240\camera\MMI_RES_DEFAULT\IMAG\DC OSD\IMG_DC_CONTRAST_FOCUS.bmp"
echo y | xcopy 1.bmp ".\mmi_res_240x240\camera\MMI_RES_DEFAULT\IMAG\DC OSD\IMG_DC_EC_ADJUST.bmp"
echo y | xcopy 1.bmp ".\mmi_res_240x240\camera\MMI_RES_DEFAULT\IMAG\DC OSD\IMG_DC_EFFECT.bmp"
echo y | xcopy 1.bmp ".\mmi_res_240x240\camera\MMI_RES_DEFAULT\IMAG\DC OSD\IMG_DC_EFFECT_FOCUS.bmp"
echo y | xcopy 1.bmp ".\mmi_res_240x240\camera\MMI_RES_DEFAULT\IMAG\DC OSD\IMG_DC_ENVIRONMENT.bmp"
echo y | xcopy 1.bmp ".\mmi_res_240x240\camera\MMI_RES_DEFAULT\IMAG\DC OSD\IMG_DC_ENVIRONMENT_FOCUS.bmp"
echo y | xcopy 1.bmp ".\mmi_res_240x240\camera\MMI_RES_DEFAULT\IMAG\DC OSD\IMG_DC_EXPOSAL_COMPENSATE.bmp"
echo y | xcopy 1.bmp ".\mmi_res_240x240\camera\MMI_RES_DEFAULT\IMAG\DC OSD\IMG_DC_EXPOSAL_COMPENSATE_FOCUS.bmp"
echo y | xcopy 1.bmp ".\mmi_res_240x240\camera\MMI_RES_DEFAULT\IMAG\DC OSD\IMG_DC_LEFT_ARROW.bmp"
echo y | xcopy 1.bmp ".\mmi_res_240x240\camera\MMI_RES_DEFAULT\IMAG\DC OSD\IMG_DC_MULTISHOT.bmp"
echo y | xcopy 1.bmp ".\mmi_res_240x240\camera\MMI_RES_DEFAULT\IMAG\DC OSD\IMG_DC_MULTISHOT_FOCUS.bmp"
echo y | xcopy 1.bmp ".\mmi_res_240x240\camera\MMI_RES_DEFAULT\IMAG\DC OSD\IMG_DC_MULTISHOT_TIP.bmp"
echo y | xcopy 1.bmp ".\mmi_res_240x240\camera\MMI_RES_DEFAULT\IMAG\DC OSD\IMG_DC_PANORAMA_TIP.bmp"
echo y | xcopy 1.bmp ".\mmi_res_240x240\camera\MMI_RES_DEFAULT\IMAG\DC OSD\IMG_DC_PHOTO_MODE.bmp"
echo y | xcopy 1.bmp ".\mmi_res_240x240\camera\MMI_RES_DEFAULT\IMAG\DC OSD\IMG_DC_PHOTO_MODE_FOCUS.bmp"
echo y | xcopy 1.bmp ".\mmi_res_240x240\camera\MMI_RES_DEFAULT\IMAG\DC OSD\IMG_DC_RIGHT_ARROW.bmp"
echo y | xcopy 1.bmp ".\mmi_res_240x240\camera\MMI_RES_DEFAULT\IMAG\DC OSD\IMG_DC_SELF_DELAY.bmp"
echo y | xcopy 1.bmp ".\mmi_res_240x240\camera\MMI_RES_DEFAULT\IMAG\DC OSD\IMG_DC_SELF_DELAY_FOCUS.bmp"
echo y | xcopy 1.bmp ".\mmi_res_240x240\camera\MMI_RES_DEFAULT\IMAG\DC OSD\IMG_DC_SIZE.bmp"
echo y | xcopy 1.bmp ".\mmi_res_240x240\camera\MMI_RES_DEFAULT\IMAG\DC OSD\IMG_DC_SIZE_FOCUS.bmp"
echo y | xcopy 1.bmp ".\mmi_res_240x240\camera\MMI_RES_DEFAULT\IMAG\DC OSD\IMG_DC_WHITE_BALANCE.bmp"
echo y | xcopy 1.bmp ".\mmi_res_240x240\camera\MMI_RES_DEFAULT\IMAG\DC OSD\IMG_DC_WHITE_BALANCE_FOCUS.bmp"
echo y | xcopy 1.bmp ".\mmi_res_240x240\camera\MMI_RES_DEFAULT\IMAG\DC OSD\IMG_DC_TITLE_BG.bmp"
echo y | xcopy 1.bmp ".\mmi_res_240x240\camera\MMI_RES_DEFAULT\IMAG\DC OSD\IMG_DC_UP_ARROW.bmp"
echo y | xcopy 1.bmp ".\mmi_res_240x240\camera\MMI_RES_DEFAULT\IMAG\DC OSD\IMG_DC_DOWN_ARROW.bmp"
echo y | xcopy 1.png .\mmi_res_240x240\multim\MMI_RES_DEFAULT\IMAG\cc\IAMGE_CALL_DEFAULT_PHOTO.png
echo y | xcopy 1.bmp .\mmi_res_240x240\cc\MMI_RES_DEFAULT\IMAG\cc\IMAGE_CALL_DIAL.bmp
echo y | xcopy 1.png .\mmi_res_240x240\cc\MMI_RES_DEFAULT\IMAG\cc\IMG_CC_ANSWER_ICON.png
echo y | xcopy 1.png .\mmi_res_240x240\cc\MMI_RES_DEFAULT\IMAG\cc\IMG_CC_HANGUP_ICON.png
echo y | xcopy 1.png .\mmi_res_240x240\cc\MMI_RES_DEFAULT\IMAG\cc\IMAGE_CC_COMMON_BG_PDA.png
echo y | xcopy 1.png .\mmi_res_240x240\cc\MMI_RES_DEFAULT\IMAG\cc\IMAGE_CC_SINGLE_HANGUP_PDA.png
echo y | xcopy 1.png .\mmi_res_240x240\cc\MMI_RES_DEFAULT\IMAG\cc\IMG_CC_RECORD_ICON.png
echo y | xcopy 1.png .\mmi_res_240x240\cc\MMI_RES_DEFAULT\IMAG\cc\IMG_CC_HANDFREE_ICON.png
echo y | xcopy 1.png .\mmi_res_240x240\cc\MMI_RES_DEFAULT\IMAG\cc\IMG_CC_DIALPANEL_ICON.png
echo y | xcopy 1.png .\mmi_res_240x240\cc\MMI_RES_DEFAULT\IMAG\cc\IMG_CC_ADD_CALL_ICON.png
echo y | xcopy 1.png .\mmi_res_240x240\cc\MMI_RES_DEFAULT\IMAG\cc\IMG_CC_MERGE_CALLS_ICON.png
echo y | xcopy 1.png .\mmi_res_240x240\cc\MMI_RES_DEFAULT\IMAG\cc\IMG_CC_MUTE_ICON.png
echo y | xcopy 1.png .\mmi_res_240x240\cc\MMI_RES_DEFAULT\IMAG\cc\IMG_CC_SILENCE_ICON.png
echo y | xcopy 1.png .\mmi_res_240x240\cc\MMI_RES_DEFAULT\IMAG\cc\IMG_CC_PB_ICON.png
echo y | xcopy 1.png .\mmi_res_240x240\cc\MMI_RES_DEFAULT\IMAG\cc\IMG_CC_HOLD_ICON.png
echo y | xcopy 1.png .\mmi_res_240x240\cc\MMI_RES_DEFAULT\IMAG\cc\IMG_CC_RETRIEVE_CALLS_ICON.png
echo y | xcopy 1.png .\mmi_res_240x240\cc\MMI_RES_DEFAULT\IMAG\cc\IMG_CC_SWAP_CALLS_ICON.png
echo y | xcopy 1.png .\mmi_res_240x240\cc\MMI_RES_DEFAULT\IMAG\cc\IMG_CC_RECORD_GRAY_ICON.png
echo y | xcopy 1.png .\mmi_res_240x240\cc\MMI_RES_DEFAULT\IMAG\cc\IMG_CC_HANDFREE_GRAY_ICON.png
echo y | xcopy 1.png .\mmi_res_240x240\cc\MMI_RES_DEFAULT\IMAG\cc\IMG_CC_HANGUP_GRAY_ICON.png
echo y | xcopy 1.png .\mmi_res_240x240\cc\MMI_RES_DEFAULT\IMAG\cc\IMG_CC_DIALPANEL_GRAY_ICON.png
echo y | xcopy 1.png .\mmi_res_240x240\cc\MMI_RES_DEFAULT\IMAG\cc\IMG_CC_ANSWER_GRAY_ICON.png
echo y | xcopy 1.png .\mmi_res_240x240\cc\MMI_RES_DEFAULT\IMAG\cc\IMG_CC_ADD_CALL_GRAY_ICON.png
echo y | xcopy 1.png .\mmi_res_240x240\cc\MMI_RES_DEFAULT\IMAG\cc\IMG_CC_MERGE_CALLS_GRAY_ICON.png
echo y | xcopy 1.png .\mmi_res_240x240\cc\MMI_RES_DEFAULT\IMAG\cc\IMG_CC_MUTE_GRAY_ICON.png
echo y | xcopy 1.png .\mmi_res_240x240\cc\MMI_RES_DEFAULT\IMAG\cc\IMG_CC_SILENCE_GRAY_ICON.png
echo y | xcopy 1.png .\mmi_res_240x240\cc\MMI_RES_DEFAULT\IMAG\cc\IMG_CC_PB_GRAY_ICON.png
echo y | xcopy 1.png .\mmi_res_240x240\cc\MMI_RES_DEFAULT\IMAG\cc\IMG_CC_HOLD_GRAY_ICON.png
echo y | xcopy 1.png .\mmi_res_240x240\cc\MMI_RES_DEFAULT\IMAG\cc\IMG_CC_RETRIEVE_CALLS_GRAY_ICON.png
echo y | xcopy 1.png .\mmi_res_240x240\cc\MMI_RES_DEFAULT\IMAG\cc\IMG_CC_SWAP_CALLS_GRAY_ICON.png
echo y | xcopy 1.png .\mmi_res_240x240\cc\MMI_RES_DEFAULT\IMAG\callog\IMAGE_SETTINGS_SIM1_ICON.png
echo y | xcopy 1.png .\mmi_res_240x240\cc\MMI_RES_DEFAULT\IMAG\callog\IMAGE_SETTINGS_SIM2_ICON.png
echo y | xcopy 1.png .\mmi_res_240x240\cc\MMI_RES_DEFAULT\IMAG\callog\IMAGE_PREFERRED_SIM1.png
echo y | xcopy 1.png .\mmi_res_240x240\cc\MMI_RES_DEFAULT\IMAG\callog\IMAGE_PREFERRED_SIM2.png
echo y | xcopy 1.png .\mmi_res_240x240\cc\MMI_RES_DEFAULT\IMAG\cc\IMAGE_CC_BG.png
echo y | xcopy 1.png .\mmi_res_240x240\cc\MMI_RES_DEFAULT\IMAG\cc\IMAGE_CALLUI_BT_BLACK.png
echo y | xcopy 1.png .\mmi_res_240x240\cc\MMI_RES_DEFAULT\IMAG\cc\IMAGE_CALLUI_BT.png
echo y | xcopy 1.png .\mmi_res_240x240\cc\MMI_RES_DEFAULT\IMAG\cc\IMAGE_CALLUI_BT_FOCUSED_ON_RED.png
echo y | xcopy 1.png .\mmi_res_240x240\cc\MMI_RES_DEFAULT\IMAG\cc\IMAGE_CALLUI_BT_UNFOCUSED_ON_RED.png
echo y | xcopy 1.png .\mmi_res_240x240\cc\MMI_RES_DEFAULT\IMAG\cc\IMAGE_CALLUI_BT_FOCUSED_ON_RED2.png
echo y | xcopy 1.png .\mmi_res_240x240\cc\MMI_RES_DEFAULT\IMAG\cc\IMAGE_CALLUI_BT_FOCUSED_ON_RED.png
echo y | xcopy 1.png .\mmi_res_240x240\cc\MMI_RES_DEFAULT\IMAG\cc\IMAGE_CALLUI_BT_UNFOCUSED_ON_RED2.png
echo y | xcopy 1.png .\mmi_res_240x240\cc\MMI_RES_DEFAULT\IMAG\cc\IMAGE_CALLUI_BT_UNFOCUSED_ON_RED.png
echo y | xcopy 1.png .\mmi_res_240x240\cc\MMI_RES_DEFAULT\IMAG\cc\IMAGE_CALLUI_MUTE_BLACK.png
echo y | xcopy 1.png .\mmi_res_240x240\cc\MMI_RES_DEFAULT\IMAG\cc\IMAGE_CALLUI_MUTE.png
echo y | xcopy 1.png .\mmi_res_240x240\cc\MMI_RES_DEFAULT\IMAG\cc\IMAGE_CALLUI_MUTE_UNFOCUSED_ON_RED.png
echo y | xcopy 1.png .\mmi_res_240x240\cc\MMI_RES_DEFAULT\IMAG\cc\IMAGE_CALLUI_MUTE_UNFOCUSED_ON_RED2.png
echo y | xcopy 1.png .\mmi_res_240x240\cc\MMI_RES_DEFAULT\IMAG\cc\IMAGE_CALLUI_MUTE_UNFOCUSED_ON_RED.png
echo y | xcopy 1.png .\mmi_res_240x240\cc\MMI_RES_DEFAULT\IMAG\cc\IMAGE_CALLUI_MUTE_FOCUSED_ON_RED.png
echo y | xcopy 1.png .\mmi_res_240x240\cc\MMI_RES_DEFAULT\IMAG\cc\IMAGE_CALLUI_MUTE_FOCUSED_ON_RED2.png
echo y | xcopy 1.png .\mmi_res_240x240\cc\MMI_RES_DEFAULT\IMAG\cc\IMAGE_CALLUI_MUTE_FOCUSED_ON_RED.png
echo y | xcopy 1.png .\mmi_res_240x240\cc\MMI_RES_DEFAULT\IMAG\cc\IMAGE_CALLUI_LOUDSPEAKER_BLACK.png
echo y | xcopy 1.png .\mmi_res_240x240\cc\MMI_RES_DEFAULT\IMAG\cc\IMAGE_CALLUI_LOUDSPEAKER.png
echo y | xcopy 1.png .\mmi_res_240x240\cc\MMI_RES_DEFAULT\IMAG\cc\IMAGE_CALLUI_LOUDSPEAKER_UNFOCUSED_ON_RED.png
echo y | xcopy 1.png .\mmi_res_240x240\cc\MMI_RES_DEFAULT\IMAG\cc\IMAGE_CALLUI_LOUDSPEAKER_UNFOCUSED_ON_RED2.png
echo y | xcopy 1.png .\mmi_res_240x240\cc\MMI_RES_DEFAULT\IMAG\cc\IMAGE_CALLUI_LOUDSPEAKER_UNFOCUSED_ON_RED.png
echo y | xcopy 1.png .\mmi_res_240x240\cc\MMI_RES_DEFAULT\IMAG\cc\IMAGE_CALLUI_LOUDSPEAKER_FOCUSED_ON_RED.png
echo y | xcopy 1.png .\mmi_res_240x240\cc\MMI_RES_DEFAULT\IMAG\cc\IMAGE_CALLUI_LOUDSPEAKER_FOCUSED_ON_RED2.png
echo y | xcopy 1.png .\mmi_res_240x240\cc\MMI_RES_DEFAULT\IMAG\cc\IMAGE_CALLUI_LOUDSPEAKER_FOCUSED_ON_RED.png
echo y | xcopy 1.png .\mmi_res_240x240\cc\MMI_RES_DEFAULT\IMAG\cc\IMAGE_CALLUI_EMERGENCYCALL.png
echo y | xcopy 1.png .\mmi_res_240x240\cc\MMI_RES_DEFAULT\IMAG\cc\IMAGE_CALLUI_AVATAR_UNKNOWN.png

echo y | xcopy 1.png .\mmi_res_240x240\cc\MMI_RES_DEFAULT\IMAG\cc\IMAGE_CALLUI_AVATAR_MASK.png
echo y | xcopy 1.png .\mmi_res_240x240\cc\MMI_RES_DEFAULT\IMAG\cc\IMAGE_CALLUI_MESSAGE.png
echo y | xcopy 1.png .\mmi_res_240x240\cc\MMI_RES_DEFAULT\IMAG\cc\IMAGE_CALLUI_SILENT.png
echo y | xcopy 1.png .\mmi_res_240x240\cc\MMI_RES_DEFAULT\IMAG\cc\IMAGE_CALLUI_AVATAR_INITIALS.png
echo y | xcopy 1.png .\mmi_res_240x240\cc\MMI_RES_DEFAULT\IMAG\cc\IMAGE_CALLUI_RECORDING_INDICATOR.png
echo y | xcopy 1.png .\mmi_res_240x240\cc\MMI_RES_DEFAULT\IMAG\cc\IMAGE_CALLUI_RECORDING_1_BLUE.png
echo y | xcopy 1.png .\mmi_res_240x240\cc\MMI_RES_DEFAULT\IMAG\cc\IMAGE_CALLUI_RECORDING_2_BLUE.png
echo y | xcopy 1.png .\mmi_res_240x240\cc\MMI_RES_DEFAULT\IMAG\cc\IMAGE_CALLUI_RECORDING_3_BLUE.png
echo y | xcopy 1.png .\mmi_res_240x240\cc\MMI_RES_DEFAULT\IMAG\cc\IMAGE_CALLUI_RECORDING_4_BLUE.png
echo y | xcopy 1.png .\mmi_res_240x240\cc\MMI_RES_DEFAULT\IMAG\cc\IMAGE_CALLUI_RECORDING_5_BLUE.png
echo y | xcopy 1.png .\mmi_res_240x240\cc\MMI_RES_DEFAULT\IMAG\cc\IMAGE_CALLUI_RECORDING_6_BLUE.png
echo y | xcopy 1.png .\mmi_res_240x240\cc\MMI_RES_DEFAULT\IMAG\cc\IMAGE_CALLUI_RECORDING_1_BLUE.png
echo y | xcopy 1.png .\mmi_res_240x240\cc\MMI_RES_DEFAULT\IMAG\cc\IMAGE_CALLUI_RECORDING_2_BLUE.png
echo y | xcopy 1.png .\mmi_res_240x240\cc\MMI_RES_DEFAULT\IMAG\cc\IMAGE_CALLUI_RECORDING_3_BLUE.png
echo y | xcopy 1.png .\mmi_res_240x240\cc\MMI_RES_DEFAULT\IMAG\cc\IMAGE_CALLUI_RECORDING_4_BLUE.png
echo y | xcopy 1.png .\mmi_res_240x240\cc\MMI_RES_DEFAULT\IMAG\cc\IMAGE_CALLUI_RECORDING_5_BLUE.png
echo y | xcopy 1.png .\mmi_res_240x240\cc\MMI_RES_DEFAULT\IMAG\cc\IMAGE_CALLUI_RECORDING_6_BLUE.png
echo y | xcopy 1.png .\mmi_res_240x240\cc\MMI_RES_DEFAULT\IMAG\cc\IMAGE_CALLUI_RECORDING_INDICATOR_SMALL_RED.png
echo y | xcopy 1.png .\mmi_res_240x240\cc\MMI_RES_DEFAULT\IMAG\cc\IMAGE_CALLUI_RECORDING_INDICATOR_SMALL_RED.png
echo y | xcopy 1.png .\mmi_res_240x240\cc\MMI_RES_DEFAULT\IMAG\cc\IMAGE_CALLUI_SWAP.png
echo y | xcopy 1.png .\mmi_res_240x240\cc\MMI_RES_DEFAULT\IMAG\cc\IMAGE_CALLUI_ONHOLD_LARGE.png
echo y | xcopy 1.png .\mmi_res_240x240\cc\MMI_RES_DEFAULT\IMAG\cc\IMAGE_CALLUI_ONHOLD_SMALL.png
echo y | xcopy 1.png .\mmi_res_240x240\cc\MMI_RES_DEFAULT\IMAG\cc\IMAGE_CALLUI_VOICEMAIL_AVATAR_LARGE.png
echo y | xcopy 1.png .\mmi_res_240x240\cc\MMI_RES_DEFAULT\IMAG\cc\IMAGE_CALLUI_ONGOING_CALL.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon_Black\IMAGE_IDLE_TITLE_ICON_NEW_PUSH_ICON.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon_Black\wifi\IMAGE_IDLE_TITLE_ICON_WIFI1.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon_Black\wifi\IMAGE_IDLE_TITLE_ICON_WIFI2.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon_Black\wifi\IMAGE_IDLE_TITLE_ICON_WIFI3.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon\IMAGE_IDLE_TITLE_ICON_NEW_PUSH_ICON.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon\wifi\IMAGE_IDLE_TITLE_ICON_WIFI1.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon\wifi\IMAGE_IDLE_TITLE_ICON_WIFI2.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon\wifi\IMAGE_IDLE_TITLE_ICON_WIFI3.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Common\IMAGE_COMMON_TIPS_BG2.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Common\IMAGE_COMMON_TIPS_BG.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Common\IMAGE_COMMON_MOVIE_SD_ICON.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Common\IMAGE_COMMON_MOVIE_UDISK_ICON.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Common\IMAGE_COMMON_MUSIC_SD_ICON.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Common\IMAGE_COMMON_MUSIC_UDISK_ICON.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Common\IMAGE_COMMON_PIC_UDISK_ICON.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Common\IMAGE_COMMON_VCF_ICON.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Common\IMAGE_COMMON_TXT_ICON.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\List\IMAGE_CONTROL_LIST_ARROW_DEFAULT.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Common\IMAGE_COMMON_SELECTED_BAR.png
echo y | xcopy 1.bmp .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Common\IMAGE_COMMON_COUNT_LBTN_UN.bmp
echo y | xcopy 1.bmp .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Common\IMAGE_COMMON_COUNT_RBTN_UN.bmp
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Statusbar\IMAGE_CONTROL_STATUSBAR_BG.png
echo y | xcopy 1.bmp .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Title\Common\IMAGE_COMMON_TITLE_BAR.bmp
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Title\Common\IMAGE_TITLE_BAR.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Title\IMAGE_TITLE_BAR2.png
echo y | xcopy 1.bmp .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\volume_setting\IMAGE_ADJUST_VOL_BG.bmp
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\volume_setting\IMAGE_ADJUST_VOL_BG.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\volume_setting\IMAGE_ADJUST_VOL_BLOCK_SINGLE_BG.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\volume_setting\IMAGE_ADJUST_VOL_BLOCK_FG.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\volume_setting\IMAGE_COMMON_PIC_ICON.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\volume_setting\IMAGE_COMMON_PIC_ERROR.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\List\IMAGE_ICONLIST_CHECK_SELECTED_ICON.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Common\IMAGE_COMMON_POP_MENU_LEFT.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Common\IMAGE_COMMON_POP_MENU_RIGHT.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Common\IMAGE_COMMON_POP_MENU_LEFT_GRAY.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Common\IMAGE_COMMON_POP_MENU_RIGHT_GRAY.png

echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Dropdownlist\IMAGE_DROPDOWNLIST_ARROW_PR.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Dropdownlist\IMAGE_DROPDOWNLIST_ARROW_UN.png
echo y | xcopy 1.bmp .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon_Black\IMAGE_IDLE_ICON_NO_SIM.bmp
echo y | xcopy 1.bmp .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon_Black\IMAGE_IDLE_ICON_LINE1.bmp
echo y | xcopy 1.bmp .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon_Black\IMAGE_IDLE_ICON_LINE2.bmp
echo y | xcopy 1.bmp .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon_Black\IMAGE_IDLE_ICON_NEW_VM.bmp
echo y | xcopy 1.bmp .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon_Black\IMAGE_IDLE_TITLE_ICON_BATTERY1.bmp
echo y | xcopy 1.bmp .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon_Black\IMAGE_IDLE_TITLE_ICON_BATTERY2.bmp
echo y | xcopy 1.bmp .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon_Black\IMAGE_IDLE_TITLE_ICON_BATTERY3.bmp
echo y | xcopy 1.bmp .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon_Black\IMAGE_IDLE_TITLE_ICON_BATTERY4.bmp
echo y | xcopy 1.bmp .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon_Black\IMAGE_IDLE_TITLE_ICON_BATTERY5.bmp
echo y | xcopy 1.bmp .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon_Black\IMAGE_IDLE_TITLE_ICON_BATTERY6.bmp
echo y | xcopy 1.bmp .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon_Black\IMAGE_IDLE_TITLE_ICON_CLOCK.bmp
echo y | xcopy 1.bmp .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon_Black\IMAGE_IDLE_TITLE_ICON_EARPHONE.bmp
echo y | xcopy 1.bmp .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon_Black\IMAGE_IDLE_TITLE_ICON_FLYMODE.bmp
echo y | xcopy 1.bmp .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon_Black\IMAGE_IDLE_TITLE_ICON_FORWARD.bmp
echo y | xcopy 1.bmp .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon_Black\IMAGE_IDLE_TITLE_ICON_FULL_MESSAGE.bmp
echo y | xcopy 1.bmp .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon_Black\IMAGE_IDLE_TITLE_ICON_LOW_RING.bmp
echo y | xcopy 1.bmp .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon_Black\IMAGE_IDLE_TITLE_ICON_MESSAGE.bmp
echo y | xcopy 1.bmp .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon_Black\IMAGE_IDLE_TITLE_ICON_CALLING.bmp
echo y | xcopy 1.bmp .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon_Black\IMAGE_IDLE_TITLE_ICON_UNCIPHERING_CALLING.bmp
echo y | xcopy 1.bmp .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon_Black\IMAGE_IDLE_TITLE_ICON_MISSED_CALL.bmp
echo y | xcopy 1.bmp .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon_Black\IMAGE_IDLE_TITLE_ICON_MMS.bmp
echo y | xcopy 1.bmp .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon_Black\IMAGE_IDLE_TITLE_ICON_MMSSEND.bmp
echo y | xcopy 1.bmp .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon_Black\IMAGE_IDLE_TITLE_ICON_OTA.bmp
echo y | xcopy 1.bmp .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon_Black\IMAGE_IDLE_TITLE_ICON_RING_VIBRA.bmp
echo y | xcopy 1.bmp .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon_Black\IMAGE_IDLE_TITLE_ICON_SILENT.bmp
echo y | xcopy 1.bmp .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon_Black\IMAGE_IDLE_TITLE_ICON_VIBRATION.bmp
echo y | xcopy 1.bmp .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon\StatusbarIcon_Black\IMAGE_IDLE_TITLE_ICON_MMS_DUA.bmp
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon_Black\signal_gprs\single\IMAGE_IDLE_TITLE_ICON_SIGNAL1_AND_GPRS.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon_Black\signal_gprs\single\IMAGE_IDLE_TITLE_ICON_SIGNAL2_AND_GPRS.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon_Black\signal_gprs\single\IMAGE_IDLE_TITLE_ICON_SIGNAL3_AND_GPRS.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon_Black\signal_gprs\single\IMAGE_IDLE_TITLE_ICON_SIGNAL4_AND_GPRS.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon_Black\signal_gprs\single\IMAGE_IDLE_TITLE_ICON_SIGNAL5_AND_GPRS.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon_Black\signal_gprs\single\IMAGE_IDLE_TITLE_ICON_SIGNAL6_AND_GPRS.png
echo y | xcopy 1.bmp .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon_Black\Signal_td\IMAGE_IDLE_TITLE_ICON_SIGNAL1_AND_T.bmp
echo y | xcopy 1.bmp .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon_Black\Signal_td\IMAGE_IDLE_TITLE_ICON_SIGNAL2_AND_T.bmp
echo y | xcopy 1.bmp .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon_Black\Signal_td\IMAGE_IDLE_TITLE_ICON_SIGNAL3_AND_T.bmp
echo y | xcopy 1.bmp .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon_Black\Signal_td\IMAGE_IDLE_TITLE_ICON_SIGNAL4_AND_T.bmp
echo y | xcopy 1.bmp .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon_Black\Signal_td\IMAGE_IDLE_TITLE_ICON_SIGNAL5_AND_T.bmp
echo y | xcopy 1.bmp .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon_Black\Signal_td\IMAGE_IDLE_TITLE_ICON_SIGNAL6_AND_T.bmp
echo y | xcopy 1.bmp .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon_Black\Signal_w\IMAGE_IDLE_TITLE_ICON_SIGNAL1_AND_W.bmp
echo y | xcopy 1.bmp .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon_Black\Signal_w\IMAGE_IDLE_TITLE_ICON_SIGNAL2_AND_W.bmp
echo y | xcopy 1.bmp .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon_Black\Signal_w\IMAGE_IDLE_TITLE_ICON_SIGNAL3_AND_W.bmp
echo y | xcopy 1.bmp .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon_Black\Signal_w\IMAGE_IDLE_TITLE_ICON_SIGNAL4_AND_W.bmp
echo y | xcopy 1.bmp .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon_Black\Signal_w\IMAGE_IDLE_TITLE_ICON_SIGNAL5_AND_W.bmp
echo y | xcopy 1.bmp .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon_Black\Signal_w\IMAGE_IDLE_TITLE_ICON_SIGNAL6_AND_W.bmp
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon\IMAGE_IDLE_ICON_LINE1.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon\IMAGE_IDLE_ICON_NEW_VM.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon_Black\battery_syle1\IMAGE_IDLE_TITLE_ICON_BATTERY1.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon_Black\battery_syle1\IMAGE_IDLE_TITLE_ICON_BATTERY2.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon_Black\battery_syle1\IMAGE_IDLE_TITLE_ICON_BATTERY3.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon_Black\battery_syle1\IMAGE_IDLE_TITLE_ICON_BATTERY4.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon_Black\battery_syle1\IMAGE_IDLE_TITLE_ICON_BATTERY5.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon_Black\battery_syle1\IMAGE_IDLE_TITLE_ICON_BATTERY6.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon_Black\battery_syle2\IMAGE_IDLE_TITLE_ICON_BATTERY1.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon_Black\battery_syle2\IMAGE_IDLE_TITLE_ICON_BATTERY2.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon_Black\battery_syle2\IMAGE_IDLE_TITLE_ICON_BATTERY3.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon_Black\battery_syle2\IMAGE_IDLE_TITLE_ICON_BATTERY4.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon_Black\battery_syle2\IMAGE_IDLE_TITLE_ICON_BATTERY5.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon_Black\battery_syle2\IMAGE_IDLE_TITLE_ICON_BATTERY6.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon_Black\battery\IMAGE_IDLE_TITLE_ICON_BATTERY1.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon_Black\battery\IMAGE_IDLE_TITLE_ICON_BATTERY2.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon_Black\battery\IMAGE_IDLE_TITLE_ICON_BATTERY3.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon_Black\battery\IMAGE_IDLE_TITLE_ICON_BATTERY4.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon_Black\battery\IMAGE_IDLE_TITLE_ICON_BATTERY5.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon_Black\battery\IMAGE_IDLE_TITLE_ICON_BATTERY6.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon_Black\IMAGE_IDLE_TITLE_ICON_CLOCK.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon_Black\IMAGE_IDLE_TITLE_ICON_EARPHONE.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon_Black\IMAGE_IDLE_TITLE_ICON_FLYMODE.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon_Black\IMAGE_IDLE_TITLE_ICON_FULL_MESSAGE.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon_Black\IMAGE_IDLE_TITLE_ICON_LOW_RING.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon_Black\IMAGE_IDLE_TITLE_ICON_MESSAGE.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon_Black\IMAGE_IDLE_TITLE_ICON_MESSAGE_SEND.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon_Black\IMAGE_IDLE_TITLE_ICON_CALLING.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon_Black\IMAGE_IDLE_TITLE_ICON_UNCIPHERING_CALLING.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon_Black\IMAGE_IDLE_TITLE_ICON_MISSED_CAL.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon_Black\IMAGE_IDLE_TITLE_ICON_MMS.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon_Black\IMAGE_IDLE_TITLE_ICON_MMSSEND.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon_Black\IMAGE_IDLE_TITLE_ICON_OTA.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon_Black\IMAGE_IDLE_TITLE_ICON_RING_VIBRA.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon_Black\IMAGE_IDLE_TITLE_ICON_SILENT.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon_Black\IMAGE_IDLE_TITLE_ICON_VIBRATION.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon_Black\IMAGE_IDLE_ICON_HDCL.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon_Black\IMAGE_IDLE_ICON_HDCL_AMRWB.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon_Black\IMAGE_IDLE_TITLE_ICON_MMS_DUA.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon_Black\Signal_td\IMAGE_IDLE_TITLE_ICON_SIGNAL1_AND_T.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon_Black\Signal_td\IMAGE_IDLE_TITLE_ICON_SIGNAL2_AND_T.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon_Black\Signal_td\IMAGE_IDLE_TITLE_ICON_SIGNAL3_AND_T.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon_Black\Signal_td\IMAGE_IDLE_TITLE_ICON_SIGNAL4_AND_T.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon_Black\Signal_td\IMAGE_IDLE_TITLE_ICON_SIGNAL5_AND_T.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon_Black\Signal_td\IMAGE_IDLE_TITLE_ICON_SIGNAL6_AND_T.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon_Black\Signal_w\IMAGE_IDLE_TITLE_ICON_SIGNAL1_AND_W.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon_Black\Signal_w\IMAGE_IDLE_TITLE_ICON_SIGNAL2_AND_W.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon_Black\Signal_w\IMAGE_IDLE_TITLE_ICON_SIGNAL3_AND_W.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon_Black\Signal_w\IMAGE_IDLE_TITLE_ICON_SIGNAL4_AND_W.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon_Black\Signal_w\IMAGE_IDLE_TITLE_ICON_SIGNAL5_AND_W.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon_Black\Signal_w\IMAGE_IDLE_TITLE_ICON_SIGNAL6_AND_W.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon_Black\IMAGE_IDLE_MIDDLE_SOFTKEY_CMCC_ICON.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon_Black\IMAGE_IDLE_MIDDLE_SOFTKEY_ICON.png
echo y | xcopy 1.bmp .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon\IMAGE_IDLE_ICON_NO_SIM.bmp
echo y | xcopy 1.bmp .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon\IMAGE_IDLE_ICON_LINE1.bmp
echo y | xcopy 1.bmp .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon\IMAGE_IDLE_ICON_LINE2.bmp
echo y | xcopy 1.bmp .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon\IMAGE_IDLE_ICON_NEW_VM.bmp
echo y | xcopy 1.bmp .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon\IMAGE_IDLE_TITLE_ICON_BATTERY1.bmp
echo y | xcopy 1.bmp .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon\IMAGE_IDLE_TITLE_ICON_BATTERY2.bmp
echo y | xcopy 1.bmp .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon\IMAGE_IDLE_TITLE_ICON_BATTERY3.bmp
echo y | xcopy 1.bmp .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon\IMAGE_IDLE_TITLE_ICON_BATTERY4.bmp
echo y | xcopy 1.bmp .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon\IMAGE_IDLE_TITLE_ICON_BATTERY5.bmp
echo y | xcopy 1.bmp .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon\IMAGE_IDLE_TITLE_ICON_BATTERY6.bmp
echo y | xcopy 1.bmp .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon\IMAGE_IDLE_TITLE_ICON_CLOCK.bmp
echo y | xcopy 1.bmp .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon\IMAGE_IDLE_TITLE_ICON_EARPHONE.bmp
echo y | xcopy 1.bmp .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon\IMAGE_IDLE_TITLE_ICON_FLYMODE.bmp
echo y | xcopy 1.bmp .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon\IMAGE_IDLE_TITLE_ICON_FORWARD.bmp
echo y | xcopy 1.bmp .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon\IMAGE_IDLE_TITLE_ICON_FULL_MESSAGE.bmp
echo y | xcopy 1.bmp .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon\IMAGE_IDLE_TITLE_ICON_LOW_RING.bmp
echo y | xcopy 1.bmp .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon\IMAGE_IDLE_TITLE_ICON_MESSAGE.bmp
echo y | xcopy 1.bmp .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon\IMAGE_IDLE_TITLE_ICON_CALLING.bmp
echo y | xcopy 1.bmp .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon\IMAGE_IDLE_TITLE_ICON_UNCIPHERING_CALLING.bmp
echo y | xcopy 1.bmp .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon\IMAGE_IDLE_TITLE_ICON_MISSED_CALL.bmp
echo y | xcopy 1.bmp .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon\IMAGE_IDLE_TITLE_ICON_MMS.bmp
echo y | xcopy 1.bmp .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon\IMAGE_IDLE_TITLE_ICON_MMSSEND.bmp
echo y | xcopy 1.bmp .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon\IMAGE_IDLE_TITLE_ICON_OTA.bmp
echo y | xcopy 1.bmp .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon\IMAGE_IDLE_TITLE_ICON_RING_VIBRA.bmp
echo y | xcopy 1.bmp .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon\IMAGE_IDLE_TITLE_ICON_SILENT.bmp
echo y | xcopy 1.bmp .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon\IMAGE_IDLE_TITLE_ICON_VIBRATION.bmp
echo y | xcopy 1.bmp .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon\dualsim_idle_icon\IMAGE_IDLE_TITLE_ICON_MMS_DUA.bmp
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon\signal_gprs\single\IMAGE_IDLE_TITLE_ICON_SIGNAL1_AND_GPRS.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon\signal_gprs\single\IMAGE_IDLE_TITLE_ICON_SIGNAL2_AND_GPRS.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon\signal_gprs\single\IMAGE_IDLE_TITLE_ICON_SIGNAL3_AND_GPRS.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon\signal_gprs\single\IMAGE_IDLE_TITLE_ICON_SIGNAL4_AND_GPRS.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon\signal_gprs\single\IMAGE_IDLE_TITLE_ICON_SIGNAL5_AND_GPRS.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon\signal_gprs\single\IMAGE_IDLE_TITLE_ICON_SIGNAL6_AND_GPRS.png
echo y | xcopy 1.bmp .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon\Signal_td\IMAGE_IDLE_TITLE_ICON_SIGNAL1_AND_T.bmp
echo y | xcopy 1.bmp .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon\Signal_td\IMAGE_IDLE_TITLE_ICON_SIGNAL2_AND_T.bmp
echo y | xcopy 1.bmp .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon\Signal_td\IMAGE_IDLE_TITLE_ICON_SIGNAL3_AND_T.bmp
echo y | xcopy 1.bmp .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon\Signal_td\IMAGE_IDLE_TITLE_ICON_SIGNAL4_AND_T.bmp
echo y | xcopy 1.bmp .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon\Signal_td\IMAGE_IDLE_TITLE_ICON_SIGNAL5_AND_T.bmp
echo y | xcopy 1.bmp .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon\Signal_td\IMAGE_IDLE_TITLE_ICON_SIGNAL6_AND_T.bmp
echo y | xcopy 1.bmp .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon\Signal_w\IMAGE_IDLE_TITLE_ICON_SIGNAL1_AND_W.bmp
echo y | xcopy 1.bmp .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon\Signal_w\IMAGE_IDLE_TITLE_ICON_SIGNAL2_AND_W.bmp
echo y | xcopy 1.bmp .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon\Signal_w\IMAGE_IDLE_TITLE_ICON_SIGNAL3_AND_W.bmp
echo y | xcopy 1.bmp .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon\Signal_w\IMAGE_IDLE_TITLE_ICON_SIGNAL4_AND_W.bmp
echo y | xcopy 1.bmp .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon\Signal_w\IMAGE_IDLE_TITLE_ICON_SIGNAL5_AND_W.bmp
echo y | xcopy 1.bmp .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon\Signal_w\IMAGE_IDLE_TITLE_ICON_SIGNAL6_AND_W.bmp
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon\IMAGE_IDLE_ICON_LINE1.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon\IMAGE_IDLE_ICON_NEW_VM.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon\battery\IMAGE_IDLE_TITLE_ICON_BATTERY1.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon\battery\IMAGE_IDLE_TITLE_ICON_BATTERY2.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon\battery\IMAGE_IDLE_TITLE_ICON_BATTERY3.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon\battery\IMAGE_IDLE_TITLE_ICON_BATTERY4.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon\battery\IMAGE_IDLE_TITLE_ICON_BATTERY5.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon\battery\IMAGE_IDLE_TITLE_ICON_BATTERY6.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon\IMAGE_IDLE_TITLE_ICON_CLOCK.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon\IMAGE_IDLE_TITLE_ICON_EARPHONE.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon\IMAGE_IDLE_TITLE_ICON_FLYMODE.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon\IMAGE_IDLE_TITLE_ICON_FULL_MESSAGE.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon\IMAGE_IDLE_TITLE_ICON_LOW_RING.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon\IMAGE_IDLE_TITLE_ICON_MESSAGE.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon\IMAGE_IDLE_TITLE_ICON_MESSAGE_SEND.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon\IMAGE_IDLE_TITLE_ICON_CALLING.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon\IMAGE_IDLE_TITLE_ICON_UNCIPHERING_CALLING.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon\IMAGE_IDLE_TITLE_ICON_MISSED_CAL.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon\IMAGE_IDLE_TITLE_ICON_MMS.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon\IMAGE_IDLE_TITLE_ICON_MMSSEND.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon\IMAGE_IDLE_TITLE_ICON_OTA.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon\IMAGE_IDLE_TITLE_ICON_RING_VIBRA.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon\IMAGE_IDLE_TITLE_ICON_SILENT.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon\IMAGE_IDLE_TITLE_ICON_VIBRATION.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon\IMAGE_IDLE_ICON_HDCL.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon\IMAGE_IDLE_ICON_HDCL_AMRWB.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon\IMAGE_IDLE_TITLE_ICON_MMS_DUA.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon\Signal_td\IMAGE_IDLE_TITLE_ICON_SIGNAL1_AND_T.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon\Signal_td\IMAGE_IDLE_TITLE_ICON_SIGNAL2_AND_T.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon\Signal_td\IMAGE_IDLE_TITLE_ICON_SIGNAL3_AND_T.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon\Signal_td\IMAGE_IDLE_TITLE_ICON_SIGNAL4_AND_T.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon\Signal_td\IMAGE_IDLE_TITLE_ICON_SIGNAL5_AND_T.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon\Signal_td\IMAGE_IDLE_TITLE_ICON_SIGNAL6_AND_T.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon\Signal_w\IMAGE_IDLE_TITLE_ICON_SIGNAL1_AND_W.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon\Signal_w\IMAGE_IDLE_TITLE_ICON_SIGNAL2_AND_W.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon\Signal_w\IMAGE_IDLE_TITLE_ICON_SIGNAL3_AND_W.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon\Signal_w\IMAGE_IDLE_TITLE_ICON_SIGNAL4_AND_W.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon\Signal_w\IMAGE_IDLE_TITLE_ICON_SIGNAL5_AND_W.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon\Signal_w\IMAGE_IDLE_TITLE_ICON_SIGNAL6_AND_W.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon\IMAGE_IDLE_MIDDLE_SOFTKEY_CMCC_ICON.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon\IMAGE_IDLE_MIDDLE_SOFTKEY_ICON.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Idle_shortcut\IMAGE_IDLE_SHORTCUT_WRITE_MSG.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Idle_prompt\IMAGE_IDLE_PROMPT_PAUSE.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Idle_prompt\IMAGE_IDLE_PROMPT_PLAY.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Idle_prompt\IMAGE_IDLE_PROMPT_WORDS.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Idle_prompt\IMAGE_IDLE_PROMPT_COUNT_DOWN.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Idle_prompt\IMAGE_IDLE_PROMPT_PAUSE.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Idle_prompt\IMAGE_IDLE_PROMPT_PLAY.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Idle_prompt\IMAGE_IDLE_PROMPT_SCHEDULE.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\List\IMAGE_CONTROL_LIST_CHECK_PIN_ICON.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\List\IMAGE_CONTROL_LIST_RIGHT_ARROW.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Title\IMAGE_LIST_LEFT_ARROW_DISABLE.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Title\IMAGE_LIST_RIGHT_ARROW_DISABLE.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Title\IMAGE_LIST_TITLE_ARROW_LEFT_DOWN.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Title\IMAGE_LIST_TITLE_ARROW_LEFT_UP.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Title\IMAGE_LIST_TITLE_ARROW_RIGHT_UP.png
echo y | xcopy 1.bmp .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\List\IMAGE_CONTROL_LIST_MARKED_ICON.bmp
echo y | xcopy 1.bmp .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\List\IMAGE_CONTROL_LIST_RADIO_PRESSED.bmp
echo y | xcopy 1.bmp .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\List\IMAGE_CONTROL_LIST_RADIO_DEFAULT.bmp
echo y | xcopy 1.bmp .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\List\IMAGE_CONTROL_CHECK_SELECTED_ICON.bmp
echo y | xcopy 1.bmp .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\List\IMAGE_CONTROL_CHECK_UNSELECTED_ICON.bmp
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\List\IMAGE_CONTROL_LIST_MARKED_ICON.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\List\IMAGE_RADIOBUTTON_ON_BLUE.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\List\IMAGE_RADIOBUTTON_OFF_BLUE.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\List\IMAGE_CHECKBOX_ON.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\List\IMAGE_CHECKBOX_OFF.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\List\IMAGE_CONTROL_LIST_CHECK_DISABLED.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\List\IMAGE_CONTROL_LIST_CHECK_UNSELECTED_ICON_GRAY.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\List\IMAGE_AVATAR_CHECKBOX_ON.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\List\IMAGE_AVATAR_CHECKBOX_OFF.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\List\IMAGE_CONTROL_LIST_LEFT_SLIDE.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\List\IMAGE_CONTROL_LIST_RIGHT_SLIDE.png
echo y | xcopy 1.bmp .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\setlist\IMAGE_CONTROL_SETLIST_ARROW_LEFT_UP.bmp
echo y | xcopy 1.bmp .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\setlist\IMAGE_CONTROL_SETLIST_ARROW_RIGHT_UP.bmp
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\setlist\IMAGE_CONTROL_SETLIST_ARROW_LEFT_UP.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\setlist\IMAGE_CONTROL_SETLIST_ARROW_RIGHT_UP.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Mainmenu\Title\IMAGE_SLIDE_MAINMENU_TITLE_OFF.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Mainmenu\Title\IMAGE_SLIDE_MAINMENU_TITLE_ON.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Mainmenu\Title\IMAGE_SLIDE_MAINMENU_TITLE_BG.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Mainmenu\IMAGE_ANDROIDMENU_DELETE_ICON.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Mainmenu\IMAGE_MAINMENU_NUMICON.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Mainmenu_icon_large\IMAGE_MAINMENU_ICON_ITEM_TEXT_BG.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Secondmenu_icon\IMAGE_SECMENU_ICON_TOOL_IKEYBACKUP.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Prgbox\IMAGE_SCROLL_DOWN_ARROW.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Prgbox\IMAGE_SCROLL_DOWN_ARROW_FOCUS.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Prgbox\IMAGE_SCROLL_UP_ARROW.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Prgbox\IMAGE_SCROLL_UP_ARROW_FOCUS.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Prgbox\IMAGE_CONTROL_PROGRESS.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Prgbox\IMAGE_CONTROL_PROGRESS_BG.png
echo y | xcopy 1.bmp .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Prgbox\IMAGE_SCROLL_VER_BAR.bmp
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Prgbox\IMAGE_CONTROL_VER_BAR.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Prgbox\IMAGE_SCROLL_VER_GROOVE.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Prgbox\IMAGE_SCROLL_HOR_GROOVE.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Prgbox\IMAGE_SCROLL_LEFT_ARROW.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Prgbox\IMAGE_SCROLL_LEFT_ARROW_FOCUS.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Prgbox\IMAGE_SCROLL_RIGHT_ARROW.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Prgbox\IMAGE_SCROLL_RIGHT_ARROW_FOCUS.png
echo y | xcopy 1.bmp .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Prgbox\IMAGE_SCROLL_DOWN_ARROW_2.bmp
echo y | xcopy 1.bmp .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Prgbox\IMAGE_SCROLL_DOWN_ARROW_FOCUS_2.bmp
echo y | xcopy 1.bmp .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Prgbox\IMAGE_SCROLL_UP_ARROW_2.bmp
echo y | xcopy 1.bmp .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Prgbox\IMAGE_SCROLL_UP_ARROW_FOCUS_2.bmp
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Prgbox\IMAGE_CONTROL_VER_BAR.png
echo y | xcopy 1.bmp .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Prgbox\IMAGE_SCROLL_LEFT_ARROW_2.bmp
echo y | xcopy 1.bmp .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Prgbox\IMAGE_SCROLL_LEFT_ARROW_FOCUS_2.bmp
echo y | xcopy 1.bmp .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Prgbox\IMAGE_SCROLL_RIGHT_ARROW_2.bmp
echo y | xcopy 1.bmp .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Prgbox\IMAGE_SCROLL_RIGHT_ARROW_FOCUS_2.bmp
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Prgbox\IMAGE_CONTROL_THUMB.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Prgbox\IMAGE_SCROLL_VER_BG.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Pubwin\IMAGE_CONTROL_POPWIN_DOWNARROW.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Pubwin\PDA\IMAGE_PUBWIN_TOP_BG_PDA.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Pubwin\PDA\IMAGE_PUBWIN_BOTTOM_BG_PDA.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Pubwin\PDA\IMAGE_PUBWIN_BOTTOM_BG_WITHOUT_BUTTON_PDA.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Pubwin\PDA\IMAGE_PUBWIN_BUTTON_GRAY_PDA.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Pubwin\PDA\IMAGE_PUBWIN_BUTTON_PDA.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Pubwin\PDA\IMAGE_PUBWIN_BUTTON_HL_PDA.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Pubwin\PDA\IMAGE_PUBWIN_WAITING_BG_PDA_small.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Pubwin\PDA\IMAGE_PUBWIN_WAITING_BG_PDA.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Pubwin\PDA\IMAGE_CONTROL_POPWIN_WARNING.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Pubwin\PDA\IMAGE_CONTROL_POPWIN_SUCCESS.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Pubwin\PDA\IMAGE_CONTROL_POPWIN_QUERY.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Pubwin\PDA\IMAGE_CONTROL_POPWIN_FAIL.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Pubwin\PDA\IMAGE_CONTROL_POPWIN_NEWCALL.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Pubwin\PDA\IMAGE_CONTROL_POPWIN_NEWMSG.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Pubwin\PDA\IMAGE_CONTROL_POPWIN_WAIT.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Pubwin\PDA\IMAGE_PUBWIN_TEXT_BG_PDA.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Pubwin\BAR\IMAGE_PUBWIN_WARNING.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Pubwin\BAR\IMAGE_PUBWIN_SUCCESS.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Pubwin\BAR\IMAGE_PUBWIN_QUERY.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Pubwin\BAR\IMAGE_PUBWIN_FAIL.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Pubwin\BAR\IMAGE_PUBWIN_NEWCALL.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Pubwin\BAR\IMAGE_PUBWIN_NEWMSG.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Pubwin\BAR\IMAGE_PUBWIN_WAIT.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Pubwin\BAR\IMAGE_PUBWIN_BG_LIGHT.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Pubwin\BAR\IMAGE_PUBWIN_BG.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\setting\IMAGE_NUMBERINPUT_PIN.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Softkey\IMAGE_SOFTKEY_BG.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Softkey\IMAGE_SOFTKEY_BG_DOWN.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Softkey\IMAGE_MAINMENU_SOFTKEY_BG.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Softkey\IMAGE_SOFTKEY_BG_H_DOWN.png
echo y | xcopy 1.bmp .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Storage\IMAGE_STORAGE_PHONE_ICON.bmp
echo y | xcopy 1.bmp .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Storage\IMAGE_STORAGE_SIM_ICON.bmp
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Storage\IMAGE_STORAGE_PHONE_ICON.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Storage\IMAGE_STORAGE_SIM_ICON.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Tab\IMAGE_CONTROL_TAB_BG.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Tab\IMAGE_CONTROL_TAB_DEFAULT_FONT30.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Tab\IMAGE_CONTROL_TAB_DEFAULT.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Tab\IMAGE_TAB_SCROLL.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Tab\IMAGE_CONTROL_TAB_HIGHLIGHT_FONT30.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Tab\IMAGE_CONTROL_TAB_SEPARATED_FONT30.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Tab\IMAGE_CONTROL_TAB_HIGHLIGHT.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Tab\IMAGE_CONTROL_TAB_SEPARATED.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Tab\IMAGE_TAB_SELECT1.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Tab\IMAGE_TAB_SELECT3.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Tab\IMAGE_TAB_SELECT2.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\wap\IMAGE_BROWSER_BOOKMARK_LIST_ICON.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\charge\IMAGE_BATTERY_CAPACIT_BG.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\charge\IMAGE_BATTERY_CAPACIT_FG.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\key_lock\effect4\IMAGE_KL_EFFECT4_TIME_BG.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\key_lock\effect4\IMAGE_KL_EFFECT4_DIGIT0.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Bg\IMAGE_THEME_BG_LARGE.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Bg\IMAGE_THEME_BG_small.png

echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Bg\IMAGE_THEME_BG.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Secondmenu_icon\IMAGE_SECMENU_ICON_BROWSER.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Secondmenu_icon\IMAGE_SECMENU_ICON_CALL_LIST.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon_Black\line\IMAGE_IDLE_ICON_LINE2.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon_Black\forward\IMAGE_IDLE_TITLE_ICON_FORWARD.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon_Black\roam\IMAGE_IDLE_ROAM.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon_Black\signal_gprs\single\IMAGE_IDLE_TITLE_ICON_SIGNAL1_AND_GPRS.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon_Black\signal_gprs\single\IMAGE_IDLE_TITLE_ICON_SIGNAL2_AND_GPRS.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon_Black\signal_gprs\single\IMAGE_IDLE_TITLE_ICON_SIGNAL3_AND_GPRS.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon_Black\signal_gprs\single\IMAGE_IDLE_TITLE_ICON_SIGNAL4_AND_GPRS.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon_Black\signal_gprs\single\IMAGE_IDLE_TITLE_ICON_SIGNAL5_AND_GPRS.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon_Black\signal_gprs\single\IMAGE_IDLE_TITLE_ICON_SIGNAL6_AND_GPRS.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon_Black\signal_gprs\single\IMAGE_IDLE_TITLE_ICON_SIGNAL1_AND_GPRS.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon_Black\signal_gprs\single\IMAGE_IDLE_TITLE_ICON_SIGNAL2_AND_GPRS.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon_Black\signal_gprs\single\IMAGE_IDLE_TITLE_ICON_SIGNAL3_AND_GPRS.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon_Black\signal_gprs\single\IMAGE_IDLE_TITLE_ICON_SIGNAL4_AND_GPRS.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon_Black\signal_gprs\single\IMAGE_IDLE_TITLE_ICON_SIGNAL5_AND_GPRS.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon_Black\signal_gprs\single\IMAGE_IDLE_TITLE_ICON_SIGNAL6_AND_GPRS.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon_Black\no_sim\IMAGE_IDLE_ICON_NO_SIM.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon_Black\idle_prompt\IMAGE_IDLE_PROMPT_SIM.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon_Black\idle_prompt\IMAGE_IDLE_PROMPT_GRAY_SIM.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon_Black\idle_prompt\IMAGE_IDLE_PROMPT_NO_SIM.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon_Black\sim_image\IMAGE_SIM1.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon\line\IMAGE_IDLE_ICON_LINE2.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon\forward\IMAGE_IDLE_TITLE_ICON_FORWARD.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon\roam\IMAGE_IDLE_ROAM.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon\signal_gprs\single\IMAGE_IDLE_TITLE_ICON_SIGNAL1_AND_GPRS.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon\signal_gprs\single\IMAGE_IDLE_TITLE_ICON_SIGNAL2_AND_GPRS.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon\signal_gprs\single\IMAGE_IDLE_TITLE_ICON_SIGNAL3_AND_GPRS.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon\signal_gprs\single\IMAGE_IDLE_TITLE_ICON_SIGNAL4_AND_GPRS.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon\signal_gprs\single\IMAGE_IDLE_TITLE_ICON_SIGNAL5_AND_GPRS.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon\signal_gprs\single\IMAGE_IDLE_TITLE_ICON_SIGNAL6_AND_GPRS.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon\signal_gprs\single\IMAGE_IDLE_TITLE_ICON_SIGNAL1_AND_GPRS.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon\signal_gprs\single\IMAGE_IDLE_TITLE_ICON_SIGNAL2_AND_GPRS.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon\signal_gprs\single\IMAGE_IDLE_TITLE_ICON_SIGNAL3_AND_GPRS.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon\signal_gprs\single\IMAGE_IDLE_TITLE_ICON_SIGNAL4_AND_GPRS.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon\signal_gprs\single\IMAGE_IDLE_TITLE_ICON_SIGNAL5_AND_GPRS.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon\signal_gprs\single\IMAGE_IDLE_TITLE_ICON_SIGNAL6_AND_GPRS.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon\no_sim\IMAGE_IDLE_ICON_NO_SIM.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon\idle_prompt\IMAGE_IDLE_PROMPT_SIM.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon\idle_prompt\IMAGE_IDLE_PROMPT_GRAY_SIM.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon\idle_prompt\IMAGE_IDLE_PROMPT_NO_SIM.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon\sim_image\IMAGE_SIM1.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Optionsmenu_icon\IMAGE_COMMON_OPTMENU_ADD.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Optionsmenu_icon\IMAGE_COMMON_OPTMENU_SET.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Optionsmenu_icon\IMAGE_COMMON_OPTMENU_SEARCH.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Optionsmenu_icon\IMAGE_COMMON_OPTMENU_NOTIFY.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Optionsmenu_icon\IMAGE_COMMON_OPTMENU_SET_WALLPAPER.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\common\IMAGE_COMMON_PICVIEW_BUTTON.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Secondmenu_icon\IMAGE_SECMENU_ICON_JAVA_INSTALL.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\key_lock\effect2\stat_notify_email_generic.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\key_lock\effect2\stat_notify_missed_call.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon_Black\signal_w\primo_statusbar_VoLTE.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon_Black\signal_w\primo_statusbar_HD.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon_Black\signal_w\primo_callingview_volte.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon_Black\signal_w\primo_callingview_hd.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon\signal_w\primo_statusbar_VoLTE.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon\signal_w\primo_statusbar_HD.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon\signal_w\primo_callingview_volte.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon\signal_w\primo_callingview_hd.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Common\IMAGE_COMMON_BACK.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\List\IMAGE_MASK.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\List\IMAGE_LISTITEM_SHORTCUT_INDICATOR.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\List\IMAGE_LISTITEM_SHORTCUT_INDICATOR_LEFT.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\List\IMAGE_LISTITEM_SHORTCUT_INDICATOR_RIGHT.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\List\IMAGE_TOGGLE_ON.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\List\IMAGE_TOGGLE_OFF.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\List\IMAGE_AVATAR_CHECKBOX_ON_CHECK.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\List\IMAGE_CHECKBOX_ON_CHECK.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\List\IMAGE_CONTROL_TOGGLE_OFF.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\List\IMAGE_CONTROL_TOGGLE_ON.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\application_management\IMAGE_MY_APPLICATIONS_MYAPP.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\control_panel\IMAGE_CONTROL_PANEL_BT_OFF.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\control_panel\IMAGE_CONTROL_PANEL_BT_ON_RED.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\control_panel\IMAGE_CONTROL_PANEL_BT_RED.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\control_panel\IMAGE_CONTROL_PANEL_DATA_OFF.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\control_panel\IMAGE_CONTROL_PANEL_DATA_ON_RED.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\control_panel\IMAGE_CONTROL_PANEL_BT_OFF.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\control_panel\IMAGE_CONTROL_PANEL_DATA_OFF.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\control_panel\IMAGE_CONTROL_PANEL_BT_RED.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\control_panel\IMAGE_CONTROL_PANEL_BT_ON_RED.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\control_panel\IMAGE_CONTROL_PANEL_DATA_ON_RED.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\control_panel\IMAGE_CONTROL_PANEL_SETTINGS.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\control_panel\IMAGE_CONTROL_PANEL_SIM1.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\control_panel\IMAGE_CONTROL_PANEL_SIM2.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\control_panel\IMAGE_IDLE_SCREEN_SINGLE_SIM.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Idle_screen\IMAGE_IDLE_SCREEN_ALARM.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Idle_screen\IMAGE_IDLE_SCREEN_ALARM_ICON_LARGE.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Idle_screen\IMAGE_IDLE_SCREEN_BACKGROUND_OVERLAY.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Idle_screen\IMAGE_IDLE_SCREEN_CALENDAR.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Idle_screen\IMAGE_IDLE_SCREEN_CALL.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Idle_screen\IMAGE_IDLE_SCREEN_CALL_BACK.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Idle_screen\IMAGE_IDLE_SCREEN_CAL_ICON_LARGE.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Idle_screen\IMAGE_IDLE_SCREEN_DEVICE_LOCK.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Idle_screen\IMAGE_IDLE_SCREEN_MESSAGE.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Idle_screen\IMAGE_IDLE_SCREEN_N_CALENDAR.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Idle_screen\IMAGE_IDLE_SCREEN_N_EMAIL.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Idle_screen\IMAGE_IDLE_SCREEN_N_GENERIC.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Idle_screen\IMAGE_IDLE_SCREEN_N_MESSAGE.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Idle_screen\IMAGE_IDLE_SCREEN_N_MISSED_CALL.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Idle_screen\IMAGE_IDLE_SCREEN_N_SNOOZE.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Idle_screen\IMAGE_IDLE_SCREEN_N_VOICEMAIL.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Idle_screen\IMAGE_IDLE_SCREEN_OPERATOR_MSG.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Idle_screen\IMAGE_IDLE_SCREEN_PLAYER_NEXT.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Idle_screen\IMAGE_IDLE_SCREEN_PLAYER_PAUSE.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Idle_screen\IMAGE_IDLE_SCREEN_PLAYER_PLAY.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Idle_screen\IMAGE_IDLE_SCREEN_PUSH.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Idle_screen\IMAGE_IDLE_SCREEN_REPLY.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Idle_screen\IMAGE_IDLE_SCREEN_N_MESSAGE_SIM1.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Idle_screen\IMAGE_IDLE_SCREEN_N_MESSAGE_SIM2.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Idle_screen\IMAGE_IDLE_SCREEN_MESSAGE_SIM1.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Idle_screen\IMAGE_IDLE_SCREEN_MESSAGE_SIM2.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Idle_screen\IMAGE_IDLE_SCREEN_VOICE_MAIL.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\MS_Identity\IMAGE_MS_IDENTITY_PROMO_SCREEN_ACCOUNT.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\MS_Identity\IMAGE_MS_IDENTITY_PROMO_SCREEN_CONTACTS.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\MS_Identity\IMAGE_MS_IDENTITY_PROMO_SCREEN_ONENOTE.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\MS_Identity\IMAGE_MS_IDENTITY_PROMO_SCREEN_OUTLOOK.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\MS_Identity\IMAGE_MS_IDENTITY_PROMO_SCREEN_PHOTOS.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\MS_Identity\IMAGE_CONTACTS_PROMO_INFO.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\settings\IMAGE_FILE_EXPLORER_FOLDER.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\settings\IMAGE_MEMORYCARD.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\settings\IMAGE_PHONEMEMORY.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\settings\IMAGE_SETTINGS_CONNECTIVITY_ICON.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\settings\IMAGE_SETTINGS_MICROSOFT_ACCOUNT_ICON.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\settings\IMAGE_SETTINGS_OPERATOR_ICON.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\settings\IMAGE_SETTINGS_PERSONALIZATION_ICON.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\settings\IMAGE_SETTINGS_QUICK_SETTINGS_ICON.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\settings\IMAGE_SETTINGS_SECURITY_ICON.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\settings\IMAGE_SETTINGS_SIM1_ICON.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\settings\IMAGE_SETTINGS_SIM2_ICON.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\settings\IMAGE_SETTINGS_STORAGE_ICON.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\settings\IMAGE_SETTINGS_SYSTEM_ICON.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\settings\IMAGE_SETTINGS_TIME_LANGUAGE_ICON.png

echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\status_area\IMAGE_STATUS_BAR_VOLTE.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\status_area\IMAGE_STATUS_BAR_HD.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\status_area\IMAGE_STATUS_BATTERY_NORMAL_0.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\status_area\IMAGE_STATUS_BATTERY_NORMAL_1.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\status_area\IMAGE_STATUS_BATTERY_NORMAL_2.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\status_area\IMAGE_STATUS_BATTERY_NORMAL_3.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\status_area\IMAGE_STATUS_BATTERY_NORMAL_4.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\status_area\IMAGE_STATUS_BATTERY_NORMAL_5.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\status_area\IMAGE_STATUS_BATTERY_NORMAL_6.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\status_area\IMAGE_STATUS_BATTERY_NORMAL_7.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\status_area\IMAGE_STATUS_BATTERY_NORMAL_8.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\status_area\IMAGE_STATUS_BATTERY_NORMAL_9.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\status_area\IMAGE_STATUS_BATTERY_NORMAL_FULL.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\status_area\IMAGE_STATUS_COUNTDOWN.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\status_area\IMAGE_STATUS_MESSAGE.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\status_area\IMAGE_STATUS_REMINDER.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\status_area\IMAGE_STATUS_STOPWATCH.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\status_area\IMAGE_STATUS_USB_CONNECTED.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\toolkit\IMAGE_ARROW_DOWN.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\toolkit\IMAGE_ARROW_DOWN_PRESS.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\toolkit\IMAGE_ARROW_UP.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\toolkit\IMAGE_ARROW_UP_PRESS.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\toolkit\IMAGE_BACKWARD.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\toolkit\IMAGE_CHECKBOX_OFF.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\toolkit\IMAGE_CHECKBOX_ON.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\toolkit\IMAGE_COMMON_BACK.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\toolkit\IMAGE_COMMON_BACKSPACE.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\toolkit\IMAGE_COMMON_CANCEL.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\toolkit\IMAGE_COMMON_CHECKMARK.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\toolkit\IMAGE_COMMON_CHECKMARK_DIMMED.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\toolkit\IMAGE_COMMON_COPY.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\toolkit\IMAGE_COMMON_DELETE.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\toolkit\IMAGE_COMMON_INFO.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\toolkit\IMAGE_COMMON_LIST_DISMISS.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\toolkit\IMAGE_COMMON_MENU.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\toolkit\IMAGE_COMMON_MESSAGE.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\toolkit\IMAGE_COMMON_MINUS.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\toolkit\IMAGE_COMMON_PLUS.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\toolkit\IMAGE_COMMON_PLUS_SMALL.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\toolkit\IMAGE_COMMON_SHARE.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\toolkit\IMAGE_COMMON_STOP.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\toolkit\IMAGE_DRILLDOWN_ARROW.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\toolkit\IMAGE_DRILLDOWN_ARROW_RTL.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\toolkit\IMAGE_FORWARD.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\toolkit\IMAGE_GRID_MULTISELECTOR_RED.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\toolkit\IMAGE_GRID_MULTISELECTOR_RED.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\toolkit\IMAGE_PRMIO_GRID_MULTISELECTOR.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\toolkit\IMAGE_PRIMO_GRID_CHECKMARK.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\toolkit\IMAGE_ICON_TEXT_CASE_LOWER.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\toolkit\IMAGE_ICON_TEXT_CASE_LOWER_RED.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\toolkit\IMAGE_ICON_TEXT_CASE_MIXED.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\toolkit\IMAGE_ICON_TEXT_CASE_MIXED_RED.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\toolkit\IMAGE_ICON_TEXT_CASE_NUMBER.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\toolkit\IMAGE_ICON_TEXT_CASE_NUMBER_RED.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\toolkit\IMAGE_ICON_TEXT_CASE_UPPER.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\toolkit\IMAGE_ICON_TEXT_CASE_UPPER_RED.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\toolkit\IMAGE_ICON_TEXT_PREDICTION_OFF.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\toolkit\IMAGE_ICON_TEXT_PREDICTION_OFF_RED.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\toolkit\IMAGE_ICON_TEXT_PREDICTION_ON.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\toolkit\IMAGE_ICON_TEXT_PREDICTION_ON_RED.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\toolkit\IMAGE_LISTITEM_AVATAR_INITIALS.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\toolkit\IMAGE_LISTITEM_SHORTCUT_42_LEFT_RED.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\toolkit\IMAGE_LISTITEM_SHORTCUT_42_LEFT_RED_MINUS_2.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\toolkit\IMAGE_LISTITEM_SHORTCUT_42_RIGHT_RED.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\toolkit\IMAGE_LISTITEM_SHORTCUT_42_RIGHT_RED_MINUS_2.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\toolkit\IMAGE_LISTITEM_SHORTCUT_52_LEFT_RED.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\toolkit\IMAGE_LISTITEM_SHORTCUT_52_LEFT_RED_MINUS_2.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\toolkit\IMAGE_LISTITEM_SHORTCUT_52_RIGHT_RED.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\toolkit\IMAGE_LISTITEM_SHORTCUT_52_RIGHT_RED_MINUS_2.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\toolkit\IMAGE_LISTITEM_SHORTCUT_64_LEFT_RED.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\toolkit\IMAGE_LISTITEM_SHORTCUT_64_LEFT_RED_MINUS_2.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\toolkit\IMAGE_LISTITEM_SHORTCUT_64_RIGHT_RED.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\toolkit\IMAGE_LISTITEM_SHORTCUT_64_RIGHT_RED_MINUS_2.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\toolkit\IMAGE_ICON_TEXT_CASE_LOWER.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\toolkit\IMAGE_ICON_TEXT_CASE_LOWER_RED.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\toolkit\IMAGE_ICON_TEXT_CASE_MIXED.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\toolkit\IMAGE_ICON_TEXT_CASE_MIXED_RED.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\toolkit\IMAGE_ICON_TEXT_CASE_NUMBER.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\toolkit\IMAGE_ICON_TEXT_CASE_NUMBER_RED.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\toolkit\IMAGE_ICON_TEXT_CASE_UPPER.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\toolkit\IMAGE_ICON_TEXT_CASE_UPPER_RED.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\toolkit\IMAGE_ICON_TEXT_PREDICTION_OFF.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\toolkit\IMAGE_ICON_TEXT_PREDICTION_OFF_RED.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\toolkit\IMAGE_ICON_TEXT_PREDICTION_ON.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\toolkit\IMAGE_ICON_TEXT_PREDICTION_ON_RED.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\toolkit\IMAGE_LISTITEM_AVATAR_INITIALS.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\toolkit\IMAGE_LISTITEM_AVATAR_MASK_RED.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\toolkit\IMAGE_LISTITEM_SHORTCUT_42_LEFT_RED.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\toolkit\IMAGE_LISTITEM_SHORTCUT_42_LEFT_RED_MINUS_2.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\toolkit\IMAGE_LISTITEM_SHORTCUT_42_RIGHT_RED.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\toolkit\IMAGE_LISTITEM_SHORTCUT_42_RIGHT_RED_MINUS_2.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\toolkit\IMAGE_LISTITEM_SHORTCUT_52_LEFT_RED.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\toolkit\IMAGE_LISTITEM_SHORTCUT_52_LEFT_RED_MINUS_2.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\toolkit\IMAGE_LISTITEM_SHORTCUT_52_RIGHT_RED.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\toolkit\IMAGE_LISTITEM_SHORTCUT_52_RIGHT_RED_MINUS_2.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\toolkit\IMAGE_LISTITEM_SHORTCUT_64_LEFT_RED.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\toolkit\IMAGE_LISTITEM_SHORTCUT_64_LEFT_RED_MINUS_2.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\toolkit\IMAGE_LISTITEM_SHORTCUT_64_RIGHT_RED.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\toolkit\IMAGE_LISTITEM_SHORTCUT_64_RIGHT_RED_MINUS_2.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\toolkit\IMAGE_PREFERRED_SIM1.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\toolkit\IMAGE_PREFERRED_SIM2.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\toolkit\IMAGE_RADIOBUTTON_OFF.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\toolkit\IMAGE_RADIOBUTTON_ON.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\toolkit\IMAGE_SCROLL_INDICATOR.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\toolkit\IMAGE_SHORTCUT_DELETE.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\toolkit\IMAGE_IDLE_SCREEN_SINGLE_SIM.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\toolkit\IMAGE_SOFTKEY_MINUS_ICON.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\toolkit\IMAGE_SOFTKEY_PLUS_ICON.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\toolkit\IMAGE_TOGGLE_OFF_RED.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\toolkit\IMAGE_TOGGLE_OFF_RED_MINUS_3.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\toolkit\IMAGE_TOGGLE_ON_RED.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\toolkit\IMAGE_TOGGLE_ON_RED_MINUS_3.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\toolkit\IMAGE_TOGGLE_OFF_RED.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\toolkit\IMAGE_TOGGLE_OFF_RED_MINUS_3.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\toolkit\IMAGE_TOGGLE_ON_RED.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\toolkit\IMAGE_TOGGLE_ON_RED_MINUS_3.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\toolkit\IMAGE_SIM1_SMALL.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\toolkit\IMAGE_SIM2_SMALL.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\toolkit\IMAGE_IDLE_SCREEN_CALL_SIM1.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\toolkit\IMAGE_IDLE_SCREEN_CALL_SIM2.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\toolkit\IMAGE_CALLING_VIEW_VOLTE.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\toolkit\IMAGE_CALLING_VIEW_HD.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\toolkit\IMAGE_ARROW_LEFT.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\toolkit\IMAGE_ARROW_LEFT_PRESS.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\toolkit\IMAGE_ARROW_RIGHT.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\toolkit\IMAGE_ARROW_RIGHT_PRESS.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\List\IMAGE_AVATAR_CHECKBOX_MASK_1_OFF.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\List\IMAGE_AVATAR_CHECKBOX_MASK_2_OFF.png
echo y | xcopy 1.gif .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Circular_loader\circular_loader.gif
echo y | xcopy 1.gif .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Waiting_indicator\yellow.gif
echo y | xcopy 1.gif .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Waiting_indicator\yellow_dark.gif
echo y | xcopy 1.gif .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Waiting_indicator\red.gif
echo y | xcopy 1.gif .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\Waiting_indicator\red_dark.gif
echo y | xcopy 1.png .\mmi_res_240x240\dataCounter\MMI_RES_DEFAULT\IMAG\IMAGE_CALENDAR_FOCUSED_RED-2.png
echo y | xcopy 1.png .\mmi_res_240x240\dataCounter\MMI_RES_DEFAULT\IMAG\IMAGE_CALENDAR_FOCUSED_TODAY_RED.png
echo y | xcopy 1.png .\mmi_res_240x240\dataCounter\MMI_RES_DEFAULT\IMAG\IMAGE_DIALOG_ALERT_NOTIFICATION.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\SKIN_1\IMG_IMSP_ARROW_DOWN_DIS.png
echo y | xcopy 1.png .\mmi_res_240x240\common\MMI_RES_DEFAULT\IMAG\SKIN_1\IMG_IMSP_ARROW_DOWN_OFF.png
echo y | xcopy 1.png .\mmi_res_240x240\im\MMI_RES_DEFAULT\IMAG\SKIN_1\IMG_IMSP_ARROW_DOWN_ON.png
echo y | xcopy 1.png .\mmi_res_240x240\im\MMI_RES_DEFAULT\IMAG\SKIN_1\IMG_IMSP_ARROW_UP_DIS.png
echo y | xcopy 1.png .\mmi_res_240x240\im\MMI_RES_DEFAULT\IMAG\SKIN_1\IMG_IMSP_ARROW_UP_OFF.png
echo y | xcopy 1.png .\mmi_res_240x240\im\MMI_RES_DEFAULT\IMAG\SKIN_1\IMG_IMSP_ARROW_UP_ON.png
echo y | xcopy 1.png .\mmi_res_240x240\im\MMI_RES_DEFAULT\IMAG\SKIN_1\IMG_IMSP_CAND_BAR.png
echo y | xcopy 1.png .\mmi_res_240x240\im\MMI_RES_DEFAULT\IMAG\SKIN_1\IMG_IMSP_SYMBOL_SPACE.png
echo y | xcopy 1.png .\mmi_res_240x240\im\MMI_RES_DEFAULT\IMAG\SKIN_1\IMG_IMSP_SYMBOL_ENTER.png
echo y | xcopy 1.bmp .\mmi_res_240x240\im\MMI_RES_DEFAULT\IMAG\IMAGE_IME_DIGIT.bmp
echo y | xcopy 1.bmp .\mmi_res_240x240\im\MMI_RES_DEFAULT\IMAG\IMAGE_IME_ENGLISH_ABC_LEAD_UPPER.bmp
echo y | xcopy 1.bmp .\mmi_res_240x240\im\MMI_RES_DEFAULT\IMAG\IMAGE_IME_ENGLISH_ABC_LOWER.bmp
echo y | xcopy 1.bmp .\mmi_res_240x240\im\MMI_RES_DEFAULT\IMAG\IMAGE_IME_ENGLISH_ABC_UPPER.bmp
echo y | xcopy 1.bmp .\mmi_res_240x240\im\MMI_RES_DEFAULT\IMAG\IMAGE_IME_PINYIN.bmp
echo y | xcopy 1.bmp .\mmi_res_240x240\im\MMI_RES_DEFAULT\IMAG\IMAGE_IME_STROKE.bmp
echo y | xcopy 1.bmp .\mmi_res_240x240\im\MMI_RES_DEFAULT\IMAG\IMAGE_NULL.bmp
echo y | xcopy 1.bmp .\mmi_res_240x240\im\MMI_RES_DEFAULT\IMAG\IMAGE_NULL.bmp
echo y | xcopy 1.bmp .\mmi_res_240x240\im\MMI_RES_DEFAULT\IMAG\SOGOU\IMAGE_IME_DIGIT.bmp
echo y | xcopy 1.bmp .\mmi_res_240x240\im\MMI_RES_DEFAULT\IMAG\SOGOU\IMAGE_IME_ENGLISH_ABC_LEAD_UPPER.bmp
echo y | xcopy 1.bmp .\mmi_res_240x240\im\MMI_RES_DEFAULT\IMAG\SOGOU\IMAGE_IME_ENGLISH_ABC_LOWER.bmp
echo y | xcopy 1.bmp .\mmi_res_240x240\im\MMI_RES_DEFAULT\IMAG\SOGOU\IMAGE_IME_ENGLISH_ABC_UPPER.bmp
echo y | xcopy 1.bmp .\mmi_res_240x240\im\MMI_RES_DEFAULT\IMAG\ICON\IMAGE_IME_DIGIT.bmp
echo y | xcopy 1.bmp .\mmi_res_240x240\im\MMI_RES_DEFAULT\IMAG\ICON\IMAGE_IME_ENGLISH_ABC_LEAD_UPPER.bmp
echo y | xcopy 1.bmp .\mmi_res_240x240\im\MMI_RES_DEFAULT\IMAG\ICON\IMAGE_IME_ENGLISH_ABC_LOWER.bmp
echo y | xcopy 1.bmp .\mmi_res_240x240\im\MMI_RES_DEFAULT\IMAG\ICON\IMAGE_IME_ENGLISH_ABC_UPPER.bmp
echo y | xcopy 1.bmp .\mmi_res_240x240\im\MMI_RES_DEFAULT\IMAG\SOGOU\IMAGE_IME_PINYIN.bmp
echo y | xcopy 1.bmp .\mmi_res_240x240\im\MMI_RES_DEFAULT\IMAG\SOGOU\IMAGE_IME_STROKE.bmp
echo y | xcopy 1.bmp .\mmi_res_240x240\im\MMI_RES_DEFAULT\IMAG\ICON\IMAGE_IME_PINYIN.bmp
echo y | xcopy 1.bmp .\mmi_res_240x240\im\MMI_RES_DEFAULT\IMAG\ICON\IMAGE_IME_STROKE.bmp
echo y | xcopy 1.bmp .\mmi_res_240x240\im\MMI_RES_DEFAULT\IMAG\ICON\IMAGE_NULL.bmp
echo y | xcopy 1.bmp .\mmi_res_240x240\im\MMI_RES_DEFAULT\IMAG\ICON\IMAGE_NULL.bmp
echo y | xcopy 1.bmp .\mmi_res_240x240\im\MMI_RES_DEFAULT\IMAG\IMAGE_IME_SMART_ENGLISH_LEAD_UPPER.bmp
echo y | xcopy 1.bmp .\mmi_res_240x240\im\MMI_RES_DEFAULT\IMAG\IMAGE_IME_SMART_ENGLISH_LOWER.bmp
echo y | xcopy 1.bmp .\mmi_res_240x240\im\MMI_RES_DEFAULT\IMAG\IMAGE_IME_SMART_ENGLISH_UPPER.bmp
echo y | xcopy 1.bmp .\mmi_res_240x240\im\MMI_RES_DEFAULT\IMAG\SOGOU\IMAGE_IME_SMART_ENGLISH_LEAD_UPPER.bmp
echo y | xcopy 1.bmp .\mmi_res_240x240\im\MMI_RES_DEFAULT\IMAG\SOGOU\IMAGE_IME_SMART_ENGLISH_LOWER.bmp
echo y | xcopy 1.bmp .\mmi_res_240x240\im\MMI_RES_DEFAULT\IMAG\SOGOU\IMAGE_IME_SMART_ENGLISH_UPPER.bmp
echo y | xcopy 1.bmp .\mmi_res_240x240\im\MMI_RES_DEFAULT\IMAG\ICON\IMAGE_IME_SMART_ENGLISH_LEAD_UPPER.bmp
echo y | xcopy 1.bmp .\mmi_res_240x240\im\MMI_RES_DEFAULT\IMAG\ICON\IMAGE_IME_SMART_ENGLISH_LOWER.bmp
echo y | xcopy 1.bmp .\mmi_res_240x240\im\MMI_RES_DEFAULT\IMAG\ICON\IMAGE_IME_SMART_ENGLISH_UPPER.bmp
echo y | xcopy 1.bmp .\mmi_res_240x240\im\MMI_RES_DEFAULT\IMAG\IMAGE_MULTIM_RECORD_TIP.bmp
echo y | xcopy 1.png .\mmi_res_240x240\im\MMI_RES_DEFAULT\IMAG\IMAGE_MULTIM_PROCESS_GROOVE_1.png
echo y | xcopy 1.bmp .\mmi_res_240x240\im\MMI_RES_DEFAULT\IMAG\IMAGE_MULTIM_PROCESS_GROOVE_1.bmp
echo y | xcopy 1.png .\mmi_res_240x240\dataCounter\MMI_RES_DEFAULT\IMAG\IMAGE_DIALOG_ALERT_NOTIFICATION.png
echo y | xcopy 1.png .\mmi_res_240x240\dataCounter\MMI_RES_DEFAULT\IMAG\IMAGE_DIALOG_ALERT_NOTIFICATION.png
echo y | xcopy 1.png .\mmi_res_240x240\cc\MMI_RES_DEFAULT\IMAG\IMAGE_EXTRAS_FLASHLIGHT_BACK_RED.png
echo y | xcopy 1.png .\mmi_res_240x240\cc\MMI_RES_DEFAULT\IMAG\IMAGE_EXTRAS_FLASHLIGHT_BACK_RED.png

