

copy .\mmi_res_128x160\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon\no_sim\IMAGE_IDLE_ICON_NO_SIM.png .\mmi_res_all_image\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon\no_sim\IMAGE_IDLE_ICON_NO_SIM.png
copy .\mmi_res_128x160\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon\idle_prompt\IMAGE_IDLE_PROMPT_SIM1.png .\mmi_res_all_image\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon\idle_prompt\IMAGE_IDLE_PROMPT_SIM1.png
copy .\mmi_res_128x160\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon\idle_prompt\IMAGE_IDLE_PROMPT_SIM2.png .\mmi_res_all_image\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon\idle_prompt\IMAGE_IDLE_PROMPT_SIM2.png
copy .\mmi_res_128x160\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon\idle_prompt\IMAGE_IDLE_PROMPT_GRAY_SIM1.png .\mmi_res_all_image\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon\idle_prompt\IMAGE_IDLE_PROMPT_GRAY_SIM1.png
copy .\mmi_res_128x160\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon\idle_prompt\IMAGE_IDLE_PROMPT_GRAY_SIM2.png .\mmi_res_all_image\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon\idle_prompt\IMAGE_IDLE_PROMPT_GRAY_SIM2.png
copy .\mmi_res_128x160\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon\idle_prompt\IMAGE_IDLE_PROMPT_NO_SIM1.png .\mmi_res_all_image\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon\idle_prompt\IMAGE_IDLE_PROMPT_NO_SIM1.png
copy .\mmi_res_128x160\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon\idle_prompt\IMAGE_IDLE_PROMPT_NO_SIM2.png .\mmi_res_all_image\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon\idle_prompt\IMAGE_IDLE_PROMPT_NO_SIM2.png
copy .\mmi_res_128x160\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon\sim_image\IMAGE_SIM1.png .\mmi_res_all_image\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon\sim_image\IMAGE_SIM1.png
copy .\mmi_res_128x160\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon\sim_image\IMAGE_SIM2.png .\mmi_res_all_image\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon\sim_image\IMAGE_SIM2.png
copy .\mmi_res_128x160\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon\fdn\IMAGE_IDLE_TITLE_ICON_FDN.png .\mmi_res_all_image\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon\fdn\IMAGE_IDLE_TITLE_ICON_FDN.png
copy .\mmi_res_128x160\common\MMI_RES_DEFAULT\IMAG\Optionsmenu_icon\IMAGE_COMMON_OPTMENU_SET.png .\mmi_res_all_image\common\MMI_RES_DEFAULT\IMAG\Optionsmenu_icon\IMAGE_COMMON_OPTMENU_SET.png
copy .\mmi_res_128x160\common\MMI_RES_DEFAULT\IMAG\Optionsmenu_icon\IMAGE_COMMON_OPTMENU_ADD.png .\mmi_res_all_image\common\MMI_RES_DEFAULT\IMAG\Optionsmenu_icon\IMAGE_COMMON_OPTMENU_ADD.png
copy .\mmi_res_128x160\common\MMI_RES_DEFAULT\IMAG\Optionsmenu_icon\IMAGE_COMMON_OPTMENU_SEARCH.png .\mmi_res_all_image\common\MMI_RES_DEFAULT\IMAG\Optionsmenu_icon\IMAGE_COMMON_OPTMENU_SEARCH.png
copy .\mmi_res_128x160\common\MMI_RES_DEFAULT\IMAG\Optionsmenu_icon\IMAGE_COMMON_OPTMENU_NOTIFY.png .\mmi_res_all_image\common\MMI_RES_DEFAULT\IMAG\Optionsmenu_icon\IMAGE_COMMON_OPTMENU_NOTIFY.png
copy .\mmi_res_128x160\common\MMI_RES_DEFAULT\IMAG\Optionsmenu_icon\IMAGE_COMMON_OPTMENU_SET_WALLPAPER.png .\mmi_res_all_image\common\MMI_RES_DEFAULT\IMAG\Optionsmenu_icon\IMAGE_COMMON_OPTMENU_SET_WALLPAPER.png
copy .\mmi_res_128x160\common\MMI_RES_DEFAULT\IMAG\Common\IMAGE_COMMON_PICVIEW_BUTTON.png .\mmi_res_all_image\common\MMI_RES_DEFAULT\IMAG\Common\IMAGE_COMMON_PICVIEW_BUTTON.png
copy .\mmi_res_128x160\common\MMI_RES_DEFAULT\IMAG\idle_icon\IMAGE_IDLE_ICON_PB.png .\mmi_res_all_image\common\MMI_RES_DEFAULT\IMAG\idle_icon\IMAGE_IDLE_ICON_PB.png
copy .\mmi_res_128x160\common\MMI_RES_DEFAULT\IMAG\idle_icon\IMAGE_IDLE_ICON_MENU.png .\mmi_res_all_image\common\MMI_RES_DEFAULT\IMAG\idle_icon\IMAGE_IDLE_ICON_MENU.png
copy .\mmi_res_128x160\common\MMI_RES_DEFAULT\IMAG\idle_icon\IMAGE_IDLE_ICON_RECONNECT.png .\mmi_res_all_image\common\MMI_RES_DEFAULT\IMAG\idle_icon\IMAGE_IDLE_ICON_RECONNECT.png

copy .\mmi_res_128x160\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon\power_saver\IMAGE_IDLE_TITLE_ICON_PS_BATTERY1.png .\mmi_res_all_image\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon\power_saver\IMAGE_IDLE_TITLE_ICON_PS_BATTERY1.png
copy .\mmi_res_128x160\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon\power_saver\IMAGE_IDLE_TITLE_ICON_PS_BATTERY2.png .\mmi_res_all_image\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon\power_saver\IMAGE_IDLE_TITLE_ICON_PS_BATTERY2.png
copy .\mmi_res_128x160\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon\power_saver\IMAGE_IDLE_TITLE_ICON_PS_BATTERY3.png .\mmi_res_all_image\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon\power_saver\IMAGE_IDLE_TITLE_ICON_PS_BATTERY3.png
copy .\mmi_res_128x160\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon\power_saver\IMAGE_IDLE_TITLE_ICON_PS_BATTERY4.png .\mmi_res_all_image\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon\power_saver\IMAGE_IDLE_TITLE_ICON_PS_BATTERY4.png
copy .\mmi_res_128x160\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon\power_saver\IMAGE_IDLE_TITLE_ICON_PS_BATTERY5.png .\mmi_res_all_image\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon\power_saver\IMAGE_IDLE_TITLE_ICON_PS_BATTERY5.png
copy .\mmi_res_128x160\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon\power_saver\IMAGE_IDLE_TITLE_ICON_PS_BATTERY6.png .\mmi_res_all_image\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon\power_saver\IMAGE_IDLE_TITLE_ICON_PS_BATTERY6.png

copy .\mmi_res_128x160\common\MMI_RES_DEFAULT\IMAG\key_lock\qqvga\IMAGE_QQVGA_KEYLOCK_CALL.png .\mmi_res_all_image\common\MMI_RES_DEFAULT\IMAG\key_lock\qqvga\IMAGE_QQVGA_KEYLOCK_CALL.png
copy .\mmi_res_128x160\common\MMI_RES_DEFAULT\IMAG\key_lock\qqvga\IMAGE_QQVGA_KEYLOCK_MESSAGE.png .\mmi_res_all_image\common\MMI_RES_DEFAULT\IMAG\key_lock\qqvga\IMAGE_QQVGA_KEYLOCK_MESSAGE.png
copy .\mmi_res_128x160\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon\IMAGE_IDLE_T_STATUSBAR_ICON.png .\mmi_res_all_image\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon\IMAGE_IDLE_T_STATUSBAR_ICON.png
copy .\mmi_res_128x160\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon\IMAGE_IDLE_TITLE_ICON_BT_VISIBLE.png .\mmi_res_all_image\common\MMI_RES_DEFAULT\IMAG\StatusbarIcon\IMAGE_IDLE_TITLE_ICON_BT_VISIBLE.png


copy .\mmi_res_128x160\common\MMI_RES_DEFAULT\IMAG\Mainmenu_icon\IMAGE_MAINMENU_ICON_AUDIO_PLAYER.png .\mmi_res_all_image\common\MMI_RES_DEFAULT\IMAG\Mainmenu_icon\IMAGE_MAINMENU_ICON_AUDIO_PLAYER.png












































































































copy .\mmi_res_128x160\cc\MMI_RES_DEFAULT\IMAG\cc\IMAGE_CC_CALLING_PHOTO_ANIM.gif .\mmi_res_all_image\cc\MMI_RES_DEFAULT\IMAG\cc\IMAGE_CC_CALLING_PHOTO_ANIM.gif
copy .\mmi_res_128x160\cc\MMI_RES_DEFAULT\IMAG\cc\IMAGE_CC_INCOMING_PHOTO_ANIM.gif .\mmi_res_all_image\cc\MMI_RES_DEFAULT\IMAG\cc\IMAGE_CC_INCOMING_PHOTO_ANIM.gif
copy .\mmi_res_128x160\cc\MMI_RES_DEFAULT\IMAG\cc\IMAGE_CC_CALL_PHOTO_ANIM.gif .\mmi_res_all_image\cc\MMI_RES_DEFAULT\IMAG\cc\IMAGE_CC_CALL_PHOTO_ANIM.gif
























copy .\mmi_res_128x160\common\MMI_RES_DEFAULT\IMAG\VOL_contrast\IMAGE_COMMON_PLAYER_PANEL_VOL_MUTE.png .\mmi_res_all_image\common\MMI_RES_DEFAULT\IMAG\VOL_contrast\IMAGE_COMMON_PLAYER_PANEL_VOL_MUTE.png
copy .\mmi_res_128x160\common\MMI_RES_DEFAULT\IMAG\VOL_contrast\IMAGE_COMMON_PLAYER_PANEL_VOL_UNMUTE.png .\mmi_res_all_image\common\MMI_RES_DEFAULT\IMAG\VOL_contrast\IMAGE_COMMON_PLAYER_PANEL_VOL_UNMUTE.png
copy .\mmi_res_128x160\common\MMI_RES_DEFAULT\IMAG\VOL_contrast\IMAGE_COMMON_PLAYER_PANEL_PROGRESS_BG.png .\mmi_res_all_image\common\MMI_RES_DEFAULT\IMAG\VOL_contrast\IMAGE_COMMON_PLAYER_PANEL_PROGRESS_BG.png
copy .\mmi_res_128x160\common\MMI_RES_DEFAULT\IMAG\VOL_contrast\IMAGE_COMMON_PLAYER_PANEL_PROGRESS.png .\mmi_res_all_image\common\MMI_RES_DEFAULT\IMAG\VOL_contrast\IMAGE_COMMON_PLAYER_PANEL_PROGRESS.png
copy .\mmi_res_128x160\common\MMI_RES_DEFAULT\IMAG\Common\IMAGE_COMMON_SELECTED_BAR.png .\mmi_res_all_image\common\MMI_RES_DEFAULT\IMAG\Common\IMAGE_COMMON_SELECTED_BAR.png
copy .\mmi_res_128x160\common\MMI_RES_DEFAULT\IMAG\Statusbar\IMAGE_CONTROL_STATUSBAR_BG.png .\mmi_res_all_image\common\MMI_RES_DEFAULT\IMAG\Statusbar\IMAGE_CONTROL_STATUSBAR_BG.png
copy .\mmi_res_128x160\common\MMI_RES_DEFAULT\IMAG\Title\Common\IMAGE_TITLE_BAR.png .\mmi_res_all_image\common\MMI_RES_DEFAULT\IMAG\Title\Common\IMAGE_TITLE_BAR.png
copy .\mmi_res_128x160\common\MMI_RES_DEFAULT\IMAG\Title\IMAGE_LIST_TITLE_ARROW_LEFT_UP.png .\mmi_res_all_image\common\MMI_RES_DEFAULT\IMAG\Title\IMAGE_LIST_TITLE_ARROW_LEFT_UP.png
copy .\mmi_res_128x160\common\MMI_RES_DEFAULT\IMAG\Title\IMAGE_LIST_TITLE_ARROW_RIGHT_UP.png .\mmi_res_all_image\common\MMI_RES_DEFAULT\IMAG\Title\IMAGE_LIST_TITLE_ARROW_RIGHT_UP.png
copy .\mmi_res_128x160\common\MMI_RES_DEFAULT\IMAG\List\IMAGE_CONTROL_LIST_RADIO_PRESSED.png .\mmi_res_all_image\common\MMI_RES_DEFAULT\IMAG\List\IMAGE_CONTROL_LIST_RADIO_PRESSED.png
copy .\mmi_res_128x160\common\MMI_RES_DEFAULT\IMAG\List\IMAGE_CONTROL_LIST_RADIO_DEFAULT.png .\mmi_res_all_image\common\MMI_RES_DEFAULT\IMAG\List\IMAGE_CONTROL_LIST_RADIO_DEFAULT.png
copy .\mmi_res_128x160\common\MMI_RES_DEFAULT\IMAG\List\IMAGE_CONTROL_LIST_CHECK_PRESSED.png .\mmi_res_all_image\common\MMI_RES_DEFAULT\IMAG\List\IMAGE_CONTROL_LIST_CHECK_PRESSED.png
copy .\mmi_res_128x160\common\MMI_RES_DEFAULT\IMAG\List\IMAGE_CONTROL_LIST_CHECK_DEFAULT.png .\mmi_res_all_image\common\MMI_RES_DEFAULT\IMAG\List\IMAGE_CONTROL_LIST_CHECK_DEFAULT.png




copy .\mmi_res_128x160\common\MMI_RES_DEFAULT\IMAG\setlist\IMAGE_CONTROL_SETLIST_ARROW_LEFT_UP.png .\mmi_res_all_image\common\MMI_RES_DEFAULT\IMAG\setlist\IMAGE_CONTROL_SETLIST_ARROW_LEFT_UP.png
copy .\mmi_res_128x160\common\MMI_RES_DEFAULT\IMAG\setlist\IMAGE_CONTROL_SETLIST_ARROW_RIGHT_UP.png .\mmi_res_all_image\common\MMI_RES_DEFAULT\IMAG\setlist\IMAGE_CONTROL_SETLIST_ARROW_RIGHT_UP.png

copy .\mmi_res_128x160\common\MMI_RES_DEFAULT\IMAG\Mainmenu_icon\IMAGE_MAINMENU_ICON_SELECT.png .\mmi_res_all_image\common\MMI_RES_DEFAULT\IMAG\Mainmenu_icon\IMAGE_MAINMENU_ICON_SELECT.png


copy .\mmi_res_128x160\common\MMI_RES_DEFAULT\IMAG\Number\IMAGE_NUMBER_1.png .\mmi_res_all_image\common\MMI_RES_DEFAULT\IMAG\Number\IMAGE_NUMBER_1.png
copy .\mmi_res_128x160\common\MMI_RES_DEFAULT\IMAG\Number\IMAGE_NUMBER_2.png .\mmi_res_all_image\common\MMI_RES_DEFAULT\IMAG\Number\IMAGE_NUMBER_2.png
copy .\mmi_res_128x160\common\MMI_RES_DEFAULT\IMAG\Number\IMAGE_NUMBER_3.png .\mmi_res_all_image\common\MMI_RES_DEFAULT\IMAG\Number\IMAGE_NUMBER_3.png
copy .\mmi_res_128x160\common\MMI_RES_DEFAULT\IMAG\Number\IMAGE_NUMBER_4.png .\mmi_res_all_image\common\MMI_RES_DEFAULT\IMAG\Number\IMAGE_NUMBER_4.png
copy .\mmi_res_128x160\common\MMI_RES_DEFAULT\IMAG\Number\IMAGE_NUMBER_5.png .\mmi_res_all_image\common\MMI_RES_DEFAULT\IMAG\Number\IMAGE_NUMBER_5.png
copy .\mmi_res_128x160\common\MMI_RES_DEFAULT\IMAG\Number\IMAGE_NUMBER_6.png .\mmi_res_all_image\common\MMI_RES_DEFAULT\IMAG\Number\IMAGE_NUMBER_6.png
copy .\mmi_res_128x160\common\MMI_RES_DEFAULT\IMAG\Number\IMAGE_NUMBER_7.png .\mmi_res_all_image\common\MMI_RES_DEFAULT\IMAG\Number\IMAGE_NUMBER_7.png
copy .\mmi_res_128x160\common\MMI_RES_DEFAULT\IMAG\Number\IMAGE_NUMBER_8.png .\mmi_res_all_image\common\MMI_RES_DEFAULT\IMAG\Number\IMAGE_NUMBER_8.png
copy .\mmi_res_128x160\common\MMI_RES_DEFAULT\IMAG\Number\IMAGE_NUMBER_9.png .\mmi_res_all_image\common\MMI_RES_DEFAULT\IMAG\Number\IMAGE_NUMBER_9.png
copy .\mmi_res_128x160\common\MMI_RES_DEFAULT\IMAG\Number\IMAGE_NUMBER_10.png .\mmi_res_all_image\common\MMI_RES_DEFAULT\IMAG\Number\IMAGE_NUMBER_10.png










copy .\mmi_res_128x160\common\MMI_RES_DEFAULT\IMAG\Prgbox\IMAGE_SCROLL_VER_BAR.bmp .\mmi_res_all_image\common\MMI_RES_DEFAULT\IMAG\Prgbox\IMAGE_SCROLL_VER_BAR.bmp
copy .\mmi_res_128x160\common\MMI_RES_DEFAULT\IMAG\Prgbox\IMAGE_CONTROL_VER_BAR.png .\mmi_res_all_image\common\MMI_RES_DEFAULT\IMAG\Prgbox\IMAGE_CONTROL_VER_BAR.png
copy .\mmi_res_128x160\common\MMI_RES_DEFAULT\IMAG\Pubwin\PDA\IMAGE_CONTROL_POPWIN_WARNING.png .\mmi_res_all_image\common\MMI_RES_DEFAULT\IMAG\Pubwin\PDA\IMAGE_CONTROL_POPWIN_WARNING.png
copy .\mmi_res_128x160\common\MMI_RES_DEFAULT\IMAG\Pubwin\PDA\IMAGE_CONTROL_POPWIN_SUCCESS.png .\mmi_res_all_image\common\MMI_RES_DEFAULT\IMAG\Pubwin\PDA\IMAGE_CONTROL_POPWIN_SUCCESS.png
copy .\mmi_res_128x160\common\MMI_RES_DEFAULT\IMAG\Pubwin\PDA\IMAGE_CONTROL_POPWIN_QUERY.png .\mmi_res_all_image\common\MMI_RES_DEFAULT\IMAG\Pubwin\PDA\IMAGE_CONTROL_POPWIN_QUERY.png
copy .\mmi_res_128x160\common\MMI_RES_DEFAULT\IMAG\Pubwin\PDA\IMAGE_CONTROL_POPWIN_FAIL.png .\mmi_res_all_image\common\MMI_RES_DEFAULT\IMAG\Pubwin\PDA\IMAGE_CONTROL_POPWIN_FAIL.png
copy .\mmi_res_128x160\common\MMI_RES_DEFAULT\IMAG\Softkey\IMAGE_SOFTKEY_BG.png .\mmi_res_all_image\common\MMI_RES_DEFAULT\IMAG\Softkey\IMAGE_SOFTKEY_BG.png
copy .\mmi_res_128x160\common\MMI_RES_DEFAULT\IMAG\Bg\IMAGE_COMMON_BG.bmp .\mmi_res_all_image\common\MMI_RES_DEFAULT\IMAG\Bg\IMAGE_COMMON_BG.bmp



















copy .\mmi_res_128x160\cc\MMI_RES_DEFAULT\IMAG\cc\IMAGE_CC_CALLING_PHOTO_ANIM.gif .\mmi_res_all_image\cc\MMI_RES_DEFAULT\IMAG\cc\IMAGE_CC_CALLING_PHOTO_ANIM.gif
copy .\mmi_res_128x160\cc\MMI_RES_DEFAULT\IMAG\cc\IMAGE_CC_INCOMING_PHOTO_ANIM.gif .\mmi_res_all_image\cc\MMI_RES_DEFAULT\IMAG\cc\IMAGE_CC_INCOMING_PHOTO_ANIM.gif
copy .\mmi_res_128x160\cc\MMI_RES_DEFAULT\IMAG\cc\IMAGE_CC_CALL_PHOTO_ANIM.gif .\mmi_res_all_image\cc\MMI_RES_DEFAULT\IMAG\cc\IMAGE_CC_CALL_PHOTO_ANIM.gif













copy .\mmi_res_128x160\common\MMI_RES_DEFAULT\IMAG\Common\IMAGE_COMMON_SELECTED_BAR.png .\mmi_res_all_image\common\MMI_RES_DEFAULT\IMAG\Common\IMAGE_COMMON_SELECTED_BAR.png
copy .\mmi_res_128x160\common\MMI_RES_DEFAULT\IMAG\Statusbar\IMAGE_CONTROL_STATUSBAR_BG.png .\mmi_res_all_image\common\MMI_RES_DEFAULT\IMAG\Statusbar\IMAGE_CONTROL_STATUSBAR_BG.png
copy .\mmi_res_128x160\common\MMI_RES_DEFAULT\IMAG\Title\Common\IMAGE_TITLE_BAR.png .\mmi_res_all_image\common\MMI_RES_DEFAULT\IMAG\Title\Common\IMAGE_TITLE_BAR.png

copy .\mmi_res_128x160\common\MMI_RES_DEFAULT\IMAG\Mainmenu_icon\IMAGE_MAINMENU_ICON_SELECT.png .\mmi_res_all_image\common\MMI_RES_DEFAULT\IMAG\Mainmenu_icon\IMAGE_MAINMENU_ICON_SELECT.png


copy .\mmi_res_128x160\common\MMI_RES_DEFAULT\IMAG\Prgbox\IMAGE_SCROLL_VER_BAR.bmp .\mmi_res_all_image\common\MMI_RES_DEFAULT\IMAG\Prgbox\IMAGE_SCROLL_VER_BAR.bmp
copy .\mmi_res_128x160\common\MMI_RES_DEFAULT\IMAG\Prgbox\IMAGE_CONTROL_VER_BAR.png .\mmi_res_all_image\common\MMI_RES_DEFAULT\IMAG\Prgbox\IMAGE_CONTROL_VER_BAR.png
copy .\mmi_res_128x160\common\MMI_RES_DEFAULT\IMAG\Softkey\IMAGE_SOFTKEY_BG.png .\mmi_res_all_image\common\MMI_RES_DEFAULT\IMAG\Softkey\IMAGE_SOFTKEY_BG.png
copy .\mmi_res_128x160\common\MMI_RES_DEFAULT\IMAG\Bg\IMAGE_COMMON_BG.bmp .\mmi_res_all_image\common\MMI_RES_DEFAULT\IMAG\Bg\IMAGE_COMMON_BG.bmp



copy .\mmi_res_128x160\cc\MMI_RES_DEFAULT\IMAG\cc\IMAGE_CC_CALLING_PHOTO_ANIM.gif .\mmi_res_all_image\cc\MMI_RES_DEFAULT\IMAG\cc\IMAGE_CC_CALLING_PHOTO_ANIM.gif
copy .\mmi_res_128x160\cc\MMI_RES_DEFAULT\IMAG\cc\IMAGE_CC_INCOMING_PHOTO_ANIM.gif .\mmi_res_all_image\cc\MMI_RES_DEFAULT\IMAG\cc\IMAGE_CC_INCOMING_PHOTO_ANIM.gif
copy .\mmi_res_128x160\cc\MMI_RES_DEFAULT\IMAG\cc\IMAGE_CC_CALL_PHOTO_ANIM.gif .\mmi_res_all_image\cc\MMI_RES_DEFAULT\IMAG\cc\IMAGE_CC_CALL_PHOTO_ANIM.gif











copy .\mmi_res_128x160\im\MMI_RES_DEFAULT\IMAG\SKIN_1\IMG_IMSP_SYMBOL_SPACE.png .\mmi_res_all_image\im\MMI_RES_DEFAULT\IMAG\SKIN_1\IMG_IMSP_SYMBOL_SPACE.png
copy .\mmi_res_128x160\im\MMI_RES_DEFAULT\IMAG\SKIN_1\IMG_IMSP_SYMBOL_ENTER.png .\mmi_res_all_image\im\MMI_RES_DEFAULT\IMAG\SKIN_1\IMG_IMSP_SYMBOL_ENTER.png
copy .\mmi_res_128x160\mms\MMI_RES_DEFAULT\IMAG\IMAGE_MMS_EDIT_TO.png .\mmi_res_all_image\mms\MMI_RES_DEFAULT\IMAG\IMAGE_MMS_EDIT_TO.png
copy .\mmi_res_128x160\mms\MMI_RES_DEFAULT\IMAG\IMAGE_MMS_EDIT_VIDEO.png .\mmi_res_all_image\mms\MMI_RES_DEFAULT\IMAG\IMAGE_MMS_EDIT_VIDEO.png
copy .\mmi_res_128x160\mms\MMI_RES_DEFAULT\IMAG\IMAGE_MMS_EDIT_SUBJECT.png .\mmi_res_all_image\mms\MMI_RES_DEFAULT\IMAG\IMAGE_MMS_EDIT_SUBJECT.png
copy .\mmi_res_128x160\mms\MMI_RES_DEFAULT\IMAG\IMAGE_MMS_EDIT_ADD_PIC_OR_VIDEO.png .\mmi_res_all_image\mms\MMI_RES_DEFAULT\IMAG\IMAGE_MMS_EDIT_ADD_PIC_OR_VIDEO.png
copy .\mmi_res_128x160\mms\MMI_RES_DEFAULT\IMAG\IMAGE_MMS_EDIT_ADD_MENU_FOCUS.png .\mmi_res_all_image\mms\MMI_RES_DEFAULT\IMAG\IMAGE_MMS_EDIT_ADD_MENU_FOCUS.png
copy .\mmi_res_128x160\mms\MMI_RES_DEFAULT\IMAG\IMAGE_MMS_EDIT_ADD_MENU.png .\mmi_res_all_image\mms\MMI_RES_DEFAULT\IMAG\IMAGE_MMS_EDIT_ADD_MENU.png
copy .\mmi_res_128x160\mms\MMI_RES_DEFAULT\IMAG\IMAGE_MMS_ACCESSORY_FILE.png .\mmi_res_all_image\mms\MMI_RES_DEFAULT\IMAG\IMAGE_MMS_ACCESSORY_FILE.png
copy .\mmi_res_128x160\mms\MMI_RES_DEFAULT\IMAG\IMAGE_MMS_NOW_DOWNLOAD_INBOX.png .\mmi_res_all_image\mms\MMI_RES_DEFAULT\IMAG\IMAGE_MMS_NOW_DOWNLOAD_INBOX.png
copy .\mmi_res_128x160\mms\MMI_RES_DEFAULT\IMAG\IMAGE_MMS_NOW_DOWNLOAD_INBOX_LOCK.png .\mmi_res_all_image\mms\MMI_RES_DEFAULT\IMAG\IMAGE_MMS_NOW_DOWNLOAD_INBOX_LOCK.png
copy .\mmi_res_128x160\mms\MMI_RES_DEFAULT\IMAG\IMAGE_MMS_WAITING_DOWNLOAD_INBOX_LOCK.png .\mmi_res_all_image\mms\MMI_RES_DEFAULT\IMAG\IMAGE_MMS_WAITING_DOWNLOAD_INBOX_LOCK.png
copy .\mmi_res_128x160\mms\MMI_RES_DEFAULT\IMAG\IMAGE_MMS_WAITING_DOWNLOAD_INBOX.png .\mmi_res_all_image\mms\MMI_RES_DEFAULT\IMAG\IMAGE_MMS_WAITING_DOWNLOAD_INBOX.png
copy .\mmi_res_128x160\mms\MMI_RES_DEFAULT\IMAG\IMAGE_MMS_COUNT_LBTN_PR.png .\mmi_res_all_image\mms\MMI_RES_DEFAULT\IMAG\IMAGE_MMS_COUNT_LBTN_PR.png
copy .\mmi_res_128x160\mms\MMI_RES_DEFAULT\IMAG\IMAGE_MMS_COUNT_LBTN_UN.png .\mmi_res_all_image\mms\MMI_RES_DEFAULT\IMAG\IMAGE_MMS_COUNT_LBTN_UN.png
copy .\mmi_res_128x160\mms\MMI_RES_DEFAULT\IMAG\IMAGE_MMS_COUNT_RBTN_PR.png .\mmi_res_all_image\mms\MMI_RES_DEFAULT\IMAG\IMAGE_MMS_COUNT_RBTN_PR.png
copy .\mmi_res_128x160\mms\MMI_RES_DEFAULT\IMAG\IMAGE_MMS_COUNT_RBTN_UN.png .\mmi_res_all_image\mms\MMI_RES_DEFAULT\IMAG\IMAGE_MMS_COUNT_RBTN_UN.png
copy .\mmi_res_128x160\sms\MMI_RES_DEFAULT\IMAG\IMAGE_SMS_SIM_SEND_FAIL_SMS_ICON.png .\mmi_res_all_image\sms\MMI_RES_DEFAULT\IMAG\IMAGE_SMS_SIM_SEND_FAIL_SMS_ICON.png
copy .\mmi_res_128x160\sms\MMI_RES_DEFAULT\IMAG\IMAGE_SMS_SIM_READ_SMS_ICON.png .\mmi_res_all_image\sms\MMI_RES_DEFAULT\IMAG\IMAGE_SMS_SIM_READ_SMS_ICON.png
copy .\mmi_res_128x160\sms\MMI_RES_DEFAULT\IMAG\IMAGE_SMS_SIM_NOT_READ_SMS_ICON.png .\mmi_res_all_image\sms\MMI_RES_DEFAULT\IMAG\IMAGE_SMS_SIM_NOT_READ_SMS_ICON.png

copy .\mmi_res_128x160\sms\MMI_RES_DEFAULT\IMAG\IMAGE_SMS_SIM_DRAFT_SMS_ICON.png .\mmi_res_all_image\sms\MMI_RES_DEFAULT\IMAG\IMAGE_SMS_SIM_DRAFT_SMS_ICON.png
copy .\mmi_res_128x160\sms\MMI_RES_DEFAULT\IMAG\IMAGE_SMS_SEND_SUCCESS_SMS_ICON.png .\mmi_res_all_image\sms\MMI_RES_DEFAULT\IMAG\IMAGE_SMS_SEND_SUCCESS_SMS_ICON.png
copy .\mmi_res_128x160\sms\MMI_RES_DEFAULT\IMAG\IMAGE_SMS_SEND_SIM_SUCCESS_SMS_ICON.png .\mmi_res_all_image\sms\MMI_RES_DEFAULT\IMAG\IMAGE_SMS_SEND_SIM_SUCCESS_SMS_ICON.png
copy .\mmi_res_128x160\sms\MMI_RES_DEFAULT\IMAG\IMAGE_SMS_SEND_FAIL_SMS_ICON.png .\mmi_res_all_image\sms\MMI_RES_DEFAULT\IMAG\IMAGE_SMS_SEND_FAIL_SMS_ICON.png
copy .\mmi_res_128x160\sms\MMI_RES_DEFAULT\IMAG\IMAGE_SMS_READ_SMS_ICON.png .\mmi_res_all_image\sms\MMI_RES_DEFAULT\IMAG\IMAGE_SMS_READ_SMS_ICON.png
copy .\mmi_res_128x160\sms\MMI_RES_DEFAULT\IMAG\IMAGE_SMS_NOT_READ_SMS_ICON.png .\mmi_res_all_image\sms\MMI_RES_DEFAULT\IMAG\IMAGE_SMS_NOT_READ_SMS_ICON.png
copy .\mmi_res_128x160\sms\MMI_RES_DEFAULT\IMAG\IMAGE_SMS_MMS_NOTIFY_NEW_ICON.png .\mmi_res_all_image\sms\MMI_RES_DEFAULT\IMAG\IMAGE_SMS_MMS_NOTIFY_NEW_ICON.png
copy .\mmi_res_128x160\sms\MMI_RES_DEFAULT\IMAG\IMAGE_SMS_MMSOTA_ICON.png .\mmi_res_all_image\sms\MMI_RES_DEFAULT\IMAG\IMAGE_SMS_MMSOTA_ICON.png
copy .\mmi_res_128x160\sms\MMI_RES_DEFAULT\IMAG\IMAGE_SMS_MMSOTA_READED_ICON.png .\mmi_res_all_image\sms\MMI_RES_DEFAULT\IMAG\IMAGE_SMS_MMSOTA_READED_ICON.png
copy .\mmi_res_128x160\sms\MMI_RES_DEFAULT\IMAG\IMAGE_SMS_NOT_READ_MMS_ICON.png .\mmi_res_all_image\sms\MMI_RES_DEFAULT\IMAG\IMAGE_SMS_NOT_READ_MMS_ICON.png
copy .\mmi_res_128x160\sms\MMI_RES_DEFAULT\IMAG\IMAGE_SMS_READ_MMS_ICON.png .\mmi_res_all_image\sms\MMI_RES_DEFAULT\IMAG\IMAGE_SMS_READ_MMS_ICON.png
copy .\mmi_res_128x160\sms\MMI_RES_DEFAULT\IMAG\IMAGE_SMS_WAPOTA_ICON.png .\mmi_res_all_image\sms\MMI_RES_DEFAULT\IMAG\IMAGE_SMS_WAPOTA_ICON.png
copy .\mmi_res_128x160\sms\MMI_RES_DEFAULT\IMAG\IMAGE_SMS_TITLE_ICON_FULL_MESSAGE.png .\mmi_res_all_image\sms\MMI_RES_DEFAULT\IMAG\IMAGE_SMS_TITLE_ICON_FULL_MESSAGE.png
copy .\mmi_res_128x160\sms\MMI_RES_DEFAULT\IMAG\IMAGE_SMS_WAPOTA_READED_ICON.png .\mmi_res_all_image\sms\MMI_RES_DEFAULT\IMAG\IMAGE_SMS_WAPOTA_READED_ICON.png
copy .\mmi_res_128x160\sms\MMI_RES_DEFAULT\IMAG\IMAGE_SMS_WAPPUSH_ICON.png .\mmi_res_all_image\sms\MMI_RES_DEFAULT\IMAG\IMAGE_SMS_WAPPUSH_ICON.png
copy .\mmi_res_128x160\sms\MMI_RES_DEFAULT\IMAG\IMAGE_SMS_WAPPUSH_READED_ICON.png .\mmi_res_all_image\sms\MMI_RES_DEFAULT\IMAG\IMAGE_SMS_WAPPUSH_READED_ICON.png
copy .\mmi_res_128x160\sms\MMI_RES_DEFAULT\IMAG\IMAGE_SMS_LOCK_DRAFT_SMS_ICON.png .\mmi_res_all_image\sms\MMI_RES_DEFAULT\IMAG\IMAGE_SMS_LOCK_DRAFT_SMS_ICON.png
copy .\mmi_res_128x160\sms\MMI_RES_DEFAULT\IMAG\IMAGE_SMS_LOCK_SIM_DRAFT_SMS_ICON.png .\mmi_res_all_image\sms\MMI_RES_DEFAULT\IMAG\IMAGE_SMS_LOCK_SIM_DRAFT_SMS_ICON.png
copy .\mmi_res_128x160\sms\MMI_RES_DEFAULT\IMAG\IMAGE_SMS_LOCK_MMS_NOTIFY_NEW_ICON.png .\mmi_res_all_image\sms\MMI_RES_DEFAULT\IMAG\IMAGE_SMS_LOCK_MMS_NOTIFY_NEW_ICON.png
copy .\mmi_res_128x160\sms\MMI_RES_DEFAULT\IMAG\IMAGE_SMS_LOCK_MMSOTA_ICON.png .\mmi_res_all_image\sms\MMI_RES_DEFAULT\IMAG\IMAGE_SMS_LOCK_MMSOTA_ICON.png
copy .\mmi_res_128x160\sms\MMI_RES_DEFAULT\IMAG\IMAGE_SMS_LOCK_MMSOTA_READED_ICON.png .\mmi_res_all_image\sms\MMI_RES_DEFAULT\IMAG\IMAGE_SMS_LOCK_MMSOTA_READED_ICON.png
copy .\mmi_res_128x160\sms\MMI_RES_DEFAULT\IMAG\IMAGE_SMS_LOCK_NOT_READ_MMS_ICON.png .\mmi_res_all_image\sms\MMI_RES_DEFAULT\IMAG\IMAGE_SMS_LOCK_NOT_READ_MMS_ICON.png
copy .\mmi_res_128x160\sms\MMI_RES_DEFAULT\IMAG\IMAGE_SMS_LOCK_NOT_READ_SMS_ICON.png .\mmi_res_all_image\sms\MMI_RES_DEFAULT\IMAG\IMAGE_SMS_LOCK_NOT_READ_SMS_ICON.png
copy .\mmi_res_128x160\sms\MMI_RES_DEFAULT\IMAG\IMAGE_SMS_LOCK_READ_MMS_ICON.png .\mmi_res_all_image\sms\MMI_RES_DEFAULT\IMAG\IMAGE_SMS_LOCK_READ_MMS_ICON.png
copy .\mmi_res_128x160\sms\MMI_RES_DEFAULT\IMAG\IMAGE_SMS_LOCK_READ_SMS_ICON.png .\mmi_res_all_image\sms\MMI_RES_DEFAULT\IMAG\IMAGE_SMS_LOCK_READ_SMS_ICON.png
copy .\mmi_res_128x160\sms\MMI_RES_DEFAULT\IMAG\IMAGE_SMS_LOCK_SEND_FAIL_SMS_ICON.png .\mmi_res_all_image\sms\MMI_RES_DEFAULT\IMAG\IMAGE_SMS_LOCK_SEND_FAIL_SMS_ICON.png
copy .\mmi_res_128x160\sms\MMI_RES_DEFAULT\IMAG\IMAGE_SMS_LOCK_SEND_SIM_SUCCESS_SMS_ICON.png .\mmi_res_all_image\sms\MMI_RES_DEFAULT\IMAG\IMAGE_SMS_LOCK_SEND_SIM_SUCCESS_SMS_ICON.png
copy .\mmi_res_128x160\sms\MMI_RES_DEFAULT\IMAG\IMAGE_SMS_LOCK_SEND_SUCCESS_SMS_ICON.png .\mmi_res_all_image\sms\MMI_RES_DEFAULT\IMAG\IMAGE_SMS_LOCK_SEND_SUCCESS_SMS_ICON.png
copy .\mmi_res_128x160\sms\MMI_RES_DEFAULT\IMAG\IMAGE_SMS_LOCK_SIM_NOT_READ_SMS_ICON.png .\mmi_res_all_image\sms\MMI_RES_DEFAULT\IMAG\IMAGE_SMS_LOCK_SIM_NOT_READ_SMS_ICON.png
copy .\mmi_res_128x160\sms\MMI_RES_DEFAULT\IMAG\IMAGE_SMS_LOCK_SIM_READ_SMS_ICON.png .\mmi_res_all_image\sms\MMI_RES_DEFAULT\IMAG\IMAGE_SMS_LOCK_SIM_READ_SMS_ICON.png
copy .\mmi_res_128x160\sms\MMI_RES_DEFAULT\IMAG\IMAGE_SMS_LOCK_SIM_SEND_FAIL_SMS_ICON.png .\mmi_res_all_image\sms\MMI_RES_DEFAULT\IMAG\IMAGE_SMS_LOCK_SIM_SEND_FAIL_SMS_ICON.png
copy .\mmi_res_128x160\sms\MMI_RES_DEFAULT\IMAG\IMAGE_SMS_LOCK_WAPOTA_ICON.png .\mmi_res_all_image\sms\MMI_RES_DEFAULT\IMAG\IMAGE_SMS_LOCK_WAPOTA_ICON.png
copy .\mmi_res_128x160\sms\MMI_RES_DEFAULT\IMAG\IMAGE_SMS_LOCK_WAPOTA_READED_ICON.png .\mmi_res_all_image\sms\MMI_RES_DEFAULT\IMAG\IMAGE_SMS_LOCK_WAPOTA_READED_ICON.png
copy .\mmi_res_128x160\sms\MMI_RES_DEFAULT\IMAG\IMAGE_SMS_LOCK_WAPPUSH_ICON.png .\mmi_res_all_image\sms\MMI_RES_DEFAULT\IMAG\IMAGE_SMS_LOCK_WAPPUSH_ICON.png
copy .\mmi_res_128x160\sms\MMI_RES_DEFAULT\IMAG\IMAGE_SMS_LOCK_WAPPUSH_READED_ICON.png .\mmi_res_all_image\sms\MMI_RES_DEFAULT\IMAG\IMAGE_SMS_LOCK_WAPPUSH_READED_ICON.png
copy .\mmi_res_128x160\sms\MMI_RES_DEFAULT\IMAG\IMAGE_SMS_DRAFTBOX_TAB_OFF_ICON.png .\mmi_res_all_image\sms\MMI_RES_DEFAULT\IMAG\IMAGE_SMS_DRAFTBOX_TAB_OFF_ICON.png
copy .\mmi_res_128x160\sms\MMI_RES_DEFAULT\IMAG\IMAGE_SMS_INBOX_TAB_OFF_ICON.png .\mmi_res_all_image\sms\MMI_RES_DEFAULT\IMAG\IMAGE_SMS_INBOX_TAB_OFF_ICON.png
copy .\mmi_res_128x160\sms\MMI_RES_DEFAULT\IMAG\IMAGE_SMS_SENDFAILBOX_TAB_OFF_ICON.png .\mmi_res_all_image\sms\MMI_RES_DEFAULT\IMAG\IMAGE_SMS_SENDFAILBOX_TAB_OFF_ICON.png
copy .\mmi_res_128x160\sms\MMI_RES_DEFAULT\IMAG\IMAGE_SMS_SENDSUCCBOX_TAB_OFF_ICON.png .\mmi_res_all_image\sms\MMI_RES_DEFAULT\IMAG\IMAGE_SMS_SENDSUCCBOX_TAB_OFF_ICON.png
copy .\mmi_res_128x160\sms\MMI_RES_DEFAULT\IMAG\IMAGE_SMS_DRAFTBOX_TAB_ON_ICON.png .\mmi_res_all_image\sms\MMI_RES_DEFAULT\IMAG\IMAGE_SMS_DRAFTBOX_TAB_ON_ICON.png
copy .\mmi_res_128x160\sms\MMI_RES_DEFAULT\IMAG\IMAGE_SMS_INBOX_TAB_ON_ICON.png .\mmi_res_all_image\sms\MMI_RES_DEFAULT\IMAG\IMAGE_SMS_INBOX_TAB_ON_ICON.png
copy .\mmi_res_128x160\sms\MMI_RES_DEFAULT\IMAG\IMAGE_SMS_SENDFAILBOX_TAB_ON_ICON.png .\mmi_res_all_image\sms\MMI_RES_DEFAULT\IMAG\IMAGE_SMS_SENDFAILBOX_TAB_ON_ICON.png
copy .\mmi_res_128x160\sms\MMI_RES_DEFAULT\IMAG\IMAGE_SMS_SENDSUCCBOX_TAB_ON_ICON.png .\mmi_res_all_image\sms\MMI_RES_DEFAULT\IMAG\IMAGE_SMS_SENDSUCCBOX_TAB_ON_ICON.png
copy .\mmi_res_128x160\sms\MMI_RES_DEFAULT\IMAG\IMAGE_SMS_EDIT_TO.png .\mmi_res_all_image\sms\MMI_RES_DEFAULT\IMAG\IMAGE_SMS_EDIT_TO.png
copy .\mmi_res_128x160\sms\MMI_RES_DEFAULT\IMAG\IMAGE_SMS_CHAT_DEFAULT.png .\mmi_res_all_image\sms\MMI_RES_DEFAULT\IMAG\IMAGE_SMS_CHAT_DEFAULT.png
copy .\mmi_res_128x160\sms\MMI_RES_DEFAULT\IMAG\IMAGE_SMS_SIM_CARD1.png .\mmi_res_all_image\sms\MMI_RES_DEFAULT\IMAG\IMAGE_SMS_SIM_CARD1.png
copy .\mmi_res_128x160\sms\MMI_RES_DEFAULT\IMAG\IMAGE_SMS_SIM_CARD2.png .\mmi_res_all_image\sms\MMI_RES_DEFAULT\IMAG\IMAGE_SMS_SIM_CARD2.png
copy .\mmi_res_128x160\sms\MMI_RES_DEFAULT\IMAG\IMAGE_SMS_SIM_CARD3.png .\mmi_res_all_image\sms\MMI_RES_DEFAULT\IMAG\IMAGE_SMS_SIM_CARD3.png
copy .\mmi_res_128x160\sms\MMI_RES_DEFAULT\IMAG\IMAGE_SETTING_SMS_TAB_ON_ICON.png .\mmi_res_all_image\sms\MMI_RES_DEFAULT\IMAG\IMAGE_SETTING_SMS_TAB_ON_ICON.png
copy .\mmi_res_128x160\sms\MMI_RES_DEFAULT\IMAG\IMAGE_SETTING_SMS_TAB_OFF_ICON.png .\mmi_res_all_image\sms\MMI_RES_DEFAULT\IMAG\IMAGE_SETTING_SMS_TAB_OFF_ICON.png
copy .\mmi_res_128x160\sms\MMI_RES_DEFAULT\IMAG\IMAGE_SETTING_PUSH_TAB_ON_ICON.png .\mmi_res_all_image\sms\MMI_RES_DEFAULT\IMAG\IMAGE_SETTING_PUSH_TAB_ON_ICON.png
copy .\mmi_res_128x160\sms\MMI_RES_DEFAULT\IMAG\IMAGE_SETTING_PUSH_TAB_OFF_ICON.png .\mmi_res_all_image\sms\MMI_RES_DEFAULT\IMAG\IMAGE_SETTING_PUSH_TAB_OFF_ICON.png
copy .\mmi_res_128x160\sms\MMI_RES_DEFAULT\IMAG\IMAGE_SETTING_MMS_TAB_ON_ICON.png .\mmi_res_all_image\sms\MMI_RES_DEFAULT\IMAG\IMAGE_SETTING_MMS_TAB_ON_ICON.png
copy .\mmi_res_128x160\sms\MMI_RES_DEFAULT\IMAG\IMAGE_SETTING_MMS_TAB_OFF_ICON.png .\mmi_res_all_image\sms\MMI_RES_DEFAULT\IMAG\IMAGE_SETTING_MMS_TAB_OFF_ICON.png






copy .\mmi_res_128x160\fm\MMI_RES_DEFAULT\IMAG\IMAGE_FM_ADJ_BG.png .\mmi_res_all_image\fm\MMI_RES_DEFAULT\IMAG\IMAGE_FM_ADJ_BG.png
copy .\mmi_res_128x160\fm\MMI_RES_DEFAULT\IMAG\IMAGE_FM_ADJ_BUT.png .\mmi_res_all_image\fm\MMI_RES_DEFAULT\IMAG\IMAGE_FM_ADJ_BUT.png
copy .\mmi_res_128x160\fm\MMI_RES_DEFAULT\IMAG\IMAGE_FM_LEFT_DEFAULT.png .\mmi_res_all_image\fm\MMI_RES_DEFAULT\IMAG\IMAGE_FM_LEFT_DEFAULT.png
copy .\mmi_res_128x160\fm\MMI_RES_DEFAULT\IMAG\IMAGE_FM_LEFT_DISABLED.png .\mmi_res_all_image\fm\MMI_RES_DEFAULT\IMAG\IMAGE_FM_LEFT_DISABLED.png
copy .\mmi_res_128x160\fm\MMI_RES_DEFAULT\IMAG\IMAGE_FM_LEFT_PRESSED.png .\mmi_res_all_image\fm\MMI_RES_DEFAULT\IMAG\IMAGE_FM_LEFT_PRESSED.png
copy .\mmi_res_128x160\fm\MMI_RES_DEFAULT\IMAG\IMAGE_FM_PAUSE_DEFAULT.png .\mmi_res_all_image\fm\MMI_RES_DEFAULT\IMAG\IMAGE_FM_PAUSE_DEFAULT.png
copy .\mmi_res_128x160\fm\MMI_RES_DEFAULT\IMAG\IMAGE_FM_PAUSE_DISABLED.png .\mmi_res_all_image\fm\MMI_RES_DEFAULT\IMAG\IMAGE_FM_PAUSE_DISABLED.png
copy .\mmi_res_128x160\fm\MMI_RES_DEFAULT\IMAG\IMAGE_FM_PAUSE_PRESSED.png .\mmi_res_all_image\fm\MMI_RES_DEFAULT\IMAG\IMAGE_FM_PAUSE_PRESSED.png
copy .\mmi_res_128x160\fm\MMI_RES_DEFAULT\IMAG\IMAGE_FM_PLAY_DEFAULT.png .\mmi_res_all_image\fm\MMI_RES_DEFAULT\IMAG\IMAGE_FM_PLAY_DEFAULT.png
copy .\mmi_res_128x160\fm\MMI_RES_DEFAULT\IMAG\IMAGE_FM_PLAY_PRESSED.png .\mmi_res_all_image\fm\MMI_RES_DEFAULT\IMAG\IMAGE_FM_PLAY_PRESSED.png
copy .\mmi_res_128x160\fm\MMI_RES_DEFAULT\IMAG\IMAGE_FM_RIGHT_DEFAULT.png .\mmi_res_all_image\fm\MMI_RES_DEFAULT\IMAG\IMAGE_FM_RIGHT_DEFAULT.png
copy .\mmi_res_128x160\fm\MMI_RES_DEFAULT\IMAG\IMAGE_FM_RIGHT_DISABLED.png .\mmi_res_all_image\fm\MMI_RES_DEFAULT\IMAG\IMAGE_FM_RIGHT_DISABLED.png
copy .\mmi_res_128x160\fm\MMI_RES_DEFAULT\IMAG\IMAGE_FM_RIGHT_PRESSED.png .\mmi_res_all_image\fm\MMI_RES_DEFAULT\IMAG\IMAGE_FM_RIGHT_PRESSED.png











copy .\mmi_res_128x160\fm\MMI_RES_DEFAULT\IMAG\IMAGE_FM_ADJ_BG.png .\mmi_res_all_image\fm\MMI_RES_DEFAULT\IMAG\IMAGE_FM_ADJ_BG.png
copy .\mmi_res_128x160\fm\MMI_RES_DEFAULT\IMAG\IMAGE_FM_ADJ_BUT.png .\mmi_res_all_image\fm\MMI_RES_DEFAULT\IMAG\IMAGE_FM_ADJ_BUT.png
copy .\mmi_res_128x160\fm\MMI_RES_DEFAULT\IMAG\IMAGE_FM_LEFT_DEFAULT.png .\mmi_res_all_image\fm\MMI_RES_DEFAULT\IMAG\IMAGE_FM_LEFT_DEFAULT.png
copy .\mmi_res_128x160\fm\MMI_RES_DEFAULT\IMAG\IMAGE_FM_PAUSE_DEFAULT.png .\mmi_res_all_image\fm\MMI_RES_DEFAULT\IMAG\IMAGE_FM_PAUSE_DEFAULT.png
copy .\mmi_res_128x160\fm\MMI_RES_DEFAULT\IMAG\IMAGE_FM_PLAY_DEFAULT.png .\mmi_res_all_image\fm\MMI_RES_DEFAULT\IMAG\IMAGE_FM_PLAY_DEFAULT.png
copy .\mmi_res_128x160\fm\MMI_RES_DEFAULT\IMAG\IMAGE_FM_RIGHT_DEFAULT.png .\mmi_res_all_image\fm\MMI_RES_DEFAULT\IMAG\IMAGE_FM_RIGHT_DEFAULT.png









copy .\mmi_res_128x160\multim\MMI_RES_DEFAULT\IMAG\IMAGE_MULTIM_BTN_BG.png .\mmi_res_all_image\multim\MMI_RES_DEFAULT\IMAG\IMAGE_MULTIM_BTN_BG.png




copy .\mmi_res_128x160\multim\MMI_RES_DEFAULT\IMAG\IMAGE_MULTIM_BTN_LIST_DEFAULT.png .\mmi_res_all_image\multim\MMI_RES_DEFAULT\IMAG\IMAGE_MULTIM_BTN_LIST_DEFAULT.png
copy .\mmi_res_128x160\multim\MMI_RES_DEFAULT\IMAG\IMAGE_MULTIM_BTN_OPTION_DISABLED.png .\mmi_res_all_image\multim\MMI_RES_DEFAULT\IMAG\IMAGE_MULTIM_BTN_OPTION_DISABLED.png
copy .\mmi_res_128x160\multim\MMI_RES_DEFAULT\IMAG\IMAGE_MULTIM_BTN_PRESS.png .\mmi_res_all_image\multim\MMI_RES_DEFAULT\IMAG\IMAGE_MULTIM_BTN_PRESS.png
copy .\mmi_res_128x160\multim\MMI_RES_DEFAULT\IMAG\IMAGE_MULTIM_TITLE_BTN_PRESS.png .\mmi_res_all_image\multim\MMI_RES_DEFAULT\IMAG\IMAGE_MULTIM_TITLE_BTN_PRESS.png
copy .\mmi_res_128x160\multim\MMI_RES_DEFAULT\IMAG\IMAGE_MULTIM_BTN_REPEAT_DISABLED.png .\mmi_res_all_image\multim\MMI_RES_DEFAULT\IMAG\IMAGE_MULTIM_BTN_REPEAT_DISABLED.png
copy .\mmi_res_128x160\multim\MMI_RES_DEFAULT\IMAG\IMAGE_MULTIM_BTN_RECORD_DEFAULT.png .\mmi_res_all_image\multim\MMI_RES_DEFAULT\IMAG\IMAGE_MULTIM_BTN_RECORD_DEFAULT.png

copy .\mmi_res_128x160\multim\MMI_RES_DEFAULT\IMAG\IMAGE_MULTIM_BTN_SHUFFLE_DISABLED.png .\mmi_res_all_image\multim\MMI_RES_DEFAULT\IMAG\IMAGE_MULTIM_BTN_SHUFFLE_DISABLED.png
copy .\mmi_res_128x160\multim\MMI_RES_DEFAULT\IMAG\IMAGE_MULTIM_MODE_BTN_BG.png .\mmi_res_all_image\multim\MMI_RES_DEFAULT\IMAG\IMAGE_MULTIM_MODE_BTN_BG.png
copy .\mmi_res_128x160\multim\MMI_RES_DEFAULT\IMAG\IMAGE_MULTIM_BTN_VOL_DEFAULT.png .\mmi_res_all_image\multim\MMI_RES_DEFAULT\IMAG\IMAGE_MULTIM_BTN_VOL_DEFAULT.png
copy .\mmi_res_128x160\multim\MMI_RES_DEFAULT\IMAG\IMAGE_MULTIM_BTN_VOL_DISABLED.png .\mmi_res_all_image\multim\MMI_RES_DEFAULT\IMAG\IMAGE_MULTIM_BTN_VOL_DISABLED.png
copy .\mmi_res_128x160\multim\MMI_RES_DEFAULT\IMAG\IMAGE_MULTIM_BTN_VOL_MUTE_DEFAULT.png .\mmi_res_all_image\multim\MMI_RES_DEFAULT\IMAG\IMAGE_MULTIM_BTN_VOL_MUTE_DEFAULT.png
copy .\mmi_res_128x160\multim\MMI_RES_DEFAULT\IMAG\IMAGE_MULTIM_BTN_VOL_MUTE_DISABLED.png .\mmi_res_all_image\multim\MMI_RES_DEFAULT\IMAG\IMAGE_MULTIM_BTN_VOL_MUTE_DISABLED.png
copy .\mmi_res_128x160\multim\MMI_RES_DEFAULT\IMAG\IMAGE_MULTIM_BTN_LIST_PRESSED.png .\mmi_res_all_image\multim\MMI_RES_DEFAULT\IMAG\IMAGE_MULTIM_BTN_LIST_PRESSED.png
copy .\mmi_res_128x160\multim\MMI_RES_DEFAULT\IMAG\IMAGE_MULTIM_BTN_VOL_PRESSED.png .\mmi_res_all_image\multim\MMI_RES_DEFAULT\IMAG\IMAGE_MULTIM_BTN_VOL_PRESSED.png
copy .\mmi_res_128x160\multim\MMI_RES_DEFAULT\IMAG\IMAGE_MULTIM_BTN_VOL_MUTE_PRESSED.png .\mmi_res_all_image\multim\MMI_RES_DEFAULT\IMAG\IMAGE_MULTIM_BTN_VOL_MUTE_PRESSED.png
copy .\mmi_res_128x160\multim\MMI_RES_DEFAULT\IMAG\IMAGE_MULTIM_PROCESSBAR_BG.png .\mmi_res_all_image\multim\MMI_RES_DEFAULT\IMAG\IMAGE_MULTIM_PROCESSBAR_BG.png
copy .\mmi_res_128x160\multim\MMI_RES_DEFAULT\IMAG\IMAGE_MULTIM_BTN_SHUFFLE_OFF_DISABLED.png .\mmi_res_all_image\multim\MMI_RES_DEFAULT\IMAG\IMAGE_MULTIM_BTN_SHUFFLE_OFF_DISABLED.png
copy .\mmi_res_128x160\multim\MMI_RES_DEFAULT\IMAG\IMAGE_MULTIM_BTN_LIST_DISABLED.png .\mmi_res_all_image\multim\MMI_RES_DEFAULT\IMAG\IMAGE_MULTIM_BTN_LIST_DISABLED.png
copy .\mmi_res_128x160\multim\MMI_RES_DEFAULT\IMAG\IMAGE_MULTIM_BTN_OPTION_DEFAULT.png .\mmi_res_all_image\multim\MMI_RES_DEFAULT\IMAG\IMAGE_MULTIM_BTN_OPTION_DEFAULT.png
copy .\mmi_res_128x160\multim\MMI_RES_DEFAULT\IMAG\IMAGE_MULTIM_RECORD_TIP.bmp .\mmi_res_all_image\multim\MMI_RES_DEFAULT\IMAG\IMAGE_MULTIM_RECORD_TIP.bmp
copy .\mmi_res_128x160\multim\MMI_RES_DEFAULT\IMAG\IMAGE_MULTIM_BTN_RETURN_DEFAULT.png .\mmi_res_all_image\multim\MMI_RES_DEFAULT\IMAG\IMAGE_MULTIM_BTN_RETURN_DEFAULT.png
copy .\mmi_res_128x160\multim\MMI_RES_DEFAULT\IMAG\IMAGE_MULTIM_MODE_BTN_PRESS.png .\mmi_res_all_image\multim\MMI_RES_DEFAULT\IMAG\IMAGE_MULTIM_MODE_BTN_PRESS.png
copy .\mmi_res_128x160\multim\MMI_RES_DEFAULT\IMAG\IMAGE_MULTIM_BTN_NEXT_DEFAULT.png .\mmi_res_all_image\multim\MMI_RES_DEFAULT\IMAG\IMAGE_MULTIM_BTN_NEXT_DEFAULT.png
copy .\mmi_res_128x160\multim\MMI_RES_DEFAULT\IMAG\IMAGE_MULTIM_BTN_NEXT_DISABLED.png .\mmi_res_all_image\multim\MMI_RES_DEFAULT\IMAG\IMAGE_MULTIM_BTN_NEXT_DISABLED.png
copy .\mmi_res_128x160\multim\MMI_RES_DEFAULT\IMAG\IMAGE_MULTIM_BTN_PAUSE_DEFAULT.png .\mmi_res_all_image\multim\MMI_RES_DEFAULT\IMAG\IMAGE_MULTIM_BTN_PAUSE_DEFAULT.png
copy .\mmi_res_128x160\multim\MMI_RES_DEFAULT\IMAG\IMAGE_MULTIM_BTN_PAUSE_DISABLED.png .\mmi_res_all_image\multim\MMI_RES_DEFAULT\IMAG\IMAGE_MULTIM_BTN_PAUSE_DISABLED.png
copy .\mmi_res_128x160\multim\MMI_RES_DEFAULT\IMAG\IMAGE_MULTIM_BTN_PLAY_DEFAULT.png .\mmi_res_all_image\multim\MMI_RES_DEFAULT\IMAG\IMAGE_MULTIM_BTN_PLAY_DEFAULT.png
copy .\mmi_res_128x160\multim\MMI_RES_DEFAULT\IMAG\IMAGE_MULTIM_BTN_PLAY_DISABLED.png .\mmi_res_all_image\multim\MMI_RES_DEFAULT\IMAG\IMAGE_MULTIM_BTN_PLAY_DISABLED.png
copy .\mmi_res_128x160\multim\MMI_RES_DEFAULT\IMAG\IMAGE_MULTIM_BTN_PREV_DEFAULT.png .\mmi_res_all_image\multim\MMI_RES_DEFAULT\IMAG\IMAGE_MULTIM_BTN_PREV_DEFAULT.png
copy .\mmi_res_128x160\multim\MMI_RES_DEFAULT\IMAG\IMAGE_MULTIM_BTN_PREV_DISABLED.png .\mmi_res_all_image\multim\MMI_RES_DEFAULT\IMAG\IMAGE_MULTIM_BTN_PREV_DISABLED.png
copy .\mmi_res_128x160\multim\MMI_RES_DEFAULT\IMAG\IMAGE_MULTIM_BTN_REPEAT_OFF_DEFAULT.png .\mmi_res_all_image\multim\MMI_RES_DEFAULT\IMAG\IMAGE_MULTIM_BTN_REPEAT_OFF_DEFAULT.png
copy .\mmi_res_128x160\multim\MMI_RES_DEFAULT\IMAG\IMAGE_MULTIM_BTN_REPEAT_ON_DEFAULT.png .\mmi_res_all_image\multim\MMI_RES_DEFAULT\IMAG\IMAGE_MULTIM_BTN_REPEAT_ON_DEFAULT.png
copy .\mmi_res_128x160\multim\MMI_RES_DEFAULT\IMAG\IMAGE_MULTIM_BTN_REPEAT_ONE_DEFAULT.png .\mmi_res_all_image\multim\MMI_RES_DEFAULT\IMAG\IMAGE_MULTIM_BTN_REPEAT_ONE_DEFAULT.png
copy .\mmi_res_128x160\multim\MMI_RES_DEFAULT\IMAG\IMAGE_MULTIM_BTN_SHUFFLE_OFF_DEFAULT.png .\mmi_res_all_image\multim\MMI_RES_DEFAULT\IMAG\IMAGE_MULTIM_BTN_SHUFFLE_OFF_DEFAULT.png
copy .\mmi_res_128x160\multim\MMI_RES_DEFAULT\IMAG\IMAGE_MULTIM_BTN_SHUFFLE_ON_DEFAULT.png .\mmi_res_all_image\multim\MMI_RES_DEFAULT\IMAG\IMAGE_MULTIM_BTN_SHUFFLE_ON_DEFAULT.png
copy .\mmi_res_128x160\multim\MMI_RES_DEFAULT\IMAG\IMAGE_MULTIM_BTN_STOP_DEFAULT.png .\mmi_res_all_image\multim\MMI_RES_DEFAULT\IMAG\IMAGE_MULTIM_BTN_STOP_DEFAULT.png
copy .\mmi_res_128x160\multim\MMI_RES_DEFAULT\IMAG\IMAGE_MULTIM_BTN_STOP_DISABLED.png .\mmi_res_all_image\multim\MMI_RES_DEFAULT\IMAG\IMAGE_MULTIM_BTN_STOP_DISABLED.png
copy .\mmi_res_128x160\multim\MMI_RES_DEFAULT\IMAG\IMAGE_MULTIM_PLAYER_PROCESS_GROOVE.png .\mmi_res_all_image\multim\MMI_RES_DEFAULT\IMAG\IMAGE_MULTIM_PLAYER_PROCESS_GROOVE.png
copy .\mmi_res_128x160\multim\MMI_RES_DEFAULT\IMAG\IMAGE_MULTIM_PLAYER_PROCESS.png .\mmi_res_all_image\multim\MMI_RES_DEFAULT\IMAG\IMAGE_MULTIM_PLAYER_PROCESS.png
copy .\mmi_res_128x160\multim\MMI_RES_DEFAULT\IMAG\IMAGE_MULTIM_PLAYER_PROCESS_SLIDE.png .\mmi_res_all_image\multim\MMI_RES_DEFAULT\IMAG\IMAGE_MULTIM_PLAYER_PROCESS_SLIDE.png
copy .\mmi_res_128x160\multim\MMI_RES_DEFAULT\IMAG\IMAGE_MULTIM_BTN_PREV_PRESSED.png .\mmi_res_all_image\multim\MMI_RES_DEFAULT\IMAG\IMAGE_MULTIM_BTN_PREV_PRESSED.png
copy .\mmi_res_128x160\multim\MMI_RES_DEFAULT\IMAG\IMAGE_MULTIM_BTN_PLAY_PRESSED.png .\mmi_res_all_image\multim\MMI_RES_DEFAULT\IMAG\IMAGE_MULTIM_BTN_PLAY_PRESSED.png
copy .\mmi_res_128x160\multim\MMI_RES_DEFAULT\IMAG\IMAGE_MULTIM_BTN_PAUSE_PRESSED.png .\mmi_res_all_image\multim\MMI_RES_DEFAULT\IMAG\IMAGE_MULTIM_BTN_PAUSE_PRESSED.png
copy .\mmi_res_128x160\multim\MMI_RES_DEFAULT\IMAG\IMAGE_MULTIM_BTN_NEXT_PRESSED.png .\mmi_res_all_image\multim\MMI_RES_DEFAULT\IMAG\IMAGE_MULTIM_BTN_NEXT_PRESSED.png
copy .\mmi_res_128x160\multim\MMI_RES_DEFAULT\IMAG\IMAGE_MULTIM_BTN_REPEAT_ON_PRESSED.png .\mmi_res_all_image\multim\MMI_RES_DEFAULT\IMAG\IMAGE_MULTIM_BTN_REPEAT_ON_PRESSED.png
copy .\mmi_res_128x160\multim\MMI_RES_DEFAULT\IMAG\IMAGE_MULTIM_BTN_REPEAT_OFF_PRESSED.png .\mmi_res_all_image\multim\MMI_RES_DEFAULT\IMAG\IMAGE_MULTIM_BTN_REPEAT_OFF_PRESSED.png
copy .\mmi_res_128x160\multim\MMI_RES_DEFAULT\IMAG\IMAGE_MULTIM_BTN_REPEAT_ONE_PRESSED.png .\mmi_res_all_image\multim\MMI_RES_DEFAULT\IMAG\IMAGE_MULTIM_BTN_REPEAT_ONE_PRESSED.png
copy .\mmi_res_128x160\multim\MMI_RES_DEFAULT\IMAG\IMAGE_MULTIM_BTN_SHUFFLE_ON_PRESSED.png .\mmi_res_all_image\multim\MMI_RES_DEFAULT\IMAG\IMAGE_MULTIM_BTN_SHUFFLE_ON_PRESSED.png
copy .\mmi_res_128x160\multim\MMI_RES_DEFAULT\IMAG\IMAGE_MULTIM_BTN_SHUFFLE_OFF_PRESSED.png .\mmi_res_all_image\multim\MMI_RES_DEFAULT\IMAG\IMAGE_MULTIM_BTN_SHUFFLE_OFF_PRESSED.png
copy .\mmi_res_128x160\set\MMI_RES_DEFAULT\IMAG\Contrast_setting\IMAGE_SET_CONTRAST_BAR_FG_NEW.png .\mmi_res_all_image\set\MMI_RES_DEFAULT\IMAG\Contrast_setting\IMAGE_SET_CONTRAST_BAR_FG_NEW.png
copy .\mmi_res_128x160\set\MMI_RES_DEFAULT\IMAG\Contrast_setting\IMAGE_SET_CONTRAST_BAR_BG_NEW.png .\mmi_res_all_image\set\MMI_RES_DEFAULT\IMAG\Contrast_setting\IMAGE_SET_CONTRAST_BAR_BG_NEW.png
copy .\mmi_res_128x160\set\MMI_RES_DEFAULT\IMAG\Contrast_setting\IMAGE_SET_CONTRAST_TRIANGLE_LEFT.png .\mmi_res_all_image\set\MMI_RES_DEFAULT\IMAG\Contrast_setting\IMAGE_SET_CONTRAST_TRIANGLE_LEFT.png
copy .\mmi_res_128x160\set\MMI_RES_DEFAULT\IMAG\Contrast_setting\IMAGE_SET_CONTRAST_TRIANGLE_RIGHT.png .\mmi_res_all_image\set\MMI_RES_DEFAULT\IMAG\Contrast_setting\IMAGE_SET_CONTRAST_TRIANGLE_RIGHT.png
copy .\mmi_res_128x160\set\MMI_RES_DEFAULT\IMAG\Phone_setting\IMAGE_SET_DATE_ICON.png .\mmi_res_all_image\set\MMI_RES_DEFAULT\IMAG\Phone_setting\IMAGE_SET_DATE_ICON.png
copy .\mmi_res_128x160\set\MMI_RES_DEFAULT\IMAG\Phone_setting\IMAGE_SET_TIME_ICON.png .\mmi_res_all_image\set\MMI_RES_DEFAULT\IMAG\Phone_setting\IMAGE_SET_TIME_ICON.png
copy .\mmi_res_128x160\set\MMI_RES_DEFAULT\IMAG\Phone_setting\IMAGE_SET_DIRKEY_LEFT.png .\mmi_res_all_image\set\MMI_RES_DEFAULT\IMAG\Phone_setting\IMAGE_SET_DIRKEY_LEFT.png
copy .\mmi_res_128x160\set\MMI_RES_DEFAULT\IMAG\Phone_setting\IMAGE_SET_DIRKEY_RIGHT.png .\mmi_res_all_image\set\MMI_RES_DEFAULT\IMAG\Phone_setting\IMAGE_SET_DIRKEY_RIGHT.png
copy .\mmi_res_128x160\set\MMI_RES_DEFAULT\IMAG\Phone_setting\IMAGE_SET_SL.png .\mmi_res_all_image\set\MMI_RES_DEFAULT\IMAG\Phone_setting\IMAGE_SET_SL.png
copy .\mmi_res_128x160\set\MMI_RES_DEFAULT\IMAG\Phone_setting\IMAGE_SET_SR.png .\mmi_res_all_image\set\MMI_RES_DEFAULT\IMAG\Phone_setting\IMAGE_SET_SR.png
copy .\mmi_res_128x160\set\MMI_RES_DEFAULT\IMAG\Phone_setting\IMAGE_SET_DIRKEY_UP.png .\mmi_res_all_image\set\MMI_RES_DEFAULT\IMAG\Phone_setting\IMAGE_SET_DIRKEY_UP.png
copy .\mmi_res_128x160\set\MMI_RES_DEFAULT\IMAG\Phone_setting\IMAGE_SET_DIRKEY_DOWN.png .\mmi_res_all_image\set\MMI_RES_DEFAULT\IMAG\Phone_setting\IMAGE_SET_DIRKEY_DOWN.png
copy .\mmi_res_128x160\set\MMI_RES_DEFAULT\IMAG\Call_setting\IMAGE_SET_ALLOWABLE_2G.png .\mmi_res_all_image\set\MMI_RES_DEFAULT\IMAG\Call_setting\IMAGE_SET_ALLOWABLE_2G.png
copy .\mmi_res_128x160\set\MMI_RES_DEFAULT\IMAG\Call_setting\IMAGE_SET_ALLOWABLE_3G.png .\mmi_res_all_image\set\MMI_RES_DEFAULT\IMAG\Call_setting\IMAGE_SET_ALLOWABLE_3G.png
copy .\mmi_res_128x160\set\MMI_RES_DEFAULT\IMAG\Call_setting\IMAGE_SET_FORBIDDEN_2G.png .\mmi_res_all_image\set\MMI_RES_DEFAULT\IMAG\Call_setting\IMAGE_SET_FORBIDDEN_2G.png
copy .\mmi_res_128x160\set\MMI_RES_DEFAULT\IMAG\Call_setting\IMAGE_SET_FORBIDDEN_3G.png .\mmi_res_all_image\set\MMI_RES_DEFAULT\IMAG\Call_setting\IMAGE_SET_FORBIDDEN_3G.png
copy .\mmi_res_128x160\set\MMI_RES_DEFAULT\IMAG\IMAGE_ADJUST_VOL_PLUG.png .\mmi_res_all_image\set\MMI_RES_DEFAULT\IMAG\IMAGE_ADJUST_VOL_PLUG.png
copy .\mmi_res_128x160\set\MMI_RES_DEFAULT\IMAG\IMAGE_ADJUST_VOL_MINUS.png .\mmi_res_all_image\set\MMI_RES_DEFAULT\IMAG\IMAGE_ADJUST_VOL_MINUS.png
copy .\mmi_res_128x160\set\MMI_RES_DEFAULT\IMAG\Phone_setting\IMAGE_SET_IDLE_SHORTCUT1.png .\mmi_res_all_image\set\MMI_RES_DEFAULT\IMAG\Phone_setting\IMAGE_SET_IDLE_SHORTCUT1.png
copy .\mmi_res_128x160\set\MMI_RES_DEFAULT\IMAG\Phone_setting\IMAGE_SET_IDLE_SHORTCUT2.png .\mmi_res_all_image\set\MMI_RES_DEFAULT\IMAG\Phone_setting\IMAGE_SET_IDLE_SHORTCUT2.png
copy .\mmi_res_128x160\set\MMI_RES_DEFAULT\IMAG\Phone_setting\IMAGE_SET_IDLE_SHORTCUT3.png .\mmi_res_all_image\set\MMI_RES_DEFAULT\IMAG\Phone_setting\IMAGE_SET_IDLE_SHORTCUT3.png
copy .\mmi_res_128x160\set\MMI_RES_DEFAULT\IMAG\Phone_setting\IMAGE_SET_IDLE_SHORTCUT4.png .\mmi_res_all_image\set\MMI_RES_DEFAULT\IMAG\Phone_setting\IMAGE_SET_IDLE_SHORTCUT4.png
copy .\mmi_res_128x160\set\MMI_RES_DEFAULT\IMAG\Phone_setting\IMAGE_SET_IDLE_SHORTCUT5.png .\mmi_res_all_image\set\MMI_RES_DEFAULT\IMAG\Phone_setting\IMAGE_SET_IDLE_SHORTCUT5.png
copy .\mmi_res_128x160\set\MMI_RES_DEFAULT\IMAG\IMAGE_SET_THEME1.bmp .\mmi_res_all_image\set\MMI_RES_DEFAULT\IMAG\IMAGE_SET_THEME1.bmp
copy .\mmi_res_128x160\set\MMI_RES_DEFAULT\IMAG\IMAGE_SET_THEME2.bmp .\mmi_res_all_image\set\MMI_RES_DEFAULT\IMAG\IMAGE_SET_THEME2.bmp

copy .\mmi_res_128x160\set\MMI_RES_DEFAULT\IMAG\Phone_setting\IMAGE_SET_BLACKLIST.png .\mmi_res_all_image\set\MMI_RES_DEFAULT\IMAG\Phone_setting\IMAGE_SET_BLACKLIST.png















































copy .\mmi_res_128x160\audioplayer\MMI_RES_DEFAULT\IMAG\Button\IMAGE_AP_BTN_REVIEW_DEFAULT.png .\mmi_res_all_image\audioplayer\MMI_RES_DEFAULT\IMAG\Button\IMAGE_AP_BTN_REVIEW_DEFAULT.png
copy .\mmi_res_128x160\audioplayer\MMI_RES_DEFAULT\IMAG\Button\IMAGE_AP_BTN_REVIEW_DISABLED.png .\mmi_res_all_image\audioplayer\MMI_RES_DEFAULT\IMAG\Button\IMAGE_AP_BTN_REVIEW_DISABLED.png
copy .\mmi_res_128x160\audioplayer\MMI_RES_DEFAULT\IMAG\Button\IMAGE_AP_BTN_REVIEW_PLAY_DEFAULT.png .\mmi_res_all_image\audioplayer\MMI_RES_DEFAULT\IMAG\Button\IMAGE_AP_BTN_REVIEW_PLAY_DEFAULT.png
copy .\mmi_res_128x160\audioplayer\MMI_RES_DEFAULT\IMAG\Button\IMAGE_AP_BTN_REVIEW_SET_DEFAULT.png .\mmi_res_all_image\audioplayer\MMI_RES_DEFAULT\IMAG\Button\IMAGE_AP_BTN_REVIEW_SET_DEFAULT.png
copy .\mmi_res_128x160\audioplayer\MMI_RES_DEFAULT\IMAG\Button\IMAGE_AP_BTN_REVIEW_START_DEFAULT.png .\mmi_res_all_image\audioplayer\MMI_RES_DEFAULT\IMAG\Button\IMAGE_AP_BTN_REVIEW_START_DEFAULT.png
copy .\mmi_res_128x160\audioplayer\MMI_RES_DEFAULT\IMAG\Button\IMAGE_AP_BTN_REVIEW_STOP_DEFAULT.png .\mmi_res_all_image\audioplayer\MMI_RES_DEFAULT\IMAG\Button\IMAGE_AP_BTN_REVIEW_STOP_DEFAULT.png
copy .\mmi_res_128x160\audioplayer\MMI_RES_DEFAULT\IMAG\Button\IMAGE_AP_BTN_REVIEW_CANCEL_DEFAULT.png .\mmi_res_all_image\audioplayer\MMI_RES_DEFAULT\IMAG\Button\IMAGE_AP_BTN_REVIEW_CANCEL_DEFAULT.png
copy .\mmi_res_128x160\audioplayer\MMI_RES_DEFAULT\IMAG\Button\IMAGE_AP_BTN_REVIEW_PRESSED.png .\mmi_res_all_image\audioplayer\MMI_RES_DEFAULT\IMAG\Button\IMAGE_AP_BTN_REVIEW_PRESSED.png
copy .\mmi_res_128x160\audioplayer\MMI_RES_DEFAULT\IMAG\Button\IMAGE_AP_BTN_REVIEW_PLAY_PRESSED.png .\mmi_res_all_image\audioplayer\MMI_RES_DEFAULT\IMAG\Button\IMAGE_AP_BTN_REVIEW_PLAY_PRESSED.png
copy .\mmi_res_128x160\audioplayer\MMI_RES_DEFAULT\IMAG\Button\IMAGE_AP_BTN_REVIEW_SET_PRESSED.png .\mmi_res_all_image\audioplayer\MMI_RES_DEFAULT\IMAG\Button\IMAGE_AP_BTN_REVIEW_SET_PRESSED.png
copy .\mmi_res_128x160\audioplayer\MMI_RES_DEFAULT\IMAG\Pda\IMAGE_AP_ALBUM_BG.png .\mmi_res_all_image\audioplayer\MMI_RES_DEFAULT\IMAG\Pda\IMAGE_AP_ALBUM_BG.png
copy .\mmi_res_128x160\audioplayer\MMI_RES_DEFAULT\IMAG\Pda\IMAGE_AP_DEFAULT_ALBUM_IMG_BRIGHT.png .\mmi_res_all_image\audioplayer\MMI_RES_DEFAULT\IMAG\Pda\IMAGE_AP_DEFAULT_ALBUM_IMG_BRIGHT.png
copy .\mmi_res_128x160\audioplayer\MMI_RES_DEFAULT\IMAG\Pda\IMAGE_AP_TITLE_BG_BRIGHT.png .\mmi_res_all_image\audioplayer\MMI_RES_DEFAULT\IMAG\Pda\IMAGE_AP_TITLE_BG_BRIGHT.png
copy .\mmi_res_128x160\audioplayer\MMI_RES_DEFAULT\IMAG\Pda\IMAGE_AP_OSD_BG_DOWN.png .\mmi_res_all_image\audioplayer\MMI_RES_DEFAULT\IMAG\Pda\IMAGE_AP_OSD_BG_DOWN.png
copy .\mmi_res_128x160\audioplayer\MMI_RES_DEFAULT\IMAG\Pda\IMAGE_AP_OSD_BG_UP.png .\mmi_res_all_image\audioplayer\MMI_RES_DEFAULT\IMAG\Pda\IMAGE_AP_OSD_BG_UP.png
copy .\mmi_res_128x160\audioplayer\MMI_RES_DEFAULT\IMAG\Pda\IMAGE_AP_PROCESS_REVIEW.png .\mmi_res_all_image\audioplayer\MMI_RES_DEFAULT\IMAG\Pda\IMAGE_AP_PROCESS_REVIEW.png
copy .\mmi_res_128x160\audioplayer\MMI_RES_DEFAULT\IMAG\Pda\IMAGE_AP_PROCESS_SLIDE_REVIEW.png .\mmi_res_all_image\audioplayer\MMI_RES_DEFAULT\IMAG\Pda\IMAGE_AP_PROCESS_SLIDE_REVIEW.png
copy .\mmi_res_128x160\audioplayer\MMI_RES_DEFAULT\IMAG\Icon\IMAGE_MP3_ALL_MUSIC_ICON.png .\mmi_res_all_image\audioplayer\MMI_RES_DEFAULT\IMAG\Icon\IMAGE_MP3_ALL_MUSIC_ICON.png
copy .\mmi_res_128x160\audioplayer\MMI_RES_DEFAULT\IMAG\Icon\IMAGE_MP3_FILE_SD_ICON.png .\mmi_res_all_image\audioplayer\MMI_RES_DEFAULT\IMAG\Icon\IMAGE_MP3_FILE_SD_ICON.png
copy .\mmi_res_128x160\audioplayer\MMI_RES_DEFAULT\IMAG\Icon\IMAGE_MP3_FILE_UDISK_ICON.png .\mmi_res_all_image\audioplayer\MMI_RES_DEFAULT\IMAG\Icon\IMAGE_MP3_FILE_UDISK_ICON.png
copy .\mmi_res_128x160\audioplayer\MMI_RES_DEFAULT\IMAG\Icon\IMAGE_MP3_LIST_SD_ICON.png .\mmi_res_all_image\audioplayer\MMI_RES_DEFAULT\IMAG\Icon\IMAGE_MP3_LIST_SD_ICON.png
copy .\mmi_res_128x160\audioplayer\MMI_RES_DEFAULT\IMAG\Icon\IMAGE_MP3_LIST_UDISK_ICON.png .\mmi_res_all_image\audioplayer\MMI_RES_DEFAULT\IMAG\Icon\IMAGE_MP3_LIST_UDISK_ICON.png
copy .\mmi_res_128x160\audioplayer\MMI_RES_DEFAULT\IMAG\Icon\IMAGE_MP3_MUSIC_PLAYING_ICON.png .\mmi_res_all_image\audioplayer\MMI_RES_DEFAULT\IMAG\Icon\IMAGE_MP3_MUSIC_PLAYING_ICON.png
copy .\mmi_res_128x160\cc\MMI_RES_DEFAULT\IMAG\cc\IAMGE_CALL_DEFAULT_PHOTO.png .\mmi_res_all_image\cc\MMI_RES_DEFAULT\IMAG\cc\IAMGE_CALL_DEFAULT_PHOTO.png
copy .\mmi_res_128x160\cc\MMI_RES_DEFAULT\IMAG\cc\Optionsmenu_icon\IMAGE_CC_OPTMENU_H_AND_ANSWER.png .\mmi_res_all_image\cc\MMI_RES_DEFAULT\IMAG\cc\Optionsmenu_icon\IMAGE_CC_OPTMENU_H_AND_ANSWER.png
copy .\mmi_res_128x160\cc\MMI_RES_DEFAULT\IMAG\cc\IMAGE_CC_COMMON_BG_PDA.png .\mmi_res_all_image\cc\MMI_RES_DEFAULT\IMAG\cc\IMAGE_CC_COMMON_BG_PDA.png
copy .\mmi_res_128x160\cc\MMI_RES_DEFAULT\IMAG\cc\IMAGE_CC_BTN_OPTION.png .\mmi_res_all_image\cc\MMI_RES_DEFAULT\IMAG\cc\IMAGE_CC_BTN_OPTION.png
copy .\mmi_res_128x160\cc\MMI_RES_DEFAULT\IMAG\cc\IMAGE_CC_BTN_OPTION_FOCUS.png .\mmi_res_all_image\cc\MMI_RES_DEFAULT\IMAG\cc\IMAGE_CC_BTN_OPTION_FOCUS.png
copy .\mmi_res_128x160\cc\MMI_RES_DEFAULT\IMAG\callog\IMAGE_CL_DIALED_CALL_ICON.png .\mmi_res_all_image\cc\MMI_RES_DEFAULT\IMAG\callog\IMAGE_CL_DIALED_CALL_ICON.png
copy .\mmi_res_128x160\cc\MMI_RES_DEFAULT\IMAG\callog\IMAGE_CL_MISSED_CALL_ICON.png .\mmi_res_all_image\cc\MMI_RES_DEFAULT\IMAG\callog\IMAGE_CL_MISSED_CALL_ICON.png
copy .\mmi_res_128x160\cc\MMI_RES_DEFAULT\IMAG\callog\IMAGE_CL_RECEIVED_CALL_ICON.png .\mmi_res_all_image\cc\MMI_RES_DEFAULT\IMAG\callog\IMAGE_CL_RECEIVED_CALL_ICON.png
copy .\mmi_res_128x160\cc\MMI_RES_DEFAULT\IMAG\callog\IMAGE_CL_REFUSED_CALL_ICON.png .\mmi_res_all_image\cc\MMI_RES_DEFAULT\IMAG\callog\IMAGE_CL_REFUSED_CALL_ICON.png
copy .\mmi_res_128x160\cc\MMI_RES_DEFAULT\IMAG\callog\IMAGE_CL_SOS_CALL_ICON.png .\mmi_res_all_image\cc\MMI_RES_DEFAULT\IMAG\callog\IMAGE_CL_SOS_CALL_ICON.png
copy .\mmi_res_128x160\cc\MMI_RES_DEFAULT\IMAG\callog\IMAGE_CL_DIALED_RELEASED.png .\mmi_res_all_image\cc\MMI_RES_DEFAULT\IMAG\callog\IMAGE_CL_DIALED_RELEASED.png
copy .\mmi_res_128x160\cc\MMI_RES_DEFAULT\IMAG\callog\IMAGE_CL_MISSED_RELEASED.png .\mmi_res_all_image\cc\MMI_RES_DEFAULT\IMAG\callog\IMAGE_CL_MISSED_RELEASED.png
copy .\mmi_res_128x160\cc\MMI_RES_DEFAULT\IMAG\callog\IMAGE_CL_RECEIVED_RELEASED.png .\mmi_res_all_image\cc\MMI_RES_DEFAULT\IMAG\callog\IMAGE_CL_RECEIVED_RELEASED.png
copy .\mmi_res_128x160\cc\MMI_RES_DEFAULT\IMAG\callog\IMAGE_CL_REFUSED_RELEASED.png .\mmi_res_all_image\cc\MMI_RES_DEFAULT\IMAG\callog\IMAGE_CL_REFUSED_RELEASED.png
copy .\mmi_res_128x160\cc\MMI_RES_DEFAULT\IMAG\callog\IMAGE_CL_DIALED_SELECTED.png .\mmi_res_all_image\cc\MMI_RES_DEFAULT\IMAG\callog\IMAGE_CL_DIALED_SELECTED.png
copy .\mmi_res_128x160\cc\MMI_RES_DEFAULT\IMAG\callog\IMAGE_CL_MISSED_SELECTED.png .\mmi_res_all_image\cc\MMI_RES_DEFAULT\IMAG\callog\IMAGE_CL_MISSED_SELECTED.png


copy .\mmi_res_128x160\cc\MMI_RES_DEFAULT\IMAG\callog\IMAGE_CL_RECEIVED_SELECTED.png .\mmi_res_all_image\cc\MMI_RES_DEFAULT\IMAG\callog\IMAGE_CL_RECEIVED_SELECTED.png
copy .\mmi_res_128x160\cc\MMI_RES_DEFAULT\IMAG\callog\IMAGE_CL_REFUSED_SELECTED.png .\mmi_res_all_image\cc\MMI_RES_DEFAULT\IMAG\callog\IMAGE_CL_REFUSED_SELECTED.png
copy .\mmi_res_128x160\cc\MMI_RES_DEFAULT\IMAG\cc\IMAGE_CC_CONFERENCE_PDA.PNG .\mmi_res_all_image\cc\MMI_RES_DEFAULT\IMAG\cc\IMAGE_CC_CONFERENCE_PDA.PNG





copy .\mmi_res_128x160\pb\MMI_RES_DEFAULT\IMAG\IMAGE_PHONEBOOK_GROUP1.png .\mmi_res_all_image\pb\MMI_RES_DEFAULT\IMAG\IMAGE_PHONEBOOK_GROUP1.png
copy .\mmi_res_128x160\pb\MMI_RES_DEFAULT\IMAG\IMAGE_PHONEBOOK_GROUP2.png .\mmi_res_all_image\pb\MMI_RES_DEFAULT\IMAG\IMAGE_PHONEBOOK_GROUP2.png
copy .\mmi_res_128x160\pb\MMI_RES_DEFAULT\IMAG\IMAGE_PHONEBOOK_GROUP3.png .\mmi_res_all_image\pb\MMI_RES_DEFAULT\IMAG\IMAGE_PHONEBOOK_GROUP3.png
copy .\mmi_res_128x160\pb\MMI_RES_DEFAULT\IMAG\IMAGE_PHONEBOOK_GROUP4.png .\mmi_res_all_image\pb\MMI_RES_DEFAULT\IMAG\IMAGE_PHONEBOOK_GROUP4.png
copy .\mmi_res_128x160\pb\MMI_RES_DEFAULT\IMAG\IMAGE_PHONEBOOK_GROUP_OWNDEF.png .\mmi_res_all_image\pb\MMI_RES_DEFAULT\IMAG\IMAGE_PHONEBOOK_GROUP_OWNDEF.png
copy .\mmi_res_128x160\pb\MMI_RES_DEFAULT\IMAG\IAMGE_PB_DEFAULT_PHOTO.png .\mmi_res_all_image\pb\MMI_RES_DEFAULT\IMAG\IAMGE_PB_DEFAULT_PHOTO.png
copy .\mmi_res_128x160\pb\MMI_RES_DEFAULT\IMAG\IMAGE_PHONEBOOK_SIM1.png .\mmi_res_all_image\pb\MMI_RES_DEFAULT\IMAG\IMAGE_PHONEBOOK_SIM1.png
copy .\mmi_res_128x160\pb\MMI_RES_DEFAULT\IMAG\IMAGE_PHONEBOOK_SIM2.png .\mmi_res_all_image\pb\MMI_RES_DEFAULT\IMAG\IMAGE_PHONEBOOK_SIM2.png
copy .\mmi_res_128x160\pb\MMI_RES_DEFAULT\IMAG\IMAGE_PHONEBOOK_HOME_NUMBER.png .\mmi_res_all_image\pb\MMI_RES_DEFAULT\IMAG\IMAGE_PHONEBOOK_HOME_NUMBER.png
copy .\mmi_res_128x160\pb\MMI_RES_DEFAULT\IMAG\IMAGE_PHONEBOOK_MIDI.png .\mmi_res_all_image\pb\MMI_RES_DEFAULT\IMAG\IMAGE_PHONEBOOK_MIDI.png
copy .\mmi_res_128x160\pb\MMI_RES_DEFAULT\IMAG\IMAGE_PHONEBOOK_NAME.png .\mmi_res_all_image\pb\MMI_RES_DEFAULT\IMAG\IMAGE_PHONEBOOK_NAME.png
copy .\mmi_res_128x160\pb\MMI_RES_DEFAULT\IMAG\IMAGE_PHONEBOOK_PHONE.png .\mmi_res_all_image\pb\MMI_RES_DEFAULT\IMAG\IMAGE_PHONEBOOK_PHONE.png
copy .\mmi_res_128x160\pb\MMI_RES_DEFAULT\IMAG\IMAGE_PHONEBOOK_SELECT_GROUP.png .\mmi_res_all_image\pb\MMI_RES_DEFAULT\IMAG\IMAGE_PHONEBOOK_SELECT_GROUP.png
copy .\mmi_res_128x160\pb\MMI_RES_DEFAULT\IMAG\IMAGE_PHONEBOOK_SELF_NUMBER.png .\mmi_res_all_image\pb\MMI_RES_DEFAULT\IMAG\IMAGE_PHONEBOOK_SELF_NUMBER.png
copy .\mmi_res_128x160\pb\MMI_RES_DEFAULT\IMAG\IMAGE_PHONEBOOK_MOBILE.png .\mmi_res_all_image\pb\MMI_RES_DEFAULT\IMAG\IMAGE_PHONEBOOK_MOBILE.png
copy .\mmi_res_128x160\pb\MMI_RES_DEFAULT\IMAG\IMAGE_PHONEBOOK_TAB_ALL_OFF.png .\mmi_res_all_image\pb\MMI_RES_DEFAULT\IMAG\IMAGE_PHONEBOOK_TAB_ALL_OFF.png
copy .\mmi_res_128x160\pb\MMI_RES_DEFAULT\IMAG\IMAGE_PHONEBOOK_TAB_GROUP_ON.png .\mmi_res_all_image\pb\MMI_RES_DEFAULT\IMAG\IMAGE_PHONEBOOK_TAB_GROUP_ON.png
copy .\mmi_res_128x160\pb\MMI_RES_DEFAULT\IMAG\IMAGE_PHONEBOOK_TAB_GROUP_OFF.png .\mmi_res_all_image\pb\MMI_RES_DEFAULT\IMAG\IMAGE_PHONEBOOK_TAB_GROUP_OFF.png
copy .\mmi_res_128x160\pb\MMI_RES_DEFAULT\IMAG\IMG_PB_MENU_SEARCH_ICON.png .\mmi_res_all_image\pb\MMI_RES_DEFAULT\IMAG\IMG_PB_MENU_SEARCH_ICON.png
copy .\mmi_res_128x160\pb\MMI_RES_DEFAULT\IMAG\IMAGE_PHONEBOOK_TAB_ALL_ON.png .\mmi_res_all_image\pb\MMI_RES_DEFAULT\IMAG\IMAGE_PHONEBOOK_TAB_ALL_ON.png
copy .\mmi_res_128x160\pb\MMI_RES_DEFAULT\IMAG\IMAGE_PHONEBOOK_TOOLBAR_DIAL.png .\mmi_res_all_image\pb\MMI_RES_DEFAULT\IMAG\IMAGE_PHONEBOOK_TOOLBAR_DIAL.png
copy .\mmi_res_128x160\pb\MMI_RES_DEFAULT\IMAG\IMAGE_PB_LIST_NV_ICON.png .\mmi_res_all_image\pb\MMI_RES_DEFAULT\IMAG\IMAGE_PB_LIST_NV_ICON.png
copy .\mmi_res_128x160\pb\MMI_RES_DEFAULT\IMAG\IMAGE_PB_LIST_SIM1_ICON.png .\mmi_res_all_image\pb\MMI_RES_DEFAULT\IMAG\IMAGE_PB_LIST_SIM1_ICON.png
copy .\mmi_res_128x160\pb\MMI_RES_DEFAULT\IMAG\IMAGE_PB_LIST_SIM2_ICON.png .\mmi_res_all_image\pb\MMI_RES_DEFAULT\IMAG\IMAGE_PB_LIST_SIM2_ICON.png








copy .\mmi_res_128x160\pb\MMI_RES_DEFAULT\IMAG\IMAGE_PHONEBOOK_FAX_NUMBER.png .\mmi_res_all_image\pb\MMI_RES_DEFAULT\IMAG\IMAGE_PHONEBOOK_FAX_NUMBER.png
copy .\mmi_res_128x160\pb\MMI_RES_DEFAULT\IMAG\IMAGE_PHONEBOOK_PHONE_NUMBER.png .\mmi_res_all_image\pb\MMI_RES_DEFAULT\IMAG\IMAGE_PHONEBOOK_PHONE_NUMBER.png






copy .\mmi_res_128x160\record\MMI_RES_DEFAULT\IMAG\IMAGE_RECORD_NUMBER_0.png .\mmi_res_all_image\record\MMI_RES_DEFAULT\IMAG\IMAGE_RECORD_NUMBER_0.png
copy .\mmi_res_128x160\record\MMI_RES_DEFAULT\IMAG\IMAGE_RECORD_NUMBER_1.png .\mmi_res_all_image\record\MMI_RES_DEFAULT\IMAG\IMAGE_RECORD_NUMBER_1.png
copy .\mmi_res_128x160\record\MMI_RES_DEFAULT\IMAG\IMAGE_RECORD_NUMBER_2.png .\mmi_res_all_image\record\MMI_RES_DEFAULT\IMAG\IMAGE_RECORD_NUMBER_2.png
copy .\mmi_res_128x160\record\MMI_RES_DEFAULT\IMAG\IMAGE_RECORD_NUMBER_3.png .\mmi_res_all_image\record\MMI_RES_DEFAULT\IMAG\IMAGE_RECORD_NUMBER_3.png
copy .\mmi_res_128x160\record\MMI_RES_DEFAULT\IMAG\IMAGE_RECORD_NUMBER_4.png .\mmi_res_all_image\record\MMI_RES_DEFAULT\IMAG\IMAGE_RECORD_NUMBER_4.png
copy .\mmi_res_128x160\record\MMI_RES_DEFAULT\IMAG\IMAGE_RECORD_NUMBER_5.png .\mmi_res_all_image\record\MMI_RES_DEFAULT\IMAG\IMAGE_RECORD_NUMBER_5.png
copy .\mmi_res_128x160\record\MMI_RES_DEFAULT\IMAG\IMAGE_RECORD_NUMBER_6.png .\mmi_res_all_image\record\MMI_RES_DEFAULT\IMAG\IMAGE_RECORD_NUMBER_6.png
copy .\mmi_res_128x160\record\MMI_RES_DEFAULT\IMAG\IMAGE_RECORD_NUMBER_7.png .\mmi_res_all_image\record\MMI_RES_DEFAULT\IMAG\IMAGE_RECORD_NUMBER_7.png
copy .\mmi_res_128x160\record\MMI_RES_DEFAULT\IMAG\IMAGE_RECORD_NUMBER_8.png .\mmi_res_all_image\record\MMI_RES_DEFAULT\IMAG\IMAGE_RECORD_NUMBER_8.png
copy .\mmi_res_128x160\record\MMI_RES_DEFAULT\IMAG\IMAGE_RECORD_NUMBER_9.png .\mmi_res_all_image\record\MMI_RES_DEFAULT\IMAG\IMAGE_RECORD_NUMBER_9.png
copy .\mmi_res_128x160\record\MMI_RES_DEFAULT\IMAG\IMAGE_RECORD_NUMBER_POINT.png .\mmi_res_all_image\record\MMI_RES_DEFAULT\IMAG\IMAGE_RECORD_NUMBER_POINT.png
copy .\mmi_res_128x160\record\MMI_RES_DEFAULT\IMAG\IMAGE_RECORD_NUMBER_BG.png .\mmi_res_all_image\record\MMI_RES_DEFAULT\IMAG\IMAGE_RECORD_NUMBER_BG.png
copy .\mmi_res_128x160\record\MMI_RES_DEFAULT\IMAG\IMAGE_RECORD_OSD_BG.png .\mmi_res_all_image\record\MMI_RES_DEFAULT\IMAG\IMAGE_RECORD_OSD_BG.png
copy .\mmi_res_128x160\record\MMI_RES_DEFAULT\IMAG\IMAGE_RECORD_RECORD_BG.png .\mmi_res_all_image\record\MMI_RES_DEFAULT\IMAG\IMAGE_RECORD_RECORD_BG.png
copy .\mmi_res_128x160\record\MMI_RES_DEFAULT\IMAG\IMAGE_RECORD_BG.png .\mmi_res_all_image\record\MMI_RES_DEFAULT\IMAG\IMAGE_RECORD_BG.png






copy .\mmi_res_128x160\record\MMI_RES_DEFAULT\IMAG\IMAGE_RECORD_RECORD_BG.png .\mmi_res_all_image\record\MMI_RES_DEFAULT\IMAG\IMAGE_RECORD_RECORD_BG.png



copy .\mmi_res_128x160\tools\MMI_RES_DEFAULT\IMAG\calculator\B\IMAGE_TOOLS_CALCULATOR_EQUAL_BG.png .\mmi_res_all_image\tools\MMI_RES_DEFAULT\IMAG\calculator\B\IMAGE_TOOLS_CALCULATOR_EQUAL_BG.png
copy .\mmi_res_128x160\tools\MMI_RES_DEFAULT\IMAG\calculator\B\IMAGE_TOOLS_CALCULATOR_NUMBER_BG.png .\mmi_res_all_image\tools\MMI_RES_DEFAULT\IMAG\calculator\B\IMAGE_TOOLS_CALCULATOR_NUMBER_BG.png
copy .\mmi_res_128x160\tools\MMI_RES_DEFAULT\IMAG\calculator\B\IMAGE_TOOLS_CALCULATOR_OTHER_BG.png .\mmi_res_all_image\tools\MMI_RES_DEFAULT\IMAG\calculator\B\IMAGE_TOOLS_CALCULATOR_OTHER_BG.png
copy .\mmi_res_128x160\tools\MMI_RES_DEFAULT\IMAG\calculator\B\IMAGE_TOOLS_CALCULATOR_PRESSED_BG.png .\mmi_res_all_image\tools\MMI_RES_DEFAULT\IMAG\calculator\B\IMAGE_TOOLS_CALCULATOR_PRESSED_BG.png
copy .\mmi_res_128x160\tools\MMI_RES_DEFAULT\IMAG\converter\IMAGE_CONVERTER_MENUICON_DEFAULT.png .\mmi_res_all_image\tools\MMI_RES_DEFAULT\IMAG\converter\IMAGE_CONVERTER_MENUICON_DEFAULT.png
copy .\mmi_res_128x160\tools\MMI_RES_DEFAULT\IMAG\converter\IMAGE_CONVERTER_MENUICON_PRESSED.png .\mmi_res_all_image\tools\MMI_RES_DEFAULT\IMAG\converter\IMAGE_CONVERTER_MENUICON_PRESSED.png
copy .\mmi_res_128x160\tools\MMI_RES_DEFAULT\IMAG\converter\IMAGE_CONVERTER_MENU_DEFAULT.png .\mmi_res_all_image\tools\MMI_RES_DEFAULT\IMAG\converter\IMAGE_CONVERTER_MENU_DEFAULT.png
copy .\mmi_res_128x160\tools\MMI_RES_DEFAULT\IMAG\converter\IMAGE_CONVERTER_MENU_PRESSED.png .\mmi_res_all_image\tools\MMI_RES_DEFAULT\IMAG\converter\IMAGE_CONVERTER_MENU_PRESSED.png
copy .\mmi_res_128x160\clock\MMI_RES_DEFAULT\IMAG\Alarm\IMAGE_CLOCK_ALARM_ALERT.png .\mmi_res_all_image\clock\MMI_RES_DEFAULT\IMAG\Alarm\IMAGE_CLOCK_ALARM_ALERT.png
copy .\mmi_res_128x160\clock\MMI_RES_DEFAULT\IMAG\Alarm\IMAGE_CLOCK_ALARM_WEEK_PRESSED.png .\mmi_res_all_image\clock\MMI_RES_DEFAULT\IMAG\Alarm\IMAGE_CLOCK_ALARM_WEEK_PRESSED.png
copy .\mmi_res_128x160\clock\MMI_RES_DEFAULT\IMAG\Alarm\IMAGE_CLOCK_ALARM_WEEK_ENABLED.png .\mmi_res_all_image\clock\MMI_RES_DEFAULT\IMAG\Alarm\IMAGE_CLOCK_ALARM_WEEK_ENABLED.png
copy .\mmi_res_128x160\clock\MMI_RES_DEFAULT\IMAG\Alarm\IMAGE_CLOCK_ALARM_WEEK_DISABLED.png .\mmi_res_all_image\clock\MMI_RES_DEFAULT\IMAG\Alarm\IMAGE_CLOCK_ALARM_WEEK_DISABLED.png
copy .\mmi_res_128x160\clock\MMI_RES_DEFAULT\IMAG\Alarm\IMAGE_CLOCK_ALARM_WEEK_MARK.png .\mmi_res_all_image\clock\MMI_RES_DEFAULT\IMAG\Alarm\IMAGE_CLOCK_ALARM_WEEK_MARK.png


copy .\mmi_res_128x160\alarm\MMI_RES_DEFAULT\IMAG\Schedule\IMAGE_ALARM_ARRANGE.bmp .\mmi_res_all_image\alarm\MMI_RES_DEFAULT\IMAG\Schedule\IMAGE_ALARM_ARRANGE.bmp
copy .\mmi_res_128x160\clock\MMI_RES_DEFAULT\IMAG\Calendar\IMAGE_CLOCK_CALENDAR_ALERT.png .\mmi_res_all_image\clock\MMI_RES_DEFAULT\IMAG\Calendar\IMAGE_CLOCK_CALENDAR_ALERT.png
copy .\mmi_res_128x160\clock\MMI_RES_DEFAULT\IMAG\Calendar\IMAGE_CLOCK_CALENDAR_BG.png .\mmi_res_all_image\clock\MMI_RES_DEFAULT\IMAG\Calendar\IMAGE_CLOCK_CALENDAR_BG.png
copy .\mmi_res_128x160\clock\MMI_RES_DEFAULT\IMAG\Calendar\IMAGE_CLOCK_CALENDAR_COMMENT.png .\mmi_res_all_image\clock\MMI_RES_DEFAULT\IMAG\Calendar\IMAGE_CLOCK_CALENDAR_COMMENT.png
copy .\mmi_res_128x160\clock\MMI_RES_DEFAULT\IMAG\Calendar\IMAGE_CLOCK_CALENDAR_DEFAULT.png .\mmi_res_all_image\clock\MMI_RES_DEFAULT\IMAG\Calendar\IMAGE_CLOCK_CALENDAR_DEFAULT.png
copy .\mmi_res_128x160\clock\MMI_RES_DEFAULT\IMAG\Calendar\IMAGE_CLOCK_CALENDAR_FOCUSED.png .\mmi_res_all_image\clock\MMI_RES_DEFAULT\IMAG\Calendar\IMAGE_CLOCK_CALENDAR_FOCUSED.png
copy .\mmi_res_128x160\clock\MMI_RES_DEFAULT\IMAG\Calendar\IMAGE_CLOCK_CALENDAR_GREEN_DEFAULT.png .\mmi_res_all_image\clock\MMI_RES_DEFAULT\IMAG\Calendar\IMAGE_CLOCK_CALENDAR_GREEN_DEFAULT.png
copy .\mmi_res_128x160\alarm\MMI_RES_DEFAULT\IMAG\Calendar\IMAGE_CALENDAR_WEEK_BG.png .\mmi_res_all_image\alarm\MMI_RES_DEFAULT\IMAG\Calendar\IMAGE_CALENDAR_WEEK_BG.png

copy .\mmi_res_128x160\clock\MMI_RES_DEFAULT\IMAG\Calendar\IMAGE_CLOCK_CALENDAR_ORANGE_DEFAULT.png .\mmi_res_all_image\clock\MMI_RES_DEFAULT\IMAG\Calendar\IMAGE_CLOCK_CALENDAR_ORANGE_DEFAULT.png
copy .\mmi_res_128x160\clock\MMI_RES_DEFAULT\IMAG\Calendar\IMAGE_CLOCK_CALENDAR_LEFT_DEFAULT.png .\mmi_res_all_image\clock\MMI_RES_DEFAULT\IMAG\Calendar\IMAGE_CLOCK_CALENDAR_LEFT_DEFAULT.png
copy .\mmi_res_128x160\clock\MMI_RES_DEFAULT\IMAG\Calendar\IMAGE_CLOCK_CALENDAR_RIGHT_DEFAULT.png .\mmi_res_all_image\clock\MMI_RES_DEFAULT\IMAG\Calendar\IMAGE_CLOCK_CALENDAR_RIGHT_DEFAULT.png
copy .\mmi_res_128x160\clock\MMI_RES_DEFAULT\IMAG\Calendar\IMAGE_CLOCK_CALENDAR_LEFT_PRESSED.png .\mmi_res_all_image\clock\MMI_RES_DEFAULT\IMAG\Calendar\IMAGE_CLOCK_CALENDAR_LEFT_PRESSED.png
copy .\mmi_res_128x160\clock\MMI_RES_DEFAULT\IMAG\Calendar\IMAGE_CLOCK_CALENDAR_RIGHT_PRESSED.png .\mmi_res_all_image\clock\MMI_RES_DEFAULT\IMAG\Calendar\IMAGE_CLOCK_CALENDAR_RIGHT_PRESSED.png
copy .\mmi_res_128x160\clock\MMI_RES_DEFAULT\IMAG\stopwatch\IMAGE_CLOCK_STOPWATCH_RESET_DEFAULT.png .\mmi_res_all_image\clock\MMI_RES_DEFAULT\IMAG\stopwatch\IMAGE_CLOCK_STOPWATCH_RESET_DEFAULT.png
copy .\mmi_res_128x160\clock\MMI_RES_DEFAULT\IMAG\stopwatch\IMAGE_CLOCK_STOPWATCH_RESET_PRESSED.png .\mmi_res_all_image\clock\MMI_RES_DEFAULT\IMAG\stopwatch\IMAGE_CLOCK_STOPWATCH_RESET_PRESSED.png
copy .\mmi_res_128x160\clock\MMI_RES_DEFAULT\IMAG\stopwatch\IMAGE_CLOCK_STOPWATCH_START_PRESSED.png .\mmi_res_all_image\clock\MMI_RES_DEFAULT\IMAG\stopwatch\IMAGE_CLOCK_STOPWATCH_START_PRESSED.png
copy .\mmi_res_128x160\clock\MMI_RES_DEFAULT\IMAG\stopwatch\IMAGE_CLOCK_STOPWATCH_START.png .\mmi_res_all_image\clock\MMI_RES_DEFAULT\IMAG\stopwatch\IMAGE_CLOCK_STOPWATCH_START.png
copy .\mmi_res_128x160\clock\MMI_RES_DEFAULT\IMAG\stopwatch\IMAGE_CLOCK_STOPWATCH_STOP.png .\mmi_res_all_image\clock\MMI_RES_DEFAULT\IMAG\stopwatch\IMAGE_CLOCK_STOPWATCH_STOP.png
copy .\mmi_res_128x160\clock\MMI_RES_DEFAULT\IMAG\stopwatch\IMAGE_CLOCK_STOPWATCH_STOP_PRESSED.png .\mmi_res_all_image\clock\MMI_RES_DEFAULT\IMAG\stopwatch\IMAGE_CLOCK_STOPWATCH_STOP_PRESSED.png
copy .\mmi_res_128x160\clock\MMI_RES_DEFAULT\IMAG\stopwatch\IMAGE_CLOCK_ALARM_STOPWATCH_DEFAULT.png .\mmi_res_all_image\clock\MMI_RES_DEFAULT\IMAG\stopwatch\IMAGE_CLOCK_ALARM_STOPWATCH_DEFAULT.png
copy .\mmi_res_128x160\clock\MMI_RES_DEFAULT\IMAG\stopwatch\IMAGE_CLOCK_ALARM_STOPWATCH_FOCUSED.png .\mmi_res_all_image\clock\MMI_RES_DEFAULT\IMAG\stopwatch\IMAGE_CLOCK_ALARM_STOPWATCH_FOCUSED.png

copy .\mmi_res_128x160\clock\MMI_RES_DEFAULT\IMAG\worldclock\IMAGE_CLOCK_WORLDCLOCK_DST.png .\mmi_res_all_image\clock\MMI_RES_DEFAULT\IMAG\worldclock\IMAGE_CLOCK_WORLDCLOCK_DST.png
copy .\mmi_res_128x160\clock\MMI_RES_DEFAULT\IMAG\Alarm\IMAGE_CLOCK_ALARM_ALERT.png .\mmi_res_all_image\clock\MMI_RES_DEFAULT\IMAG\Alarm\IMAGE_CLOCK_ALARM_ALERT.png
copy .\mmi_res_128x160\clock\MMI_RES_DEFAULT\IMAG\Alarm\IMAGE_CLOCK_ALARM_WEEK_ENABLED.png .\mmi_res_all_image\clock\MMI_RES_DEFAULT\IMAG\Alarm\IMAGE_CLOCK_ALARM_WEEK_ENABLED.png
copy .\mmi_res_128x160\clock\MMI_RES_DEFAULT\IMAG\Alarm\IMAGE_CLOCK_ALARM_WEEK_DISABLED.png .\mmi_res_all_image\clock\MMI_RES_DEFAULT\IMAG\Alarm\IMAGE_CLOCK_ALARM_WEEK_DISABLED.png
copy .\mmi_res_128x160\clock\MMI_RES_DEFAULT\IMAG\Alarm\IMAGE_CLOCK_ALARM_WEEK_MARK.png .\mmi_res_all_image\clock\MMI_RES_DEFAULT\IMAG\Alarm\IMAGE_CLOCK_ALARM_WEEK_MARK.png
copy .\mmi_res_128x160\clock\MMI_RES_DEFAULT\IMAG\Calendar\IMAGE_CLOCK_CALENDAR_COMMENT.png .\mmi_res_all_image\clock\MMI_RES_DEFAULT\IMAG\Calendar\IMAGE_CLOCK_CALENDAR_COMMENT.png
copy .\mmi_res_128x160\clock\MMI_RES_DEFAULT\IMAG\Calendar\IMAGE_CLOCK_CALENDAR_DEFAULT.png .\mmi_res_all_image\clock\MMI_RES_DEFAULT\IMAG\Calendar\IMAGE_CLOCK_CALENDAR_DEFAULT.png
copy .\mmi_res_128x160\clock\MMI_RES_DEFAULT\IMAG\Calendar\IMAGE_CLOCK_CALENDAR_FOCUSED.png .\mmi_res_all_image\clock\MMI_RES_DEFAULT\IMAG\Calendar\IMAGE_CLOCK_CALENDAR_FOCUSED.png
copy .\mmi_res_128x160\clock\MMI_RES_DEFAULT\IMAG\Calendar\IMAGE_CLOCK_CALENDAR_GREEN_DEFAULT.png .\mmi_res_all_image\clock\MMI_RES_DEFAULT\IMAG\Calendar\IMAGE_CLOCK_CALENDAR_GREEN_DEFAULT.png
copy .\mmi_res_128x160\alarm\MMI_RES_DEFAULT\IMAG\Calendar\IMAGE_CALENDAR_WEEK_BG.png .\mmi_res_all_image\alarm\MMI_RES_DEFAULT\IMAG\Calendar\IMAGE_CALENDAR_WEEK_BG.png

copy .\mmi_res_128x160\clock\MMI_RES_DEFAULT\IMAG\Calendar\IMAGE_CLOCK_CALENDAR_LEFT_DEFAULT.png .\mmi_res_all_image\clock\MMI_RES_DEFAULT\IMAG\Calendar\IMAGE_CLOCK_CALENDAR_LEFT_DEFAULT.png
copy .\mmi_res_128x160\clock\MMI_RES_DEFAULT\IMAG\Calendar\IMAGE_CLOCK_CALENDAR_RIGHT_DEFAULT.png .\mmi_res_all_image\clock\MMI_RES_DEFAULT\IMAG\Calendar\IMAGE_CLOCK_CALENDAR_RIGHT_DEFAULT.png
copy .\mmi_res_128x160\clock\MMI_RES_DEFAULT\IMAG\Calendar\IMAGE_CLOCK_CALENDAR_COMMENT.png .\mmi_res_all_image\clock\MMI_RES_DEFAULT\IMAG\Calendar\IMAGE_CLOCK_CALENDAR_COMMENT.png
copy .\mmi_res_128x160\clock\MMI_RES_DEFAULT\IMAG\Calendar\IMAGE_CLOCK_CALENDAR_DEFAULT.png .\mmi_res_all_image\clock\MMI_RES_DEFAULT\IMAG\Calendar\IMAGE_CLOCK_CALENDAR_DEFAULT.png
copy .\mmi_res_128x160\clock\MMI_RES_DEFAULT\IMAG\Calendar\IMAGE_CLOCK_CALENDAR_FOCUSED.png .\mmi_res_all_image\clock\MMI_RES_DEFAULT\IMAG\Calendar\IMAGE_CLOCK_CALENDAR_FOCUSED.png
copy .\mmi_res_128x160\clock\MMI_RES_DEFAULT\IMAG\Calendar\IMAGE_CLOCK_CALENDAR_GREEN_DEFAULT.png .\mmi_res_all_image\clock\MMI_RES_DEFAULT\IMAG\Calendar\IMAGE_CLOCK_CALENDAR_GREEN_DEFAULT.png
copy .\mmi_res_128x160\alarm\MMI_RES_DEFAULT\IMAG\Calendar\IMAGE_CALENDAR_WEEK_BG.png .\mmi_res_all_image\alarm\MMI_RES_DEFAULT\IMAG\Calendar\IMAGE_CALENDAR_WEEK_BG.png

copy .\mmi_res_128x160\connection\MMI_RES_DEFAULT\IMAG\IMAGE_CONNECTION_LINK_ITEM_RO.bmp .\mmi_res_all_image\connection\MMI_RES_DEFAULT\IMAG\IMAGE_CONNECTION_LINK_ITEM_RO.bmp
copy .\mmi_res_128x160\connection\MMI_RES_DEFAULT\IMAG\IMAGE_CONNECTION_LINK_ITEM_RW.bmp .\mmi_res_all_image\connection\MMI_RES_DEFAULT\IMAG\IMAGE_CONNECTION_LINK_ITEM_RW.bmp
copy .\mmi_res_128x160\files_manager\MMI_RES_DEFAULT\IMAG\IMAGE_FMM_FILE_UDISK_ICON.png .\mmi_res_all_image\files_manager\MMI_RES_DEFAULT\IMAG\IMAGE_FMM_FILE_UDISK_ICON.png
copy .\mmi_res_128x160\files_manager\MMI_RES_DEFAULT\IMAG\IMAGE_FMM_FOLDER_ICON.png .\mmi_res_all_image\files_manager\MMI_RES_DEFAULT\IMAG\IMAGE_FMM_FOLDER_ICON.png
copy .\mmi_res_128x160\files_manager\MMI_RES_DEFAULT\IMAG\IMAGE_FMM_UDISK_FOCUSED.png .\mmi_res_all_image\files_manager\MMI_RES_DEFAULT\IMAG\IMAGE_FMM_UDISK_FOCUSED.png
copy .\mmi_res_128x160\files_manager\MMI_RES_DEFAULT\IMAG\IMAGE_FMM_SDCARD_FOCUSED.png .\mmi_res_all_image\files_manager\MMI_RES_DEFAULT\IMAG\IMAGE_FMM_SDCARD_FOCUSED.png
copy .\mmi_res_128x160\files_manager\MMI_RES_DEFAULT\IMAG\IMAGE_FMM_SDCARD1_FOCUSED.png .\mmi_res_all_image\files_manager\MMI_RES_DEFAULT\IMAG\IMAGE_FMM_SDCARD1_FOCUSED.png
copy .\mmi_res_128x160\files_manager\MMI_RES_DEFAULT\IMAG\IMAGE_FMM_UDISK_RELEASED.png .\mmi_res_all_image\files_manager\MMI_RES_DEFAULT\IMAG\IMAGE_FMM_UDISK_RELEASED.png
copy .\mmi_res_128x160\files_manager\MMI_RES_DEFAULT\IMAG\IMAGE_FMM_SDCARD_RELEASED.png .\mmi_res_all_image\files_manager\MMI_RES_DEFAULT\IMAG\IMAGE_FMM_SDCARD_RELEASED.png
copy .\mmi_res_128x160\files_manager\MMI_RES_DEFAULT\IMAG\IMAGE_FMM_SDCARD1_RELEASED.png .\mmi_res_all_image\files_manager\MMI_RES_DEFAULT\IMAG\IMAGE_FMM_SDCARD1_RELEASED.png
copy .\mmi_res_128x160\drm\MMI_RES_DEFAULT\IMAG\IMAGE_DRM_PROMPT_ICON.png .\mmi_res_all_image\drm\MMI_RES_DEFAULT\IMAG\IMAGE_DRM_PROMPT_ICON.png
copy .\mmi_res_128x160\drm\MMI_RES_DEFAULT\IMAG\IMAGE_DRM_AUDIO_LOCK_ICON.png .\mmi_res_all_image\drm\MMI_RES_DEFAULT\IMAG\IMAGE_DRM_AUDIO_LOCK_ICON.png
copy .\mmi_res_128x160\drm\MMI_RES_DEFAULT\IMAG\IMAGE_DRM_AUDIO_UNLOCK_ICON.png .\mmi_res_all_image\drm\MMI_RES_DEFAULT\IMAG\IMAGE_DRM_AUDIO_UNLOCK_ICON.png
copy .\mmi_res_128x160\drm\MMI_RES_DEFAULT\IMAG\IMAGE_DRM_IMAGE_LOCK_ICON.png .\mmi_res_all_image\drm\MMI_RES_DEFAULT\IMAG\IMAGE_DRM_IMAGE_LOCK_ICON.png
copy .\mmi_res_128x160\drm\MMI_RES_DEFAULT\IMAG\IMAGE_DRM_IMAGE_UNLOCK_ICON.png .\mmi_res_all_image\drm\MMI_RES_DEFAULT\IMAG\IMAGE_DRM_IMAGE_UNLOCK_ICON.png
copy .\mmi_res_128x160\drm\MMI_RES_DEFAULT\IMAG\IMAGE_DRM_UNKNOWN_LOCK_ICON.png .\mmi_res_all_image\drm\MMI_RES_DEFAULT\IMAG\IMAGE_DRM_UNKNOWN_LOCK_ICON.png
copy .\mmi_res_128x160\drm\MMI_RES_DEFAULT\IMAG\IMAGE_DRM_UNKNOWN_UNLOCK_ICON.png .\mmi_res_all_image\drm\MMI_RES_DEFAULT\IMAG\IMAGE_DRM_UNKNOWN_UNLOCK_ICON.png
copy .\mmi_res_128x160\drm\MMI_RES_DEFAULT\IMAG\IMAGE_DRM_VIDEO_LOCK_ICON.png .\mmi_res_all_image\drm\MMI_RES_DEFAULT\IMAG\IMAGE_DRM_VIDEO_LOCK_ICON.png
copy .\mmi_res_128x160\drm\MMI_RES_DEFAULT\IMAG\IMAGE_DRM_VIDEO_UNLOCK_ICON.png .\mmi_res_all_image\drm\MMI_RES_DEFAULT\IMAG\IMAGE_DRM_VIDEO_UNLOCK_ICON.png
copy .\mmi_res_128x160\drm\MMI_RES_DEFAULT\IMAG\IMAGE_DRM_PIC_UNKNOW_ICON.png .\mmi_res_all_image\drm\MMI_RES_DEFAULT\IMAG\IMAGE_DRM_PIC_UNKNOW_ICON.png
copy .\mmi_res_128x160\drm\MMI_RES_DEFAULT\IMAG\IMAGE_DRM_PIC_LOCK_ICON.png .\mmi_res_all_image\drm\MMI_RES_DEFAULT\IMAG\IMAGE_DRM_PIC_LOCK_ICON.png
copy .\mmi_res_128x160\drm\MMI_RES_DEFAULT\IMAG\IMAGE_DRM_PIC_UNLOCK_ICON.png .\mmi_res_all_image\drm\MMI_RES_DEFAULT\IMAG\IMAGE_DRM_PIC_UNLOCK_ICON.png
copy .\mmi_res_128x160\pic_viewer\MMI_RES_DEFAULT\IMAG\IMAGE_PICVIEW_CHANGE_FOLDER.png .\mmi_res_all_image\pic_viewer\MMI_RES_DEFAULT\IMAG\IMAGE_PICVIEW_CHANGE_FOLDER.png
copy .\mmi_res_128x160\pic_viewer\MMI_RES_DEFAULT\IMAG\IMAGE_PICVIEW_OSD_BG.png .\mmi_res_all_image\pic_viewer\MMI_RES_DEFAULT\IMAG\IMAGE_PICVIEW_OSD_BG.png
copy .\mmi_res_128x160\pic_viewer\MMI_RES_DEFAULT\IMAG\IMAGE_PICVIEW_CAMERA.png .\mmi_res_all_image\pic_viewer\MMI_RES_DEFAULT\IMAG\IMAGE_PICVIEW_CAMERA.png
copy .\mmi_res_128x160\pic_viewer\MMI_RES_DEFAULT\IMAG\IMAGE_PICVIEW_FOLDER_DEFAULT_ICON.png .\mmi_res_all_image\pic_viewer\MMI_RES_DEFAULT\IMAG\IMAGE_PICVIEW_FOLDER_DEFAULT_ICON.png
copy .\mmi_res_128x160\pic_viewer\MMI_RES_DEFAULT\IMAG\IMAGE_PICVIEW_PIC_ERROR_ICON.png .\mmi_res_all_image\pic_viewer\MMI_RES_DEFAULT\IMAG\IMAGE_PICVIEW_PIC_ERROR_ICON.png
copy .\mmi_res_128x160\pic_viewer\MMI_RES_DEFAULT\IMAG\IMAGE_PICVIEW_TIME_BG.png .\mmi_res_all_image\pic_viewer\MMI_RES_DEFAULT\IMAG\IMAGE_PICVIEW_TIME_BG.png
copy .\mmi_res_128x160\pic_viewer\MMI_RES_DEFAULT\IMAG\IMAGE_PICVIEW_OSD_BG.png .\mmi_res_all_image\pic_viewer\MMI_RES_DEFAULT\IMAG\IMAGE_PICVIEW_OSD_BG.png
copy .\mmi_res_128x160\videoplayer\MMI_RES_DEFAULT\IMAG\IMAGE_VP_DEFAULT_PIC.png .\mmi_res_all_image\videoplayer\MMI_RES_DEFAULT\IMAG\IMAGE_VP_DEFAULT_PIC.png
copy .\mmi_res_128x160\videoplayer\MMI_RES_DEFAULT\IMAG\IMAGE_VP_MY_VIDEO_ICON.png .\mmi_res_all_image\videoplayer\MMI_RES_DEFAULT\IMAG\IMAGE_VP_MY_VIDEO_ICON.png
copy .\mmi_res_128x160\videoplayer\MMI_RES_DEFAULT\IMAG\IMAGE_VP_VIDEO_LIST_ICON.png .\mmi_res_all_image\videoplayer\MMI_RES_DEFAULT\IMAG\IMAGE_VP_VIDEO_LIST_ICON.png
copy .\mmi_res_128x160\videoplayer\MMI_RES_DEFAULT\IMAG\IMAGE_VP_MY_VIDEO_FOCUS_ICON.png .\mmi_res_all_image\videoplayer\MMI_RES_DEFAULT\IMAG\IMAGE_VP_MY_VIDEO_FOCUS_ICON.png
copy .\mmi_res_128x160\videoplayer\MMI_RES_DEFAULT\IMAG\IMAGE_VP_VIDEO_LIST_FOCUS_ICON.png .\mmi_res_all_image\videoplayer\MMI_RES_DEFAULT\IMAG\IMAGE_VP_VIDEO_LIST_FOCUS_ICON.png
copy .\mmi_res_128x160\videoplayer\MMI_RES_DEFAULT\IMAG\IMAGE_VP_PROCESSBAR_BG.png .\mmi_res_all_image\videoplayer\MMI_RES_DEFAULT\IMAG\IMAGE_VP_PROCESSBAR_BG.png
copy .\mmi_res_128x160\videoplayer\MMI_RES_DEFAULT\IMAG\IMAGE_VP_TITLE_BAR.png .\mmi_res_all_image\videoplayer\MMI_RES_DEFAULT\IMAG\IMAGE_VP_TITLE_BAR.png
copy .\mmi_res_128x160\game_boxman\MMI_RES_DEFAULT\IMAG\IMAGE_BOXMAN_AIM.bmp .\mmi_res_all_image\game_boxman\MMI_RES_DEFAULT\IMAG\IMAGE_BOXMAN_AIM.bmp
copy .\mmi_res_128x160\game_boxman\MMI_RES_DEFAULT\IMAG\IMAGE_BOXMAN_BOX.bmp .\mmi_res_all_image\game_boxman\MMI_RES_DEFAULT\IMAG\IMAGE_BOXMAN_BOX.bmp
copy .\mmi_res_128x160\game_boxman\MMI_RES_DEFAULT\IMAG\IMAGE_BOXMAN_BOX_IN_AIM.bmp .\mmi_res_all_image\game_boxman\MMI_RES_DEFAULT\IMAG\IMAGE_BOXMAN_BOX_IN_AIM.bmp
copy .\mmi_res_128x160\game_boxman\MMI_RES_DEFAULT\IMAG\IMAGE_BOXMAN_BUTTON.bmp .\mmi_res_all_image\game_boxman\MMI_RES_DEFAULT\IMAG\IMAGE_BOXMAN_BUTTON.bmp
copy .\mmi_res_128x160\game_boxman\MMI_RES_DEFAULT\IMAG\IMAGE_BOXMAN_MAN.bmp .\mmi_res_all_image\game_boxman\MMI_RES_DEFAULT\IMAG\IMAGE_BOXMAN_MAN.bmp
copy .\mmi_res_128x160\game_boxman\MMI_RES_DEFAULT\IMAG\IMAGE_BOXMAN_MAN_IN_AIM.bmp .\mmi_res_all_image\game_boxman\MMI_RES_DEFAULT\IMAG\IMAGE_BOXMAN_MAN_IN_AIM.bmp
copy .\mmi_res_128x160\game_boxman\MMI_RES_DEFAULT\IMAG\IMAGE_BOXMAN_SPACE.bmp .\mmi_res_all_image\game_boxman\MMI_RES_DEFAULT\IMAG\IMAGE_BOXMAN_SPACE.bmp
copy .\mmi_res_128x160\game_boxman\MMI_RES_DEFAULT\IMAG\IMAGE_BOXMAN_WALL.bmp .\mmi_res_all_image\game_boxman\MMI_RES_DEFAULT\IMAG\IMAGE_BOXMAN_WALL.bmp
copy .\mmi_res_128x160\game_boxman\MMI_RES_DEFAULT\IMAG\IMAGE_BOXMAN_WALLOUT.bmp .\mmi_res_all_image\game_boxman\MMI_RES_DEFAULT\IMAG\IMAGE_BOXMAN_WALLOUT.bmp

